graphql-java/graphql-java

src/main/java/graphql/introspection/Introspection.java

This fixes graphiql when no mutations are present in the schema

mutationType is optional

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SimpleExecutionStrategy.java
src/test/groovy/graphql/HelloWorld.java

Use ExecutionResults for resolveField (and its protected calls) to allow greater customization (necessary for rx to be able to stay inside the monad while resolving fields as much as possible)

Change ExecutionStrategy to use ExecutionResults all the way down

---

src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/SchemaUtil.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy

With the current API, only concrete instances which are registered somewhere from the query or mutation root are registered.  This makes writting tools to automatically generate types a PITA - specifically because you have to ensure there is at least one concrete instance of every type registered.
This change provides a way to pass a set of types into the schema when building it, which will be added into the set of available types when replacing type references.
An alternative could be to provide a resolver to GraphQLTypeReference, which would be used to resolve the type at build time - however, this method seems far less intrusive for existing consumers :-)

Allow providing additional types to schema build.

---

README.md
src/test/groovy/graphql/GarfieldSchema.java

Also, static import `newUnionType` method in `GarfieldSchema.java` to make it consistent with the example and other imports in GarfieldSchema.

Fix example for GraphQLUnionType

---

src/main/java/graphql/relay/Relay.java

To match the spec: _(...) A field that returns a Connection Type must include **forward pagination arguments**, **backward pagination arguments**, or both. (...)_

Support for only backward or forward pagination arguments

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java

Some erroneous HTML tags were added in b603ffa that cause the Gradle javadoc
task to fail with errors.

Fix invalid javadoc in BatchedExecutionStrategy

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/language/IntValue.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/test/groovy/graphql/ScalarsTest.groovy

IntValue now stores BigInteger instead of int. GraphQLInt and
GraphQLLong parseLiteral will throw if the value overflows int or long
respectively.
StringValue parsing for GraphQLLong is still supported for backwards
compatibility.
Add a test for parsing GraphQLLong larger than INT_MAX.

Support IntValue tokens with larger value than INT_MAX

---

src/main/java/graphql/Scalars.java
src/test/groovy/graphql/ScalarsTest.groovy

Hello!
We noticed a problem with the GraphQLFloat data type. If you send a literal number e.g. `2`, it will be parsed as IntValue and therefore throw an exception in the Scalars.parseLiteral for floats. There is a workaround to send e.g. `2.00001` but probably integers should be accepted here.
-Markku
https://github.com/HSLdevcom/digitransit-ui

Support parsing IntValue literals into GraphQLFloat

---

src/main/java/graphql/ExceptionWhileDataFetching.java

Some JDK APIs such as CompletableFutures generate Throwables instead of
Exceptions.
Exception has no additional methods than Throwable, and all tests are passing.

Throwable cause instead of Exception

---

src/main/java/graphql/Directives.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/validation/rules/KnownDirectives.java
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/schema/SchemaUtilTest.groovy

When using the introspection query that is supplied with the latest version of graphql npm package (currently 0.5.0) the query uses a `locations` key that is not supported in graphql-java 2.0.0.
See also: http://facebook.github.io/graphql/#sec-The-__Directive-Type
At the moment the compatibility level of graphql-java is not really clear as stated in #132 
This pull request does not solve that but ups the compatibility to the latest graphql spec, and its introspection query (see: https://github.com/graphql/graphql-js/blob/0b72e7038761bec9fb5319cc08ea93ff8b071a9c/src/utilities/introspectionQuery.js).

Support for directive.locations in introspection query

---

.travis.yml
build.gradle

This ensures that only java6 functionality can be used, while compiling with the java8 compiler. source and target versions remain unchanged to 1.6

Build with java6 runtime

---

src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/test/groovy/graphql/ScalarsQuerySchema.java
src/test/groovy/graphql/ScalarsQueryTest.groovy

Escaped characters in string literals were not replaced with the correct character.
A ShouldNotHappenException is thrown on unknown escape codes because these should already be rejected during parsing.

Parse escaped characters in strings

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/DataFetcherTest.groovy

As mentioned in #130 some languages and frameworks uses "get" prefix for `Boolean `types. This was also the case for me. I use Lombok for generating accessors which also uses this convention. Even IDE's generate getters for `Boolean` with "get"
The prefix 'is' generally used for primitive `boolean`, Lombok has a option to disable this but not for `Boolean`. So I think this functionality should be a part of `PropertyDataFetcher`. Otherwise it will be error prone or some unnecessary configuration/code for these fields.

Fix for #130 - Adds support for Boolean property accessors with 'get' prefix in PropertyDataFetcher

---

README.md

The link to the grammar in the Readme.MD file was not up to date.

Fixed link to grammar

---

src/main/java/graphql/validation/LanguageTraversal.java
src/main/java/graphql/validation/RulesVisitor.java
src/test/groovy/graphql/validation/RulesVisitorTest.groovy

Stackoverflow errors happen if you run a query with recursive fragments. While the library has a rule which (correctly) identify recursive fragments when this rule is used in isolation, there are other rules which need to look inside fragment spreads, such as `NoUnusedVariables`. This causes the RulesVisitor itself to go into a loop spreading these fragments and produces a StackOverflow error.
The fix is to add the path history to any new LanguageTraversals which are made, so that before it dives into another fragment it can check if it has opened this fragment in its history already. I've added some tests as well, let me know if the fix / tests are reasonable!
Create any schema and run a query with a recursive fragment against it. For example this introspection query: 
```graphql
{ …
```

Fix validation stack overflow errors

---

src/main/java/graphql/relay/Relay.java

instead of array index out of bound exception

illegal global id should yield illegal argument exception

---

build.gradle

This PR is a patch from @IamCornholio. Thank you @IamCornholio.

Fix #225: remove ANTLR compile dep from published POM

---

src/main/antlr/Graphql.g4
src/test/groovy/graphql/parser/ParserTest.groovy

2.9.2 seems somewhat ambiguous as it indicates a list of digits in fractional part but doesn't specify whether it can be empty or not. `graphql-js` has:
```
if (code === 46) { // .
isFloat = true;
code = charCodeAt.call(body, ++position);
position = readDigits(source, position, code);
code = charCodeAt.call(body, position);
}
```

4. parses as FloatValue

---

README.md

The closing curly bracket and the semicolon were missing from the DataFetcher example.
I also fixed a typo and, even tho its not my native language, I believe "complexer" doesn't exist in English :P

Fixed DataFetcher example and typo in the readme

---

src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/test/groovy/graphql/execution/ExecutionStrategySpec.groovy

mostly immutable and otherwise thread safe
Without this a multi threaded execution strategy will not be able to safely update errors.

#263 - make execution context thread safe 

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Addresses #152 and #106
When resolving an object literal check for any fields which are omitted from
the literal but have a default value. In that case copy the default value to
the result. This fixes #152 (InputObjectType defaultValue is not getting used)
When resolving a variable value that corresponds to an input object type omit
any fields that are not present in the value, unless those fields have a
default value (in which case use the default value) or non null (which should
force an error). This fixes at least one part of #106, Unspecified fields in
Input object are set to null

ValuesResolver fixes for input object literals and variable values

---

src/main/java/graphql/introspection/Introspection.java

From https://github.com/graphql-java/graphql-java/pull/175: 
> * Update introspection for directives. Return values for "locations" (the field used in the latest GraphQL spec) and also for "onOperation", "onFragment" and "onField" (the deprecated fields which our current GraphiQL expects in its schema query).

Fixed directive introspection

---

src/main/antlr/Graphql.g4
src/main/java/graphql/execution/FieldCollector.java
src/main/java/graphql/language/InlineFragment.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/validation/TraversalContext.java
src/main/java/graphql/validation/rules/FragmentsOnCompositeType.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/StarWarsValidationTest.groovy
src/test/groovy/graphql/validation/SpecValidation282Test.groovy

From #175:
> * Fix a problem with the Antlr grammar for inline fragments. It had this:
`inlineFragment : '...' 'on' typeCondition directives? selectionSet;`
That is the "type condition" (on TypeName) was required. Changed it to be optional, which involved changing the grammar, the way we construct the parse tree and then a bunch of new null checks to deal with the case where the type condition is null.

Fixed grammar: type conditions in inline fragments are optional

---

src/main/antlr/Graphql.g4
src/test/groovy/graphql/parser/ParserTest.groovy

Follows up with #243 and fixed #32

Parsing: ensure that keywords can be used as names

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategySpec.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy

Fixes #208 and #97. Use case for me is writing an async execution strategy. A custom mutation strategy is needed to not block on mutation results, even while they are executed serially.

Allow specification of mutation strategy

---

src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLInputFieldsContainer.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/GraphQLTypeReference.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/main/java/graphql/schema/SchemaUtil.java
src/main/java/graphql/schema/TypeReference.java
src/main/java/graphql/schema/validation/InvalidSchemaException.java
src/main/java/graphql/schema/validation/NoUnbrokenInputCycles.java
src/main/java/graphql/schema/validation/ValidationError.java
src/main/java/graphql/schema/validation/ValidationErrorCollector.java
src/main/java/graphql/schema/validation/ValidationErrorType.java
src/main/java/graphql/schema/validation/ValidationRule.java
src/main/java/graphql/schema/validation/Validator.java
src/test/groovy/graphql/TypeReferenceSchema.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy
src/test/groovy/graphql/schema/validation/NoUnbrokenInputCyclesTest.groovy

As described in https://github.com/graphql-java/graphql-java/issues/172 this allows `TypeReference`s to be used as input types, making sure they're properly replaced, in both type and argument definitions.
Worth to note is that it does _not_ add validations that would disallow creating infinitely recursive types, as described in https://github.com/facebook/graphql/issues/189
I need some help/discussion for that. I see a few possible approaches here: add checks GraphQLInputObjectType.Builder#field, so they're ran as the fields are added (not really sure this is possible), add it to GraphQLFieldDefinition.Builder#argument (sounds like it's enough to just run this check for query & mutation roots?), or to GraphQLSchema.Builder#build so they're ran for the entire schema at the end.

#172 Allow TypeReference as InputType

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java

Issue 281: Spec allows for 'extensions' map in result but graphql-java does not.
ExecutionResult changed to have an extensions Map<Object,Object> and
ExecutionResultImpl changed to support it, defaulting to null.

#281: Spec allows for 'extensions' map in result but graphql-java does not

---

src/main/java/graphql/Assert.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionId.java
src/main/java/graphql/execution/ExecutionIdProvider.java
src/test/groovy/graphql/execution/ExecutionIdTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategySpec.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy

As per #278  - This provides a unique id in the execution of a graphql query.  A later PR will provide the ability for api consumers to provide their own ExecutionIds but this gets you 90% on the way

278 unique query idenitifer

---

README.md
src/main/java/graphql/Assert.java
src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/HelloWorld.java
src/test/groovy/graphql/MutationTest.groovy
src/test/groovy/graphql/RelaySchemaTest.groovy
src/test/groovy/graphql/ScalarsQueryTest.groovy
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/StarWarsQueryTest.groovy
src/test/groovy/graphql/UnionTest.groovy
src/test/groovy/graphql/execution/ExecutorServiceExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/batched/GraphqlExecutionSpec.groovy
src/test/groovy/readme/ReadmeExamples.java

#273 - to allow consistency with other parts of the API and extensibility in the future, the builder pattern should be used on the GraphQL object

273 - use builder pattern in GraphQL top level object

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/execution/ExecutionIdTest.groovy

#278  - This now allows the caller to provider their own ExecutionId into the mix.  There is a good default however

Allows a ExecutionProvider to be provided by the caller

---

build.gradle

Plugin [page](https://docs.gradle.org/current/userguide/jacoco_plugin.html) on gradle site.
Coverage report for this pr: [graphql-java](http://exbe.info/projects/graphql-java/)
Do it yourself: 
```
gradle clean test jacocoTestReport
```
Jacoco plugin add yourself after test tasks and one need to call **jacocoTestReport** to generate actual report from collected metrics. Multiple formats are supported and configurable.
The reason why report generation is a manual step is to avoid impact on build time for developers.

Add jacoco plugin. It generates test coverage.

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/InstrumentationContext.java
src/main/java/graphql/execution/instrumentation/NoOpInstrumentation.java
src/main/java/graphql/execution/instrumentation/parameters/DataFetchParameters.java
src/main/java/graphql/execution/instrumentation/parameters/ExecutionParameters.java
src/main/java/graphql/execution/instrumentation/parameters/FieldFetchParameters.java
src/main/java/graphql/execution/instrumentation/parameters/FieldParameters.java
src/main/java/graphql/execution/instrumentation/parameters/ValidationParameters.java
src/test/groovy/graphql/execution/ExecutionStrategySpec.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy

as per #269 the desire here is to be able to measure how long a graphql query is taken
This approach of "return call back " allows for a fairly stateless system if we have multi threaded execution.
So you can "create a timer and then have the end time - start time  be calculated via this created object.

#269 - this adds instrumentation to the execution of the graphql query

---

src/main/java/graphql/Assert.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLTypeReference.java
src/main/java/graphql/schema/GraphQLUnionType.java

Validation of schema names on the server side (not in the query document)

Validate name field matches current spec's conventions

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

ValueResolver makes an assumption that an object passed through
is always going to be a map.
However, when using graphql-java with graphql-java-annotations and
graphql-java-servlet (GraphQLVariables), the inputs passed through
are already resolved.
Solution: this patch allows to pass such objects through the resolver
unmodified, without throwing an exception.

Problem: passing input object as a resolved class doesn't work

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy
src/test/groovy/graphql/schema/somepackage/PackageProtectedImpl.java
src/test/groovy/graphql/schema/somepackage/TestClass.java
src/test/groovy/graphql/schema/somepackage/TwoClassesDown.java

Google's AutoValue library (https://github.com/google/auto/)
generates package-protected implementations of abstract
data classes with abstract public getters. These classes
weren't supported by the PropertyDataFetcher, since invoking
the public method on a package-protected class causes
InvocationTargetException. However, invoking the method
on the public parent class works fine.
These changes look for a public parent class with the applicable
getter method. Behavior with normal style classes should not be
affected.

PropertyDataFetcher supports AutoValue style classes

---

src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

It was throwing an exception while trying to instantiate the interface under test and not an impl of the interface.  Here is what I am seeing:
> gradlew clean build
`PropertyDataFetcherTest.groovy: 10: You cannot create an instance from the abstract interface 'graphql.schema.DataFetchingEnvironment'.
@ line 10, column 16.
return new DataFetchingEnvironment(obj,
^
1 error`

PropertyDataFetcherTest throwing exception

---

src/main/java/graphql/ErrorType.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/InvalidSyntaxError.java
src/main/java/graphql/MutationNotSupportedError.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/schema/validation/InvalidSchemaException.java
src/main/java/graphql/validation/ValidationError.java
src/test/groovy/graphql/GraphQLTest.groovy

#345 outlined that NPEs can happen when mutation strategies are missing
But in fixing that I noticed that we blow up when there is no mutation root type
This is actually valid to NOT have a mutation root type but the spec is unclear on what should happen when "mutation is not allowed".
I am pretty sure that NullPointerException is not the desired response ;)
So I have made it return a new MutationNotSupportedError instead

#345 - mutations are optional and errors should come back if they are missing

---

src/main/antlr/Graphql.g4
src/main/java/graphql/language/AbstractNode.java
src/main/java/graphql/language/Comment.java
src/main/java/graphql/language/Node.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/IDLParserTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy

This retains the comments in the grammar and makes the available on nodes.
This is the first step in allowing a schema generator to turn language defs into descriptions etc...

#325 - retain comments in the parsed document

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java

Allow ExecutionStrategies to specify a `handleDataFetchingException` to allow more customized error handling.
To solve the issue here: https://github.com/graphql-java/graphql-java/issues/282, my team also faced the same issue.

Allow ExecutionStrategy to specify dataFetchingExceptionHandler

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/DataFetcherTest.groovy
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

Fix for #303, but also exposes the `ExecutionId` - it seemed like the only other thing on the `ExecutionContext` that could be useful to know in a `DataFetcher`.

Add fragment definitions and execution id to DataFetchingEnvironment

---

src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/SchemaUtil.java

Renaming the map with extra types for the schema from `dictionary` to `additionalTypes` to make it more clear.
This is a breaking change if somebody is using `GraphQLSchema.getDictionary`, which is normally not the case.

Renaming dictionary argument

---

src/main/java/graphql/validation/RulesVisitor.java
src/main/java/graphql/validation/rules/NoUnusedFragments.java
src/test/groovy/graphql/validation/RulesVisitorTest.groovy
src/test/groovy/graphql/validation/SpecValidation5421Test.groovy

The KnownFragment rule does not seem to be applying properly, instead a nullpointer is thrown. 
Even if `validationContext.getFragment` returns null, it still descends into that node and then throws. 
https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/validation/RulesVisitor.java#L115

Fix handling of UnknownFragment 

---

README.md
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/TypeRuntimeWiring.java
src/test/groovy/graphql/schema/idl/RuntimeWiringTest.groovy
src/test/groovy/graphql/schema/idl/SchemaDecompilerTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/readme/ReadmeExamples.java

A type name is ALWAYS required when building runtime wiring of data fetchers.  This makes more DSL sense

Makes type name specified to builder

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/errors/MissingInterfaceTypeError.java
src/main/java/graphql/schema/idl/errors/SchemaMissingError.java
src/main/java/graphql/schema/idl/errors/SchemaProblem.java
src/main/java/graphql/schema/idl/errors/TypeExtensionFieldRedefinitionError.java
src/main/java/graphql/schema/idl/errors/TypeExtensionMissingBaseTypeError.java
src/test/groovy/graphql/schema/idl/SchemaCompilerTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy
src/test/groovy/readme/README.next.md
src/test/groovy/readme/ReadmeExamples.java

#406 added extend type XXX {} support
this now allows the type extension syntax
type BaseType {
fieldA : Int
}
extend type BaseType {
fieldB : Int
}
This could be in multiple files say to modularize the schema files.
The schema grammar always had these...we just didnt apply them in the generator
I think this should be in 3.x because it fits the "add IDL support" them in 3.x

#406 added extend type XXX {} support

---

src/main/java/graphql/Assert.java
src/main/java/graphql/AssertException.java
src/main/java/graphql/ExceptionWhileDataFetching.java
src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/Internal.java
src/main/java/graphql/PublicApi.java
src/main/java/graphql/PublicSpi.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/FieldCollector.java
src/main/java/graphql/execution/TypeFromAST.java
src/main/java/graphql/schema/DataFetcher.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLList.java
src/main/java/graphql/schema/GraphQLNonNull.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/main/java/graphql/schema/SchemaUtil.java
src/main/java/graphql/schema/TypeResolver.java
src/main/java/graphql/schema/idl/RuntimeWiring.java

This is a first idea how we could handle #284:
There are three different Annotations: 
-`@PublicApi` for public classes/methods/interfaces.
- `@PrivateApi` for private stuff
- `@PublicSpi` for public interfaces/abstract classes which users are expected to implement.

add public/internal/spi annotations

---

src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy

#417 do not overwrite top level schema definition during type registry merge

---

build.gradle

It's always safest to download software over https

Download gradle over https

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/parameters/FieldFetchParameters.java
src/main/java/graphql/execution/instrumentation/parameters/FieldParameters.java

It looks like this is an oversight - the environment isn't passed to `beginField` but is passed to `beginFieldFetch` on the next line.
Without the environment, it's impossible to know the type that the current field is on in `beginField`.

Add environment to field instrumentation.

---

src/main/java/graphql/relay/SimpleListConnection.java
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy

Scenario to reproduce:
Client requests first 3 edges of relay list of list total length 4 at time t.
At time t+1, 
underlying list is mutated at data source, list becomes 2 items shorter.
Length of edge list is now 2, but GraphQL client thinks list is length 4.
At time t+2, 
Client requests some more edges specifying parameter `after` as 3
```
java.lang.IllegalArgumentException: fromIndex(3) > toIndex(2)
at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
at java.util.ArrayList.subList(ArrayList.java:996)
at graphql.relay.SimpleListConnection.get(SimpleListConnection.java:42)
at GraphQL.DataFetchers.lambda$getPlaylistGroupVideosDataFetcher$20(DataFetchers.java:365)
at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
at …
```

Check for invalid SimpleListConnection list indices on client-provided cursor

---

src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

this is a small bugfix for enum field descriptions and a change so that
an empty line in an comment separate a comment from a description (for the IDL)
also: empty lines are not skipped, but are valid comments

bugfix: comments as descriptions

---

src/main/java/graphql/schema/idl/EnumValuesProvider.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/StaticEnumValuesProvider.java
src/main/java/graphql/schema/idl/TypeRuntimeWiring.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Introducing the possibility to define a Java value for each graphql enum value,
when defining a schema via IDL.
Default Implementation for using a Java Enum is `StaticEnumValuesProvider`: 
Example usage:
**Java Enum:**
```java
enum Color {
Blue, 
Red
}
```
**GraphQL Schema Definition:**
```graphql
enum Color {
Blue
Red
}
```
**Creating the Schema:**
```java
StaticEnumValuesProvider colorValues = new StaticEnumValuesProvider(Color.class);
RuntimeWiring.newRuntimeWiring()
.type("Color", typeWiring -> typeWiring.enumValues(colorValues))
....
```

enum values provider

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionParameters.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/NonNullableFieldValidator.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/NonNullableFieldValidatorTest.groovy

A custom scalar could return null and we can now enforce that it matches a non null graphql type

#438 now with double checks in null values that might come out of coercion

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SimpleExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/NoOpInstrumentation.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationDataFetchParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldFetchParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationValidationParameters.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/DataFetcherTest.groovy
src/test/groovy/graphql/execution/ExecutionIdTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy
src/test/groovy/graphql/execution/NonNullableFieldValidatorTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

This adds a explicit `root` object, which is used as the `source` object
for the root query instead of `context`.
Adds also a new `ExecutionInput` to be used as Input for `GraphQL.execute`.
Important: Old `GraphQL.execute` calls are unchanged: `root` is set to `context`
in order to not break it!
other breaking changes (just renaming) made along the way to make the overall
naming better and to avoid confusion with the new `ExecutionInput`:
- `instrumentation.ExecutionParameters` is renamed to `InstrumentationExecutionParameters`
- `instrumentation.ValidationParameters` is renamed to `InstrumentationValidationParameters`
- `ExecutionParameters` is renamed to ExecutionStrategyParameters
- `DataFetchParameters` is renamed to `InstrumentationDataFetchParameters`
- `FieldFetchParameters` is …

add explicit root object

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This addresses #462.
It adds several tests regarding comments as description.
It fixes a bug that input objects were not printed at all.
And it changes the format to not have a space before a colon.

Schema printer comments

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

aligns schema printer and AstPrinter regarding indention and new lines
adds test which completes a full round trip with SchemaPrinter,
Introspection and AstPrinter
changes IntrospectionResultToSchema to only create a SchemaDefinition
if needed because non default names are used

printer improvments

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/SerializationError.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/schema/Coercing.java
src/main/java/graphql/schema/CoercingParseValueException.java
src/main/java/graphql/schema/CoercingSerializeException.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/test/groovy/graphql/ScalarsBigDecimalTest.groovy
src/test/groovy/graphql/ScalarsBigIntegerTest.groovy
src/test/groovy/graphql/ScalarsBooleanTest.groovy
src/test/groovy/graphql/ScalarsByteTest.groovy
src/test/groovy/graphql/ScalarsCharTest.groovy
src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsIDTest.groovy
src/test/groovy/graphql/ScalarsIntTest.groovy
src/test/groovy/graphql/ScalarsLongTest.groovy
src/test/groovy/graphql/ScalarsQueryTest.groovy
src/test/groovy/graphql/ScalarsShortTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy

This PR introduces two different GraphQLException for Coercing serialize/parseValue.
It handles enum values serialization and scalars serialization correctly by catching the exception, adding an Error and setting the value to null.
It is a breaking change, because some protected methods ins `ExecutionStrategy` are changed including the logic (not sure if the logic changes classifie as bug fix or not)

Coercing exception handling

---

docs/execution.rst

There's a very small error in the execution example in the docs. I believe this corrects it.

Correct execution example

---

src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationValidationParameters.java
src/test/groovy/graphql/execution/ExecutionTest.groovy

The goal here was to 
- Hide implementation details in sub-methods, which should
- Make it easier to understand what is happening from a quick read, and
- Make the lifecycle of the instrumentation instances easy to see and validate
I believe that I have not significantly changed when or under what conditions the `onEnd` instrumentation methods are called. Its worth noting that the `onEnd` methods are not guaranteed to be called in all possible error scenarios.

Refactor GraphQL#execute implementation

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/FieldCollectorParameters.java
src/main/java/graphql/execution/TypeInfo.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java

From https://github.com/graphql-java/graphql-java/pull/508
I dont seem to have maintainer access upstream
```
git push tklovett
Counting objects: 27, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (24/24), done.
Writing objects: 100% (27/27), 5.86 KiB | 0 bytes/s, done.
Total 27 (delta 15), reused 0 (delta 0)
remote: Resolving deltas: 100% (15/15), completed with 8 local objects.
To git@github.com:tklovett/graphql-java.git
! [remote rejected] tklovett-builder-consistency -> tklovett-builder-consistency (permission denied)
error: failed to push some refs to 'git@github.com:tklovett/graphql-java.git'
```
Anyway I have this branch with the merge conflicts fixed up

Tklovett builder consistency

---

src/main/java/graphql/execution/ExecutionContextBuilder.java
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy

This fixes an ExecutionContextBuilder bug where root and context was mixed up. (Thanks @LarsKrogJensen for spotting it)
It also adds a unit test for the builder, which was completely missing.

fix and test ExecutionContextBuilder: root and context was mixed up

---

docs/execution.rst
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/preparsed/NoOpPreparsedDocumentProvider.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentContext.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy
src/test/groovy/graphql/execution/preparsed/NoOpPreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentEntryTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedTest.groovy
src/test/groovy/graphql/execution/preparsed/TestingPreparsedDocumentProvider.groovy

Query parsing and validation can be costly in terms of execution performance, this PR introduces a preparsed provider/cache that allows implementations to hook in a cache to avoid re- parse and validation.
Another possible use case could be white listing queries.
One showstopper for this might be that it requires the Document tree to be thread safe, and from what I can see it is not modified after its been created.

Preparsed document provider/cache to avoid costly parse and validation

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SimpleExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/NonNullHandlingTest.groovy
src/test/groovy/graphql/execution/AsyncFetchThenCompleteExecutionTestStrategy.java
src/test/groovy/graphql/execution/BreadthFirstExecutionTestStrategy.java
src/test/groovy/graphql/execution/ExecutionIdTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy

Any serial execution is really an async one that is deemed complete so we are able to implement the existing via this pattern
This puts the structure in place to allow us to write truly asynchronous execution strategies where the consumer gets to decide when to consume the result.
As it turns out we can re-implement all the current serial execution strategies via the CompletableFuture pattern that have completed immediately.  And hence this calls the async versions of everything to get work done.

A start to #324 that provides a promise interface to executing querie

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/GraphQLTest.groovy

Like the other parts of the code that use a builder, it now takes one as input plus used the builder function pattern

graphql.execute can accept a builder

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SimpleExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/AsyncFetchThenCompleteExecutionTestStrategy.java
src/test/groovy/graphql/execution/BreadthFirstExecutionTestStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

While this is a breaking change, its more inline with all the other method parameters
on execution strategy . ie use the "parameters pattern"
In terms of breaking change, since we are going to break the API for async support, we should take the opportunity to clean it up now.

Removed List<Field> from execution strategy signature

---

src/main/java/graphql/validation/rules/KnownDirectives.java
src/test/groovy/graphql/validation/SpecValidation562Test.groovy

While looking around the code for hasInvalidLocation, I noticed that the inversion appeared to be incorrect inside of the InlineFragment use case - I believe it should be on the outside of the parentheses like the other cases, not inside on the .validLocations() check)

Move boolean inversion to correct place

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy

Adding the ability to deeply instrument data fetchers, allowing them to be wrapped
I see this as allowing an AOP way of instrumenting the system of ANY schema.
Not all data fetchers (for example PropertyFetchers etc..) are wired in by the caller and hence
this allows interception of the data fetcher to be used at execution time

Adding the ability to deeply instrument data fetchers

---

src/main/java/graphql/schema/validation/ObjectsImplementInterfaces.java
src/test/groovy/graphql/schema/validation/ObjectsImplementInterfacesTest.groovy

The current implementation of ObjectsImplementInterfaces only allows objects with field types that exactly match the field types in the interface. This causes valid schemas to be rejected.
This pull request implements support for covariant types as specified in http://facebook.github.io/graphql/#sec-Object-type-validation

Improved object type validation with support for covariant types

---

src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/validation/ValidateCustomDirectives.groovy

This doesn't add any functionality besides allowing custom directives in queries; if a server needs custom directives then he needs to write f.e. a custom ExecutionStrategy or DataFetcher that recognizes them.

Allow schemas to contain custom directives for queries.

---

src/main/java/graphql/ExecutionResultImpl.java

We avoid allocating an ArrayList when there are no errors (the common
case).
By making the errors List unmodifiable, we can also avoid the need for a
defensive copy in the getter.

Optimization: Avoid allocation in ExecutionResultImpl

---

src/main/java/graphql/schema/GraphQLFieldDefinition.java

By making arguments an unmodifiable list, we can avoid the need for a
defensive copy.

Avoid defensive copy in GraphQLFieldDefinition::getArguments

---

src/main/java/graphql/execution/ConditionalNodes.java

directivesByName is relatively expensive - it builds a Map of all
directives and then fetches the directive by name.  In the common case
when there are no directives at all, we can immediately return null.

Optimize the case when there are no directives

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/DataFetchingException.java
src/test/groovy/graphql/execution/batched/FunWithStringsSchemaFactory.java
src/test/groovy/graphql/execution/batched/GraphqlExecutionTest.groovy

new ArrayList<>(nodeData.size()); does not init a list of that size, just prepares space for it. Thus a IndexOutOfBound is thrown @ line 349.
Also right now, when an invalid number of values is provided back the whole query is aborted without a meaningful message. Instead, provide a meaningful message and just return null for affected fields, thus going in line with the behavior of unbatched fields.

Fix BatchedExectionStrategy - IndexOutOfBoundException @ line 349

---

src/main/java/graphql/execution/ValuesResolver.java

For the common case of fields with no arguments, we can early exit out
of getArgumentValues.

Optimize fields with no arguments

---

.gitignore
build.gradle
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/DataFetcherExceptionHandlerParameters.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SerialExecutionStrategy.java
src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java
src/test/groovy/graphql/NonNullHandlingTest.groovy
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/AsyncSerialExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/BreadthFirstExecutionTestStrategy.java
src/test/groovy/graphql/execution/BreadthFirstTestStrategy.java
src/test/groovy/graphql/execution/ExecutionIdTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyEquivalenceTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/SerialExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/batched/GraphqlExecutionTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TracingInstrumentationTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
src/test/groovy/readme/ReadmeExamples.java

The main change is that `ExecutionStrategy.fetchField` returns now a `CompletableFuture` instead of `Object` and new `ExecutionStrategy`s.
`SimpleExecutionStrategy` is now `SerialExecutionStrategy` and is not used anymore by default, because it is blocking.
The new default strategy is `AsyncExecutionStrategy` for queries and `AsyncSerialExecutionStrategy` for mutations. Both are non blocking but are compatible to the old behaviour if `DataFetcher` are still blocking and not async.

support async execution

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy

this changes `instrumentExecutionResult` to get an already resolved `ExecutionResult` instead of an `CF`.

change instrumentExecutionResult 

---

src/main/java/graphql/relay/Connection.java
src/main/java/graphql/relay/ConnectionCursor.java
src/main/java/graphql/relay/DefaultConnection.java
src/main/java/graphql/relay/DefaultEdge.java
src/main/java/graphql/relay/DefaultPageInfo.java
src/main/java/graphql/relay/Edge.java
src/main/java/graphql/relay/PageInfo.java
src/main/java/graphql/relay/Relay.java

See #659 and #656 
This removes the deprecated and "mutable" methods on the default implementations and also updates the documentation

Relay deprecation removal and documentation

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy

I discovered this as a limitation of the graphql-java SchemaPrinter that is preventing us from using it as part of our Relay Modern development workflow 
Based on: https://github.com/graphql/graphql-js/blob/ff4338daadb7f86e0d0700faff086dd46cbfb7b2/src/utilities/schemaPrinter.js#L160-L168

SchemaPrinter: print implemented interfaces for types

---

src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Fixes the copying of schemas and also the fact you cant set field visibility on IDL schema creation runtime wiring
See #698

Fixes the copying of schemas

---

src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java

At first, I found difficult to understand what the exception meant and where to find the problem to fix. So, I'm providing clearer description for that. Supposing the following schema:
```
type User {
...
password: String
password: String  // definition duplicated
}
```
We'll get the following exception:
Current:
`Exception in thread "main" graphql.AssertException: field password redefined`
Update:
`Exception in thread "main" graphql.AssertException: Duplicated definition for field 'password' in type 'User'`

Improving exception for duplicated field definition

---

build.gradle
docs/batching.rst
docs/index.rst
src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationTest.groovy
src/test/groovy/readme/BatchingExamples.java

See #703 
The graphql code in java-dataloader has been removed and the dependency reversed.
This adds a new Instrumentation that causes dataloader dispatching and hence the AsyncExecutionSttrategy can be made even more efficient

703 make java dataloader a dep

---

src/main/java/graphql/schema/GraphQLSchema.java

Switch to LinkedHashSet in order to have a deterministic iteration order for GraphQL directives when using introspection

Deterministic Directives iteration order

---

src/main/java/graphql/schema/validation/ObjectsImplementInterfaces.java
src/test/groovy/graphql/schema/validation/ObjectsImplementInterfacesTest.groovy

If an interface has a member which is a non-null interface, an implementation of that interface with a concrete implementation of that interface fails.
I.E.
```GraphQL
interface TestMemberInterface {
field: String
}
type TestMemberInterfaceImpl implements TestMemberInterface {
field: String
}
interface TestInterface {
field: TestMemberInterface!
}
type TestInterfaceImpl implements TestInterface {
field: TestMemberInterfaceImpl!
}
```
Will fail to validate with error
```
object type 'TestInterfaceImpl' does not implement interface 'TestInterface' because field 'field' is defined as 'TestMemberInterfaceImpl!' type and not as 'TestMemberInterface!' type
```

Fix validation of non-null Interface member

---

docs/schema.rst

This pull request removes a redundant word which I noticed in the docs when reading about Modularising the schema file.

Modify docs for Modularising the Schema IDL by removing redundant word

---

src/main/java/graphql/schema/GraphQLInterfaceType.java

Hi,
The toString() of GraphQLInterfaceType goes into StackOverflow with this example :
```
GraphQLObjectType objectType = newObject()
.name("root")
.field(newFieldDefinition()
.name("test")
.type(GraphQLInterfaceType.newInterface()
.name("test")
.typeResolver(new TypeResolver() {
@Override
public GraphQLObjectType getType(TypeResolutionEnvironment env) {
return null;
}
})
.field(newFieldDefinition()
.name("test")
.type(new GraphQLTypeReference("test"))))).build();
GraphQLSchema graphQLSchema = newSchema().query(objectType).build();
graphQLSchema.getType("test").toString();
```
It should use `fieldDefinitionsByName.keySet()` instead of `fieldDefinitionsByName`, as in GraphQLObjectType

Fixed stack overflow on toString()

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/language/AstPrinterTest.groovy

fix missing "scalar" and "input" type key word for the corresponding node; add double-quotes for
empty string value
#787

fix(AstPrinter): fix missing strings and misformat in the AstPrinter

---

src/main/java/graphql/TypeResolutionEnvironment.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/TypeResolutionParameters.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy

For a project we are working on it is useful to have the type resolvers have access to the context. As an example think of our data being a numerical ID that represents a person (interface type). That person can be an employee type or a customer type, and that needs to have access to the context to resolve which it is.

Add context to the TypeResolutionEnvironment

---

.gitignore
docs/execution.rst
src/main/java/graphql/schema/AsynchronousDataFetcher.java
src/test/groovy/graphql/schema/AsynchronousDataFetcherTest.groovy

Adds the ability to make any `DataFetcher` appropriate for running asynchronously via a helper class `AsynchronousDataFetcher`.
This class has a static method `async(DataFetcher)` that wraps the given `Data Fetcher<T>` in a new `DataFetcher<CompletableFuture<T>>`. The `CompletableFuture` returned by the new `DataFetcher` runs the original `CompletableFuture` asynchronously.
Example use (with static imports to improve readability)
```java
GraphQLFieldDefinition.newFieldDefinition()
.dataFetcher(async(fooDataFetcher))
// ... rest of field definition
```
I have also added some stuff to the `.gitignore` for files generated by Eclipse.

 Add a helper class for making asynchronous data fetchers

---

src/main/java/graphql/execution/ConditionalNodes.java
src/test/groovy/graphql/SkipAndInclude.groovy

Correct the behavior based on the spec: http://facebook.github.io/graphql/October2016/#sec--include
>  In the case that both the @skip and  @include directives are provided in on the same the field or fragment, it must be queried only if the  @skip condition is false and the @include condition is true.

Handle the case correctly when both @include and @skip exist

---

docs/getting_started.rst

Gradle didn't seem to resolve 'com.graphql-java:graphql-java:5.0.0'. I changed it to 'com.graphql-java:graphql-java:5.0' and everything seems to work fine. I am not sure if you need to make the same changes to the Maven configuration just below my changes.

fixed issue with graphql-java dependency

---

src/main/java/graphql/execution/instrumentation/tracing/TracingSupport.java

This breaks the Engine UI. Eg:

TracingSupport: no ! in parent type names

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

This allows for a simple and natural type safe way to get Java POJO properties
DataFetcher df = new PropertyDataFetcher(Thing::getId); // ok
DataFetcher<Long> df2 = new PropertyDataFetcher(Thing::getId); // ok
DataFetcher<String> df3 = new PropertyDataFetcher(Thing::getId); // wont compile
I originally added a new type of data fetcher (eg FunctionDataFetcher) but then I realised its too fine grained.  This adds just enough behavior so that you mostly only need to think about property data fetches and this is getting properties (via method references)

Ability to use Method references in PropertyDataFetchers

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/schema/CoercingParseValueException.java
src/test/groovy/graphql/Issue739.groovy

This pull request adds `sourceLocations` for coercion errors.
I'm not sure if I've added this in the appropriate place, but it seemed the easier way to add this to all types of coercion errors without forcing each individual scalar to deal with handling the source location.

Add source location for coercion errors

---

src/main/java/graphql/relay/Relay.java

The current implementation of `graphql.relay.Relay#mutationWithClientMutationId` is overly restrictive by making the `clientMutationId` non-null.
Remove the non-null constraint on `clientMutationId` in the mutation input object type and payload object type.
-----
In the [Relay Input Object Mutations Specification](https://facebook.github.io/relay/graphql/mutations.htm) we can see that the `clientMutationId` just needs to be a `String` and does not need to be non-null:
> [The] input object type may contain an argument named `clientMutationId`. If provided, that argument must be a `String`. That argument *may* be non‐null.
But in `graphql.relay.Relay#mutationWithClientMutationId` the `clientMutationId` is forced to be a non-null `String`: …

Remove non-null restriction on clientMutationId field definitions

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/Issue739.groovy

Messages now include the name of the offending variable. They no longer
include the java-specific name of the offending type. This means we will
not leak language-specific idioms in error messages.

Update coercion error messages

---

src/main/java/graphql/relay/Relay.java

A `clientMutationId` is no longer required for a Relay compliant mutation.
Provide the method `graphql.relay.Relay#mutation` that creates a Relay compliant mutation without a `clientMutationId`.
---
The need for the `clientMutationId` was removed form the [Relay Input Object Mutations Specification](https://facebook.github.io/relay/graphql/mutations.htm) with this commit facebook/relay@23a851cda10c112aa794b3480baeeb9381adf5c0. It now reads:
> All mutations **may** include in their input a `clientMutationId` string, which is then returned as part of the object returned by the mutation field.

Make a Relay mutation without a clientMutationId

---

src/main/java/graphql/relay/InvalidPageSizeException.java
src/main/java/graphql/relay/SimpleListConnection.java

`graphql.relay.SimpleListConnection` does not give an error if either the `first` or `last` argument is negative.
Throw an exception if the value of either the `first` or `last` argument is negative.
---
The [Relay Cursor Connections Specification](https://facebook.github.io/relay/graphql/connections.htm) section on the [Pagination Algorithm](https://facebook.github.io/relay/graphql/connections.htm#sec-Pagination-algorithm) says:
> If `first` is less than 0: Throw an error
and
> If `last` is less than 0: Throw an error

Error if 'first' or 'last' is negative for a Relay connection argument

---

src/main/java/graphql/relay/SimpleListConnection.java

When using `graphql.relay.SimpleListConnection`: `PageInfo/hasPerviousPage` is always `false` when using the `after` argument and `PageInfo/hasNextPage` is always `false` when using the `before` argument.
This is because the `firstPresliceCursor` and `lastPresliceCursor` are being taken **AFTER** the original `edges` have been sliced based on the `before` and `after` cursor arguments.
Take the `firstPresliceCursor` and `lastPresliceCursor` as soon the original `edges` list is computed.
--- 
The current time that the `firstPresliceCursor` and `lastPresliceCursor` are taken (after taking a sublist based on the cursors):
https://github.com/graphql-java/graphql-java/blob/2fc5fdacf3bf58967cdf515a1f379803e492cf18/src/main/java/graphql/relay/SimpleListConnection.java#L47-L65

Use correct preslice cursors in SimpleListConnection

---

src/main/java/graphql/language/NodeUtil.java

When I use operationName in blank, this code generate an exception.      
```
ExecutionInput.newExecutionInput()
.query(query.get("query").toString())
.variables((Map) query.get("variables"))
.operationName(query.getOrDefault("operationName", "").toString())
.build();
```  
`query`is HashMap.   when map has not operationName key, It is return blank.
if operationName is blank,  previous code generate an exception.
So, add the code to check the blank.
sorry .. I am not good at English. :(

Add operationName condition

---

src/main/java/graphql/language/NodeUtil.java

#845  
I was heard advice that str.isEmpty() is better then "".equals(). 
So, I modify the code  ! 
etc  
I am considering Whether or not Optional Type  is available. 
```
//  A
final Optional<String> optional = Optional.of(operationName);
Predicate<String> emptyCheck = String::isEmpty;
if(optional.filter(emptyCheck.negate()).isPresent()){
//
}
// B
if (operationName == null || operationName.isEmpty()) {
//
}
```   
But I think that A is not clean...
So, I used the code you gave me !   
Thank you for teaching me 👍

Change operationName condition (2)

---

src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy

See #844
This commit adds the root field to subscription results to conform to
the current version of the GraphQL specification.

Add root field to subscription results

---

src/main/java/graphql/Assert.java
src/main/java/graphql/execution/ExecutionPath.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/SchemaUtil.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/AssertTest.groovy

During stress testing of an app using graphql-java we encountered a hot spot that was unexpected.
Introspection.getFieldDef is invoked very frequently and the hot spot originated in this line:
`assertTrue(parentType instanceof GraphQLFieldsContainer, "should not happen : parent type must be an object or interface : " + parentType);`
The string concatenation of the error message is rarely thrown, to make things worse the 'parentType' it self was building new messages in recursively.
The Assert.assertTrue is modified to accept a format message and a varargs arguments array. The error message is only built if needed.
This is basically the same solutions logging frameworks has faced back in the days, and solve similar.
The Assert class lacked tests so these are added.
Usage of the Assert …

Assert performance improvement

---

src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy

This commit fixes alias support in GraphQL subscriptions.
See #856.

Fix alias in GraphQL subscriptions

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/Issue739.groovy

This PR improves the behavior of https://github.com/graphql-java/graphql-java/pull/818 by always including the most specific field name when throwing coercion errors.

Use most specific possible field name in coercion errors

---

src/main/java/graphql/schema/DataFetchingFieldSelectionSet.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/DataFetcherSelectionTest.groovy
src/test/groovy/graphql/schema/DataFetchingFieldSelectionSetImplTest.groovy
src/test/resources/starWarsSchemaWithArguments.graphqls

See #832 
Now you can get the field arguments and field definitions inside the selection set capture.
This allows for more efficient "parent" fetching (in some cases)

Added the ability to get arguments in selection set capture

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/test/groovy/graphql/NullVariableCoercionTest.groovy

This exposes `sourceLocations` on null coercion errors.

Correctly expose source location for null coercion errors

---

src/main/java/graphql/TypeMismatchError.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/TypeMismatchErrorTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

See issue #868. 
Overloaded the current `toIterable` method to preserve backwards compatibility, and I added a `handleTypeMismatchProblem` method that creates a `TypeMismatchError` and adds it to the execution context.
Added `TypeMismatchError` and corresponding `ExecutionStrategy` unit tests.

868 Fix ClassCastException in ExecutionStrategy.toIterable

---

src/main/antlr/Graphql.g4
src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/language/AstValueHelper.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/language/AstValueHelperTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy

It now uses proper AST values so that strings are '"string"' and ints are '123' and objects can be '{"object", "form"} and arrays are '[ "array", "form" ]
This was causing the double encoding (not the JSON encoding) but that we treated everything as strings incorrectly
see #863

863 introspection results default values

---

src/main/java/graphql/execution/TypeFromAST.java
src/main/java/graphql/validation/TraversalContext.java
src/test/groovy/graphql/validation/SpecValidation573Test.groovy

Added a null check in `getTypeFromAST`, similarly to what [graphql-js does](https://github.com/graphql/graphql-js/blob/7e147a8dd60496505cd5d491fb7126b2319095c9/src/utilities/typeFromAST.js#L49):
They return `void` (undefined in js) or the type itself.
```javascript
export function typeFromAST(schema, typeNode) {
/* eslint-enable no-redeclare */
let innerType;
if (typeNode.kind === Kind.LIST_TYPE) {
innerType = typeFromAST(schema, typeNode.type);
return innerType && GraphQLList(innerType);
}
if (typeNode.kind === Kind.NON_NULL_TYPE) {
innerType = typeFromAST(schema, typeNode.type);
return innerType && GraphQLNonNull(innerType);
}
if (typeNode.kind === Kind.NAMED_TYPE) {
return schema.getType(typeNode.name.value);
}
/* istanbul ignore next */
throw new Error(`Unexpected type kind: …
```

Fix #882, variable input type mismatch throws AssertException

---

build.gradle

Sorry for the back to back quick PRs 😄
Some of the Javadocs contain UTF8 characters and by default, on windows, it assumes Windows 1252 encoding, which fails. The fix is to explicitly call for the javadocs encoded as UTF8

Set javadoc encoding to utf8 to build on windows

---

src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java

I don't think it's a good idea to have the DataFetchingFieldSelectionSetImpl to list field names separated by a platform specific separator (considering these aren't files we're dealing with).
This fixes the build on windows machines (see test "field selection can be captured via data environment").
This is backwards incompatible change but IMO relatively minor and what looks like an oversight. If not, let me know the reasoning and feel free to close.

Platform agnostic field selection separator

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

Adds support for serializing values of:
- java.util.OptionalDouble
- java.util.OptionalInt
- java.util.OptionalLong
These types were originally created for performance reasons, but should be
included here for readability and convenience for graphql users.
Closes #899

Support for serialization of other optional types

---

src/main/java/graphql/DirectivesUtil.java
src/main/java/graphql/language/NodeUtil.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLDirectiveContainer.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

We have started with ObjectType and FieldDefinition and will extend it to other types as we go
The DSL is now officially spec and hence we can start to add the new `extend XXX` type support and directives with that

This adds runtime directives to the graphql types.  

---

build.gradle

this adds the grammar file to the jar file, so it can be consumed from other libs/programs.

add grammar file to jar

---

src/main/java/graphql/relay/Relay.java
src/test/groovy/graphql/relay/RelayTest.groovy

In order to support using Relay global IDs from the GraphQL server in URLs or filesystem paths on the client, change to unpadded url/filename-safe Base64 encoding.

Use unpadded url/filename-safe Base64 encoding for Relay global IDs.

---

src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

see #920 
This needs to be expanded in the future when we have directives on all of the other runtime types such as InputObject etc..

Added printing of GraphqlDirectives in the schema printer

---

src/main/java/graphql/schema/GraphQLEnumType.java
src/test/groovy/graphql/Issue921.groovy
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy

See #921 
Basically when the enum of backed by actual Java enums, but the input is a String, we can serialise now

Allows matching from string input to enum putput

---

docs/schema.rst

Removed note as SDL is now part of the official specification.
see : https://github.com/facebook/graphql/pull/90

Update docs on schema

---

docs/batching.rst

The Dataloader doc at http://graphql-java.readthedocs.io/en/latest/batching.html has a few typos and the example is a little hard to read.
I've corrected the errors where I've spotted them and expanded the example a little to make the reoccurrence of common fields more obvious.

Updates to Dataloader doc

---

src/main/java/graphql/execution/AbsoluteGraphQLError.java
src/test/groovy/graphql/execution/AbsoluteGraphQLErrorTest.groovy

Description
-----------
When returning a `DataFetcherResult`, the execution strategy constructs a `AbsoluteGraphQLError` that creates absolute path and source locations from the root of the GraphQL query.
When the relative error path or sourceLocation is null, it is expected that the absolute base path and source locations are null too.
When a relative error has an empty path, the expectation is for the `AbsoluteGraphQLError` to return a path up to the field that caused the error.
When a relative error has an empty source location, the same expectation should apply, that is for the `AbsoluteGraphQLError` to return the source location up to the field that caused the error. Instead `AbsoluteGraphQLError.createAbsoluteLocations` currently returns null. 
Steps to reproduce/Testing …

AbsoluteGraphQLError returns null sourceLocation when relativeError sourceLocation is empty.

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/schema/CoercingParseLiteralException.java
src/main/java/graphql/schema/CoercingParseValueException.java
src/main/java/graphql/schema/idl/SchemaPrinter.java

* Replaced `count() > 0` with `anyMatch`
* Replaced `Arrays.asList(<single_element>)` to `Collections.singletonList()`
* Replaced `Collections.toArray(T[<size>])` to `Collections.toArray(T[0])`. This is the best performing and contractually cleaner way as [explained ](https://shipilev.net/blog/2016/arrays-wisdom-ancients/)by Aleksey Shipilev

Minor performance improvements

---

src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/schema/GraphQLArgumentTest.groovy
src/test/groovy/graphql/schema/GraphQLDirectiveTest.groovy
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLEnumValueDefinitionTest.groovy
src/test/groovy/graphql/schema/GraphQLFieldDefinitionTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectFieldTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLInterfaceTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLObjectTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLScalarTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLUnionTypeTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

This allows each runtime type to be transformed into new versions of themselves.
This is a staging change so later we can allow @directives that can enhance / change the SDL type model.

Added builders to each of the graphql runtime objects

---

src/main/java/graphql/language/AstValueHelper.java
src/test/groovy/graphql/language/AstValueHelperTest.groovy

https://github.com/graphql-java/graphql-java/issues/1030
I included three fixes here:
- `\b` was not being escaped
- if escaping both `\` and `\"` in the same string, the slash before the doublequotes will be re-escaped
- not a bug, just an improvement: my understanding is that the forward slash `/` *can* be escaped in a json string, but it doesn't have to. i suggest not escaping it to generate cleaner output.
note that unicode chars `\uXXXX` are still unescaped, not sure if those should be escaped though. I'm also wondering if [`StringEscapeUtils.html.escapeEcmaScript(String)` from apache comons-lang](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#escapeEcmaScript-java.lang.String-) should be used instead.

Fix Json string escaping

---

src/main/java/graphql/execution/Async.java

-Added return call to avoid un-necessarily throwing and catching the
exception
fixes #992

Fix Async.eachSequentiallyImpl is throwing NoSuchElement Exception

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

https://github.com/graphql-java/graphql-java/issues/1029
I found that the schema printer was not printing directives for the following items:
- enum types
- enum values
- interface types
- interface fields
- union types
- input types
- input fields
- regular object types when implementing interfaces
- directives are also missing for field arguments, however that is not easily resolvable because while the schema definition uses `InputValueDefinition` to represent field args (which contains `Directive`s), the executable schema uses `GraphQLArgument` (which doesn't contain `GraphQLDirective`, neither it implements `GraphQLDirectiveContainer`)
I'm also a bit confused about how `Directive` and `DirectiveDefinition` are mapped into the executable schema, is that distinction lost or am I missing …

SchemaPrinter to print directives in all locations

---

src/main/java/graphql/validation/AbstractRule.java
src/main/java/graphql/validation/LanguageTraversal.java
src/main/java/graphql/validation/RulesVisitor.java
src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/ExecutableDefinitions.java
src/test/groovy/graphql/validation/rules/ExecutableDefinitionsTest.groovy

When a valid schema SDL definition is attempted to be executed, a validation rule
should catch that use case and display a human readable error. Instead the validation either passes and the query fails later at execution or an NPE is raised when traversing the syntax tree.
GraphQL-js correctly prevents non GraphQL queries to be executed by using the following validation rule [ExecutableDefinitions](https://github.com/graphql/graphql-js/blob/261b99b0a643561ccfb217fe8ac0c2ac16b2c5d3/src/validation/rules/ExecutableDefinitions.js ). This rule validates that the parsed Document is of either kind OperationDefinition or FragmentDefinition, so we don't attempt to mistakenly execute other kinds of definitions. 
GraphQL-java is currently missing this validation rule.
Also, if we attempt to execute …

Fix NPE and add ExecutableDefinitions Validation rule

---

docs/defer.rst
src/main/java/graphql/Directives.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/execution/defer/DeferSupportIntegrationTest.groovy

It means you don't have to add it explicitly to your schema to use it

This makes @defer support first class, instead of being an experiment

---

src/main/java/graphql/UnresolvedTypeError.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/UnresolvedTypeException.java
src/test/groovy/graphql/TypeResolverExecutionTest.groovy

**Current behavior:**
When a type resolver fails to find an appropriate concrete type for a given abstract type (interface or union), an `UnresolvedTypeException` is thrown, the execution is aborted and the exception is bubbled up as is back to the caller.
**Expected behavior:**
Instead, the corresponding GraphQL field should be set to `null` (if nullable) and the `UnresolvedTypeException` should be translated to a GraphQLError to be placed in the errors block of the GraphQL response. `graphql-js` handles this correctly [by validating the resolved type](https://github.com/graphql/graphql-js/blob/ef585e9db8d161e715dfaa4e70c1ed2efa58294c/src/execution/execute.js#L1016) and [throwing a GraphQLError](https://github.com/graphql/graphql-js/blob/ef585e9db8d161e715dfaa4e70c1ed2efa58294c/src/execut …

Fix UnresolvedTypeException not being propagated as GraphQLError

---

docs/schema.rst

Members of a union have to be Objects based types
http://facebook.github.io/graphql/October2016/#sec-Union-type-validation

fixed documentation

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/errors/NotAnInputTypeError.java
src/main/java/graphql/schema/idl/errors/NotAnOutputTypeError.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

This PR adds the source location of where a type has been used incorrectly in addition to the existing location of the referenced type definition (#429).
Both locations are useful as the cause of the error is either the wrong use of a type, or the type was declared incorrectly.

Added source location of where a type was used incorrectly in SDL

---

src/main/java/graphql/validation/rules/PossibleFragmentSpreads.java
src/test/groovy/graphql/validation/rules/PossibleFragmentSpreadsTest.groovy

This PR contains the follow changes:
- Use type names in `PossibleFragmentSpreads` message format to make it more readable (it's currently being toString'ed which outputs the typeResolver etc. as part of the message)
- Updated `PossibleFragmentSpreadsTest.groovy` with assertions that the type names appear as expected for both inline fragments and named fragment spreads

Use type names in PossibleFragmentSpreads message format

---

docs/exceptions.rst
src/main/java/graphql/execution/UnknownOperationException.java
src/main/java/graphql/language/NodeUtil.java
src/test/groovy/graphql/language/NodeUtilTest.groovy

When executing a GraphQL query, if multiple operations are defined in the query and the operation name is missing or there is no matching operation name contained in the GraphQL query, then GraphQL-java throws the general purpose `GraphQLException`. 
The problem with throwing `GraphQLException` is it's hard for the library consumer to catch for that specific use case and translate to a customer error. To do so we currently have to catch all `GraphQLException` and match on the exception message.
I added a new `UnknownOperationException` that is to be used specifically for this kind of errors, whether the operation name is missing or not matching the operation name provided in the query.
I also added it to the documentation for completeness.
I added unit tests in `NodeUtil` to cover the …

Add specific UnknownOperationException when operation name is missing

---

src/main/java/graphql/UnresolvedTypeError.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/UnresolvedTypeException.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/TypeResolverExecutionTest.groovy
src/test/groovy/graphql/execution/batched/FunWithStringsSchemaFactory.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy

#1050 is a pre-requisite to this PR. 
**Current behavior:**
After calling the user defined `TypeResolver`, `graphql-java` doesn't validate that the returned `resolvedType` is a possible type of the resolved abstract type (interface or union). If the user `TypeResolver` happens to return an aberrant type, (i.e a type that doesn't implement the given interface), `graphql-java` still attempts to complete the fetched value with that type and can lead to unexpected behavior.
**Expected behavior:**
`graphq-java` should behave like `graphql-js` which validates [the `resolvedType` and throws a `GraphQLError` if it isn't valid.](https://github.com/graphql/graphql-js/blob/ef585e9db8d161e715dfaa4e70c1ed2efa58294c/src/execution/execute.js#L1057)
I wrote a test to showcase the issue, by using an …

Add validation after type resolution to check if concrete type is a possible type of abstract type

---

src/main/java/graphql/validation/TraversalContext.java
src/test/groovy/graphql/validation/TraversalContextTest.groovy
src/test/groovy/graphql/validation/rules/VariablesAreInputTypesTest.groovy

**Current Behavior:**
If a GraphQL query contains a variable that is of type `GraphQLObjectType`, `graphql-java` throws a `ClassCastException`. 
**Expected Behavior:**
The library should catch that behavior and return a validation error using the `VariablesAreInputTypes` rule. 
I wrote an integration test to showcase the issue, (integration test below):
```java
def "when a variable is of type GraphQLObjectType then it should not throw ClassCastException and validate with errors"() {
setup:
def schema = '''
type User {
id: String
}
input UserInput {
id: String
}
type Mutation {
createUser(user: UserInput): User
}
type Query {
getUser: User
}
'''
def query = '''
mutation createUser($user: User){
createUser(user: $user) {
id
} 
}
'''
def graphQlSchema = TestUtil.schema(schema)
def document = …
```

Fix classCastException when a query variable is not a GraphQLInputType

---

src/main/java/graphql/validation/rules/KnownDirectives.java
src/test/groovy/graphql/validation/rules/KnownDirectivesTest.groovy

* Known directives validator start using node visitor, which allows to verify type at compile time
* more tests 
* legacy directive mapping `directive.isOnXXXX()` is moved to a single method
PS
Intent behind this PR is to try out new node/graph traversal :)

Tests for Known directives validation rule

---

src/main/java/graphql/language/SourceLocation.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/IDLParserTest.groovy

This PR adds sourceName as supported by Antlr TokenSource to the GraphQL SourceLocation class.
The sourceName is useful when schema errors are reported during schema validation, and the type registry was created by parsing multiple SDL documents.

Added sourceName to improve error reporting across multiple SDL documents

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/analysis/QueryReducer.java
src/main/java/graphql/analysis/QueryTraversal.java
src/main/java/graphql/analysis/QueryTraversalContext.java
src/main/java/graphql/analysis/QueryVisitor.java
src/main/java/graphql/analysis/QueryVisitorEnvironment.java
src/main/java/graphql/analysis/QueryVisitorFieldEnvironment.java
src/main/java/graphql/analysis/QueryVisitorFieldEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorFragmentSpreadEnvironment.java
src/main/java/graphql/analysis/QueryVisitorFragmentSpreadEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorInlineFragmentEnvironment.java
src/main/java/graphql/analysis/QueryVisitorInlineFragmentEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorStub.java
src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationSupport.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FragmentDefinition.java
src/main/java/graphql/language/InlineFragment.java
src/main/java/graphql/language/NodeUtil.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/Selection.java
src/main/java/graphql/language/SelectionSetContainer.java
src/test/groovy/graphql/analysis/QueryTraversalTest.groovy

This makes QueryTraversal public (it was internal before)
and improves it by having an arbitrary Node as root (not only the DocumentDefintion) and adds the `SelectionSetContainer` to the environment.

improve query traversal and make it public

---

src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeDirectivesChecker.java
src/main/java/graphql/schema/idl/errors/DirectiveIllegalArgumentTypeError.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeDirectivesCheckerTest.groovy

**Current behavior:**
This PR adds support for validating directive definitions against directive argument types.
In the example below, while the directive definition declares `arg` as being of type `[String]`, the directive improperly uses a `String`.
```
directive @myDirective(arg: [String]) on FIELD_DEFINITION
query {
f: String @myDirective(arg: "A String")
}
```
graphql-java does not currently catch this use case as the implementation was implicitly marked as TODO:
```
private boolean argValueMatchesAllowedType(TypeDefinitionRegistry typeRegistry, Value instanceValue, Type allowedArgType) {
// this code is not written yet and is tricky.
return true;
}
```
**Expected behavior:**
graphql-java should validate directive argument values matches the allowed types defined in the directive …

Add directive argument type validation

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/UniqueOperationNames.java
src/test/groovy/graphql/validation/SpecValidation51Test.groovy
src/test/groovy/graphql/validation/SpecValidationBase.groovy
src/test/groovy/graphql/validation/rules/UniqueOperationNamesTest.groovy

**Current behavior:**
When a query contains duplicate operation names, graphql-java execute one of the two operations instead of raising a validation error.
**Expected behavior:**
The graphql-js implementation complies to the [spec](http://facebook.github.io/graphql/October2016/#sec-Operation-Name-Uniqueness) by executing the [UniqueOperationNames](https://github.com/graphql/graphql-js/blob/master/src/validation/rules/UniqueOperationNames.js#L15) rule and raising a GraphQLError.
After digging through the existing tests in graphql-java I found [two tests](https://github.com/graphql-java/graphql-java/blob/master/src/test/groovy/graphql/validation/SpecValidation51Test.groovy#L37) covering this use case but they are currently disabled.
See one of them below: …

Add validation rule for unique operation names.

---

src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceData.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderPerformanceWithChainedInstrumentationTest.groovy

When using the `ChainedInstrumentation` along with the `DataLoaderInstrumentation` any GraphQL query containing lists of lists will hang indefinitely. The reason is, the chained instrumentation is not correctly passing calls back to the chained contexts, which will cause to never trigger dispatches. For reference [this is the offending line/commit](https://github.com/graphql-java/graphql-java/commit/ca6f7fa01b516b75efc292f7e673973b0d9572f3#diff-5e8eee6bb7ce89c537845070d52e704aR107) 
I reused the `DataLoaderPerformanceTest` but instead with a `ChainedInstrumentation` to reproduce the issue/hanging.
Note the use of `ChainedInstrumentation` below.
```java
void setup() {
DataLoaderRegistry dataLoaderRegistry = setupDataLoaderRegistry()
Instrumentation instrumentation = new …
```

Fix ChainInstrumentation misses to pass down calls chained contexts causes hanging

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

**Current behavior**:
[The commit that added runtime directive support](https://github.com/graphql-java/graphql-java/commit/f40354e02fe34181d7cd3cd24c09d4705fd3015a#diff-7472121f90a7b71b41a1874204845666R743) restricted the types of arguments for implicit directives to strictly only primitives. By implicit directive, I mean a directive that is used on a schema which doesn't have a corresponding directive definition. 
**Expected behavior**:
While this code path is still supported but not recommended (customers should be spec compliant and use directive definitions instead), it is breaking for us when using arrays, so I added support for array of primitive types.
I added a test to reproduce, the test below raises an `AssertException` for the array types:
```java
@Unroll
def "when using …
```

Support for list type in implicit directive argument values

---

src/main/java/graphql/GraphQLError.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java
src/main/java/graphql/language/Comment.java
src/main/java/graphql/language/Description.java
src/main/java/graphql/language/Node.java
src/main/java/graphql/language/SourceLocation.java
src/test/groovy/graphql/language/SerialisationTest.groovy

See #1071 
Today you cant place a Document into a distributed cache because of missing serialisation
This puts serialisation on the graphql language nodes and errors so they can be cached

Added serialisation support to graphql language nodes

---

src/main/java/graphql/language/NodeTraverser.java
src/main/java/graphql/language/NodeVisitor.java
src/main/java/graphql/language/NodeVisitorStub.java
src/main/java/graphql/util/TraversalControl.java
src/main/java/graphql/util/TraverserContext.java
src/test/groovy/graphql/language/NodeTraverserTest.groovy

graphql-java should provide a good way to traverse a Document/Query. This makes the NodeTraverser public and adds special pre/post Order methods for easy usage.

make NodeTraverser public and improves it with preOder/postOrder methods

---

docs/subscriptions.rst

I've stumbled on an improper quoting while reading http://graphql-java.readthedocs.io/en/latest/subscriptions.html

Fix quoting around "IBM" in the SDL sample in the Subscriptions page.

---

docs/instrumentation.rst

Discovered while reading http://graphql-java.readthedocs.io/en/latest/instrumentation.html

Fix improper quoting around Graphql in Instrumentation page

---

src/main/java/graphql/schema/idl/SchemaParser.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java

use the new SDLDefinitions Interface to make it more clear that only SDL Types are accepted.

restrict add to SDLDefinitions

---

.gitignore
build.gradle

Netbeans runs with a different CWD compared to the project causing the git command to break.
Adding -C to tell git the location of the repository to get the hash from.
Also added Netbeans gradle directory in.gitignore

Support building from a different CWD

---

src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/FieldValueInfo.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy

When using the `DataLoaderInstrumentation` and a type mismatch error happens, a NPE is thrown in the [`FieldLevelTrackingApproach.`](https://github.com/graphql-java/graphql-java/blob/ca6f7fa01b516b75efc292f7e673973b0d9572f3/src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java#L182) which will result in leaving the overall completable future result un-completed hence hanging the execution thread. 
I wrote an integration test to reproduce the issue, not the `Query.getTodos` returns a list of Todo objects `[Todo]` and our data-fetcher only returns a Todo.
This will trigger a type mismatch error that will then hang the execution.
```java
def "when actual field value return type is different from expected return type, then it should not hang execution"() { …
```

Fix NPE in FieldLevelTrackingApproach when type mismatch error

---

src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationState.java
src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java

according to https://github.com/graphql-java/graphql-java-tools/issues/58#issuecomment-407335274
for Spring-Boot usage example
```
@Bean
Instrumentation dataloaderInstrumentation() {
return new DataLoaderDispatcherInstrumentation(
()->new DataLoaderRegistry().register("characters", characterDataLoader)
);
}
```

Make DataLoaderDispatcherInstrumentation support request scope for servlet usage

---

src/main/java/graphql/language/AstValueHelper.java
src/test/groovy/graphql/language/AstValueHelperTest.groovy

See #1105 
This follows the JSON encoding from json.org more correctly

#1105 - fixed json encoding of AST string values

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/NullVariableCoercionTest.groovy

When using graphql variables for nested mandatory fields the error message in case of a missing value was not specifying the name of the field. This commit adds the field name to the message so that finding the problem is much easier.
Resolves #1183

Improves errormsg for nested fields

---

src/main/java/graphql/relay/SimpleListConnection.java
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy

If the list is empty, a NPE is triggered in the following `edges.get(0).getCursor()`.

fix: Handling empty list in SimpleListCollection

---

src/main/java/graphql/validation/TraversalContext.java
src/main/java/graphql/validation/rules/PossibleFragmentSpreads.java
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/StarWarsSchema.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy
src/test/groovy/graphql/validation/TraversalContextTest.groovy
src/test/groovy/graphql/validation/rules/Harness.java
src/test/groovy/graphql/validation/rules/PossibleFragmentSpreadsTest.groovy

When a fragment target type (or type condition) is not a composite type, `PossibleFragmentSpreads` rule validation errors with `assertShouldNeverHappen`. 
Note that the `FragmentOnCompositeType` rule already catches this use case and is the rule that emits the user validation error.
I created a test to reproduce the `AssertException` issue:
```java
def 'when fragment target type is not composite type do not error - FragmentsOnCompositeType takes care of the validation'() {
setup: "LeashInput is an input type so it shouldn't be target-able"
def query = """
query {
dogWithInput {
...LeashInputFragment
}
}
fragment LeashInputFragment on LeashInput {
id
}
"""
when:
traverse(query)
then:
errorCollector.getErrors().isEmpty()
}
```
The `PossibleFragmentSpreads` rule should not error when a …

Fix: invalid fragment target type triggers assertShouldNeverHappen

---

src/main/java/graphql/validation/TraversalContext.java
src/main/java/graphql/validation/rules/PossibleFragmentSpreads.java
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/StarWarsSchema.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy
src/test/groovy/graphql/validation/TraversalContextTest.groovy
src/test/groovy/graphql/validation/rules/Harness.java
src/test/groovy/graphql/validation/rules/PossibleFragmentSpreadsTest.groovy

Backport of #1220 
- GraphQLCompositeType is not GraphQLOutputType in 9.x, added appropriate check
- Made `StarWarsIntrospectionTests."Allows querying the schema for types"` unit test more maintainable by using Set instead of List comparison

stable fix of PR #1220

---

src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy

Test could potentially fail if Locale was different than en.

Fix test failing due to date formatting problems (#1247)

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Steps to reproduce:
Add a `@deprecated` directive to a field or a value and then run it through both `SchemaParser` and `SchemaPrinter`, it will be transformed into `@deprecated(reason : "No longer supported" = "No longer supported")` which is invalid GraphQL according to the [spec](http://facebook.github.io/graphql/June2018/#sec-Language.Directives).

Fix SchemaPrinter generating invalid values for directives

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/analysis/QueryComplexityInfo.java
src/main/java/graphql/analysis/QueryDepthInfo.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy
src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy

This PR adds:
- Logging of query complexity and depth when instrumentation classes are used.
- A kind of 'simulation' option using a `boolean abortExecution` argument.
This is useful to get insights of the query complexity and depth users are performing against our GraphQL API.
The latter one can be used if we don't actually want to abort the execution (yet), but only log a warning when the query is above the max complexity / depth.

Added query complexity and depth logging + added 'simulation' option

---

src/main/java/graphql/language/ArrayValue.java
src/main/java/graphql/language/BooleanValue.java
src/main/java/graphql/language/EnumValue.java
src/main/java/graphql/language/IntValue.java
src/main/java/graphql/language/ListType.java
src/main/java/graphql/language/NonNullType.java
src/main/java/graphql/language/StringValue.java
src/main/java/graphql/language/TypeName.java
src/main/java/graphql/language/VariableReference.java

some classes assign some fields and call parent constructor in all their own constructors instead of reuse them.

clean up second constructors to use the first ones

---

src/main/java/graphql/TrivialDataFetcher.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/relay/SimpleListConnection.java
src/main/java/graphql/schema/DataFetcher.java
src/main/java/graphql/schema/PropertyDataFetcher.java
src/main/java/graphql/schema/StaticDataFetcher.java

@bbakerman this is an alternative to #1300: What do u think?
My main motivation was to keep the info out of the DF interface itself: being the most important Interface we have I think our goal should be to keep it as simple as possible.
The trivial info is not needed in a lot of cased and will distract/confuse especially beginners who look at GraphQL Java the first time more than it helps. IMHO

moves the info if a DF is trivial out of the DF itself into a marker

---

src/main/java/graphql/schema/SchemaTransformer.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

This allows for post processing code to be specified in the RuntimeWiring so that the build schema can be automatically transformed into something else.
I intend it to be used for the "validation post processing" so that we can run the entire schema and find validation directives and generate code that goes into the CodeRegistry.

Added SchemaTransformers as a post processing step in the schema build

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Add a flag, `includeDirectives`, on by default. If the flag is off (`includeDirectives(false)`), directives won't be printed even if they exist.

#1370 make printing directives optional

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy

While looking at some pretty printed schemas from graphql-js I noticed the graphql-java schemas were not as pretty.
Now they will look more like:
```
type Query {
field(
#about arg1
arg1: String, 
arg2: String, 
"""
about 3
second line
"""
arg3: String
): String
}
```
Would like to even add newlines between args to pad them out but this is a good first step.

Indent args and use multiline comments when printing schema

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/language/OperationTypeDefinition.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java

This is a breaking change:
`OperationTypeDefinition.type` is changed to `OperationTypeDefinition.typeName`.
The type is changed from `Type` to `TypeName.`
I don't know why it was ever the way it was, but a `OperationTypeDefinition` doesn't have a type reference, but clearly just has a type name. (the grammar has it correct)

the type of an OperationTypeDefinition is actually a typeName

---

CONTRIBUTING.md
build.gradle

There were some security issues in jackson(-databind) recently, including:
* https://www.cvedetails.com/cve/CVE-2017-7525/
* https://www.cvedetails.com/cve/CVE-2018-1000873/
Therefore I wanted to update this dependency.
While I was here, also updated the Junit version and fixed some typos.
Afaik all tests still pass (although I'm not too familiar with Gradle...)
Please let me know if you have any feedback.

Update jackson-databind version (security risk!), junit version (and fix typos)

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/UniqueDirectiveNamesPerLocation.java
src/test/groovy/graphql/validation/SpecValidationSchema.java
src/test/groovy/graphql/validation/rules/UniqueDirectiveNamesPerLocationTest.groovy

Directive uniqueness is not enforced today.  This fixes that according to the graphql spec
SDL code already has directive uniqueness - just not query code

Unique query directives

---

src/main/java/graphql/GraphqlErrorBuilder.java
src/main/java/graphql/execution/DataFetcherResult.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/nextgen/ValueFetcher.java
src/test/groovy/graphql/DataFetcherWithErrorsAndDataTest.groovy
src/test/groovy/graphql/GraphqlErrorBuilderTest.groovy
src/test/groovy/graphql/execution/DataFetcherResultTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

General Purpose Error Builder and opt in to the AbsoluteGraphqlError handling
You use this in a data fetcher via 
GraphqlErrorBuilder.newError(dfe).message("Bad %s", "JuJu").build()

General Purpose Error Builder

---

src/main/java/graphql/Assert.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/nextgen/BatchedExecutionStrategy.java
src/main/java/graphql/execution/nextgen/DefaultExecutionStrategy.java
src/main/java/graphql/execution/nextgen/ExecutionStrategyUtil.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalysis.java
src/main/java/graphql/execution/nextgen/result/ExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/LeafExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ListExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ObjectExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ResultNodeAdapter.java
src/main/java/graphql/execution/nextgen/result/ResultNodeTraverser.java
src/main/java/graphql/execution/nextgen/result/ResultNodesUtil.java
src/main/java/graphql/execution/nextgen/result/RootExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/UnresolvedObjectResultNode.java
src/test/groovy/graphql/execution/nextgen/result/ResultNodesUtilTest.groovy

by using the resultKey from mergedField as key, therefore we just have a list of children for a ERN and
not list AND maps

simplify ExecutionResultNodes

---

src/main/java/graphql/language/NodeParentTree.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphqlElementParentTree.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiring.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironment.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironmentImpl.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorDirectiveHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/groovy/readme/DirectivesExamples.java

This makes the schema directive wiring occur after the type has been built and hence the callback gets full access to the type hierarchy

SchemaDirectiveWiring is now done after the full set of graphql elements are built

---

build.gradle

[This bug ](https://github.com/antlr/antlr4/pull/2309) appears in our service and has since been fixed in ANTRL 4.7.2. This PR is to update `graphql-java` use of ANTLR to from 4.7.1 to 4.7.2. 
As it is a patch version of ANTLR, no breaking changes have been identified from `graphql-java`.
I will create another pull request for the stable branch.

Update antlr4 from 4.7.1 to 4.7.2

---

src/main/java/graphql/relay/Relay.java
src/test/groovy/graphql/RelaySchema.java

Make the PageInfo type public static and use a type reference so that when the schema is traversed, it won't generate a new one.
This means that the PageInfo type should be added by the dev consumer to the schema manually.
This will solve #1441

Make the PageInfo type public static and use a type reference

---

src/main/java/graphql/ErrorClassification.java
src/main/java/graphql/ErrorType.java
src/main/java/graphql/ErrorTypeClassification.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/GraphqlErrorBuilder.java
src/main/java/graphql/execution/AbsoluteGraphQLError.java

This changes the closed enum that is ErrorType and creates  a new ErrorTypeClassification
(possible rename is ErrorTypeClassification -> ErrorClassification)
This means that any one can create a GraphqlError class and use their own "classification" object.
For example if one wanted to have "statusCode" as an attribute, then you could create
class StatCodeClassification implements ErrorTypeClassification {
int getStatusCode() 
}
which in json terms will be
{
"msg" : "some text",
"path" : [ "foo", "bar" ],
"errorType" : {
"statusCode" : 403
}
}

Made the ErrorType implement a base interface

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy

(cherry picked from commit 84f4bc73805b94912a7cb046556817102945561f)

Fix NPE in AstPrinter for inline fragments without type condition

---

src/main/java/graphql/validation/rules/FragmentsOnCompositeType.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/Issue1440.groovy
src/test/groovy/graphql/validation/rules/FragmentsOnCompositeTypeTest.groovy

Fix #1440 ClassCastException when using a fragment with wrong input type condition and overlapping fields are being merged.

---

src/main/java/graphql/validation/rules/FragmentsOnCompositeType.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/Issue1440.groovy
src/test/groovy/graphql/validation/rules/FragmentsOnCompositeTypeTest.groovy

In cases where a fragment type condition is invalid (say it was an input type instead of a composite type), the `FragmentsOnCompositeType` rule rightfully collects the validation error. However, the `OverlappingFieldsCanBeMerged` validation rule is wrongly assuming that the type condition is valid and attempts to cast it as a `GraphQLOutputType`, throwing a `ClassCastException` described in issue #1440.
I wrote a test to reproduce the issue:
```java
def schema = TestUtil.schema("""
type Query {
nothing: String
}
type Mutation {
updateUDI(input: UDIInput!): UDIOutput
}
type UDIOutput {
device: String
version: String
}
input UDIInput {
device: String 
version: String
}
""")
def graphQL = GraphQL.newGraphQL(schema).build()
def "#1440 when fragment type condition is input type it should …
```

Fix #1440 ClassCastException - fragment with wrong input type condition

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/ExecutionInputTest.groovy
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy

Make CacheControl explicitly accessible from DataFetchingEnvironment, similar to how DataLoaderRegistry currently works

Ability to provide CacheControl instance via ExecutionInput

---

src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/test/groovy/readme/MappingExamples.java
src/test/groovy/readme/ReadmeExamples.java

This fixes up the example code so it used CodeRegistry and also quick rename of parameter names there

This fixes up the example code so it used CodeRegistry

---

src/main/java/graphql/schema/idl/SchemaParser.java
src/main/java/graphql/schema/idl/errors/NonSDLDefinitionError.java
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

See  #1447
The justification is that a SchemaParser should parse for schemas.  Not other things.  The general parser can of course parse for all.

Fixes so that non SDL definitions are rejected by the SchemaParser

---

src/main/java/graphql/schema/Coercing.java

This is a JavaDoc only fix.  The code actually does allow null values on coercing.serialize()
The JavaDoc was misleading (along with our understanding)
See #1362

Fixes up JavaDoc on what is allowed to come back from scalars serialize

---

src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalysis.java
src/main/java/graphql/execution/nextgen/result/ExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ResultNodeAdapter.java
src/test/groovy/graphql/execution/nextgen/result/ExecutionResultNodeTest.groovy
src/test/groovy/graphql/execution/nextgen/result/ExecutionResultNodeTestUtils.groovy
src/test/groovy/graphql/execution/nextgen/result/ResultNodeAdapterTest.groovy

I also added toStrings on ERN because those guys are complex and it makes it  asmidge easier in the debugger

result node adaptor now can delete children

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/preparsed/NoOpPreparsedDocumentProvider.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java
src/main/java/graphql/nextgen/GraphQL.java
src/test/groovy/graphql/execution/preparsed/NoOpPreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/TestingPreparsedDocumentProvider.groovy

This will improve the ability for people to do better "query caching" because it now sends the operation name (and all ExecutionInput properties) in to the call back.
This is a breaking change to the SPI.
There is a way to do it where we delegate from the new to the old via a `default` interface method.  But I dont think enough people will be affected by this change to, nor the scope of change is big enough to warrant those gymnastics

Changed the PreParsedDocumentProvider so it has the full input and not just query string

---

src/main/java/graphql/execution/MergedField.java

A MergedField is just a collection of Field without a real identity behind the list of field it contains. So two MergedField should be considered equal when the lists a equal.

add equals/hashcode to merged field

---

src/main/java/graphql/language/Document.java
src/main/java/graphql/language/SelectionSet.java
src/main/java/graphql/parser/ExtendedBailStrategy.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/MultiSourceReader.java
src/main/java/graphql/parser/SourceLocationHelper.java
src/test/groovy/graphql/DataFetcherWithErrorsAndDataTest.groovy
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/IssueNonNullDefaultAttribute.groovy
src/test/groovy/graphql/parser/LineNumberingTest.groovy
src/test/groovy/graphql/parser/ParserExceptionTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/validation/rules/ExecutableDefinitionsTest.groovy
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy
src/test/groovy/graphql/validation/rules/UniqueDirectiveNamesPerLocationTest.groovy
src/test/groovy/graphql/validation/rules/UniqueOperationNamesTest.groovy

see #1512 
The previous multi source line reader work was a bit hasty in how it calculated line numbers.
Antler is 1s based while the multi source reader is zeroes based - so we got out by one
And then the tests got updated to reflect it - even though it was wrong in practice
This corrects that

The line numbers of elements are no longer off by one

---

src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy
src/test/resources/diff/schema_ABaseLine.graphqls
src/test/resources/diff/schema_changed_field_arguments.graphqls
src/test/resources/diff/schema_changed_input_object_fields.graphqls
src/test/resources/diff/schema_changed_nested_input_object_fields.graphqls
src/test/resources/diff/schema_changed_object_fields.graphqls
src/test/resources/diff/schema_changed_type_kind.graphqls
src/test/resources/diff/schema_dangerous_changes.graphqls
src/test/resources/diff/schema_interface_fields_missing.graphqls
src/test/resources/diff/schema_missing_enum_value.graphqls
src/test/resources/diff/schema_missing_field_arguments.graphqls
src/test/resources/diff/schema_missing_input_object_fields.graphqls
src/test/resources/diff/schema_missing_object_fields.graphqls
src/test/resources/diff/schema_missing_operation.graphqls
src/test/resources/diff/schema_missing_union_members.graphqls

Fixes #1503 .
Looks like there was a missing call to recurse down to nested input types.
The changes are mostly test file changes -- the contents are copied and pasted for every file with only minor changes 😬

Fix schemadiff input recursion

---

src/main/java/graphql/execution/ExecutionContext.java
src/test/java/benchmark/AddError.java

before:
AddError.benchMarkAddError    ss    5  1.079 ± 0.064   s/op
after:
AddError.benchMarkAddError    ss    5  0.131 ± 0.059   s/op

fixes #1524

---

src/main/java/graphql/util/DefaultTraverserContext.java
src/main/java/graphql/util/FpKit.java
src/main/java/graphql/util/NodeMultiZipper.java
src/main/java/graphql/util/NodeZipper.java
src/main/java/graphql/util/TraverserContext.java
src/main/java/graphql/util/TreeTransformerUtil.java
src/test/groovy/graphql/analysis/QueryTransformerTest.groovy
src/test/groovy/graphql/language/AstTransformerTest.groovy

Enhance zipper to specify a modification type to allow for delete and insert changes.
Breaking change because it removes the  `TreeTransformerUtil.changeParent` method which was the wrong approach.

add modificationType for NodeZipper to handle delete and insert

---

src/main/java/graphql/util/NodeMultiZipper.java
src/main/java/graphql/util/NodeZipper.java
src/test/groovy/graphql/language/AstTransformerTest.groovy

This handle the case of deleting the root node of a tree, which results in `null`.

handle deleting root node

---

src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy

Currently GraphQLCodeRegistry allows registering DataFetchers using either FieldCoordinates or by explicitly providing parent and target field (which is then used to construct field coordinates) but it only allows retrieving DataFetcher for a given field based on the parent container field. This is problematic when attempting to configure directives while recursively generating the schemas (i.e. how it is done in graphql-kotlin) as the parent object is not yet available.
It appears that parent GraphQLFieldsContainer is only used to construct target field coordinates for retrieving the data fetcher. It would be great if we could retrieve the data fetchers by the coordinates as well as it is blocking us (graphql-kotlin) from upgrading to latest version of graphql-java.

Retrieve DataFetcher from CodeRegistry using FieldCoordinates

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryTransformer.java
src/main/java/graphql/language/NodeTraverser.java
src/main/java/graphql/util/DefaultTraverserContext.java
src/main/java/graphql/util/Traverser.java
src/main/java/graphql/util/TraverserContext.java
src/test/groovy/graphql/analysis/QueryTraversalTest.groovy
src/test/groovy/graphql/language/NodeTraverserTest.groovy
src/test/groovy/graphql/util/TraverserTest.groovy

This removes the Leave/Enter context variable from NodeTraverser and makes it a general property on `TraverserContext`.

add phase to general traverser context

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/analysis/QueryReducer.java
src/main/java/graphql/analysis/QueryTraversalContext.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/analysis/QueryVisitor.java
src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationSupport.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy
src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy

This is a breaking change.
It is renamed to be consistent with other classes in GraphQL Java and also because `Traverser` is the better more accurate name.

rename QueryTraversal to QueryTraverser

---

src/main/java/graphql/language/DirectivesContainer.java
src/main/java/graphql/language/EnumTypeDefinition.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/FragmentDefinition.java
src/main/java/graphql/language/FragmentSpread.java
src/main/java/graphql/language/InlineFragment.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/InputValueDefinition.java
src/main/java/graphql/language/InterfaceTypeDefinition.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/ScalarTypeDefinition.java
src/main/java/graphql/language/UnionTypeDefinition.java

Reverts the InlineFragment change and makes all the existing DirectivesContainers implement NamedNode directly
This is a breaking change for any one who took a DirectivesContainer and called getName on it

Made DirectivesContainer NOT implement NamedNode 

---

src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiring.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironment.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironmentImpl.java
src/main/java/graphql/schema/idl/SchemaGeneratorDirectiveHelper.java
src/main/java/graphql/schema/idl/WiringFactory.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/groovy/readme/DirectivesExamples.java

This changes directive wiring so that all directives are available  during callbacks.
Its also changes the behavior of registration so that "named directive" wirings are called as before but the WiringFactory directive wiring is ALSO called last.  Before it was either one or the other but not both.
This is a behaviour breaking change (not a compilation one)
I also added some helper methods since "data fetcher" tweaking is the most common actions and hence you can now write code like
```
public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> environment) {
String targetAuthRole = (String) environment.getDirective().getArgument("role").getValue();
//
// build a data fetcher that first checks authorisation roles before then calling the original data …
```

This changes directive wiring so that all directives are available 

---

src/main/java/graphql/ErrorClassification.java
src/main/java/graphql/GraphqlErrorHelper.java
src/test/groovy/graphql/ExecutionResultImplTest.groovy
src/test/groovy/graphql/GraphQLErrorTest.groovy
src/test/groovy/graphql/GraphqlErrorHelperTest.groovy

This now adds support in graphql-java for errors to put a `classification : objValue` into the `extensions` map of a graphql error.
This will be useful for downstream errors such that you can might have something like this as an error
```
{
message : "Unable to make downstream call",
extensions : {
classification : {
failureSystem : "http",
statusCode : 403
}
}
```
GraphqlErrors are still able to have their own "extensions".  This is just for the ErrorClassification aspect so that a standard error comes out with some sort of classification in the extensions

Adds toSpecification support to ErrorClassification

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/Issue1559.groovy

Issue [#1559 ](https://github.com/graphql-java/graphql-java/issues/1559) outlines a lack of control over list items in fetcher result for a list field, in particular, the inability to set a localContext for each item of a list. This pull request modifies list result handling in `ExecutionStrategy` class allowing an instance of `DataFetcherResult` as an item of a list. After the improvement, individual list items `DataFetcherResult` are handled the same way as a regular field's value of `DataFetcherResult` type: errors are added to query result, localContext for child nodes of the item is set.

Allow and process DataFetcherResult as an item for GraphQL List fields.

---

src/main/java/graphql/execution/nextgen/BatchedExecutionStrategy.java
src/main/java/graphql/execution/nextgen/DefaultExecutionStrategy.java
src/main/java/graphql/execution/nextgen/ExecutionStrategyUtil.java
src/main/java/graphql/execution/nextgen/ResultNodesCreator.java
src/main/java/graphql/execution/nextgen/result/ExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/LeafExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ListExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ObjectExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/ResolvedValue.java
src/main/java/graphql/execution/nextgen/result/ResultNodesUtil.java
src/main/java/graphql/execution/nextgen/result/RootExecutionResultNode.java
src/main/java/graphql/execution/nextgen/result/UnresolvedObjectResultNode.java
src/main/java/graphql/language/AbstractNode.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/Node.java
src/test/groovy/graphql/execution/nextgen/result/ExecutionResultNodeTest.groovy
src/test/groovy/graphql/execution/nextgen/result/ExecutionResultNodeTestUtils.groovy
src/test/groovy/graphql/execution/nextgen/result/ResultNodeAdapterTest.groovy
src/test/groovy/graphql/execution/nextgen/result/ResultNodesUtilTest.groovy

Main change: simplifying ResultNodes by putting ESI directly into the result node and introducing
a new ResolvedValue which contains only the needed information
also: making AbstractNode and Field more mutable by coping input
collections

simplifying ResultNodes 

---

src/main/antlr/GraphqlCommon.g4
src/test/groovy/graphql/parser/IDLParserTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy

This allows all unicode characters and also fixes the comment rule: comments should also be `SourceCharacter` according to spec

allow full range of unicode characters

---

src/main/java/graphql/schema/idl/ScalarInfo.java
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

Discussed in [spectrum chat](https://spectrum.chat/graphql-java/general/why-is-byte-not-included-in-the-standard-scalar-definitions~415c8b35-9ed4-4bb5-828c-b3c9eeca505a)
Adding `Byte` since it was missing from [ScalarInfo#STANDARD_SCALAR_DEFINITIONS](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/ScalarInfo.java#L54-L65)

Add 'Byte' to standard scalar definitions

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryVisitorFieldArgumentInputValue.java
src/main/java/graphql/analysis/QueryVisitorFieldArgumentInputValueImpl.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputValue.java
src/main/java/graphql/schema/GraphQLInputValueDefinition.java
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy

Naming comes from the counter part InputValueDefinition
Also named in line with GraphqlFieldDefinition (with counterpart FieldDefinition)
Consistency would called for GraphqlArgumentDefinition and GraphqlInputObjectFieldDefinition - but thats a bridge too far

Invented a new interface type - GraphqlInputValueDefinition

---

src/main/java/graphql/schema/Coercing.java

Noticed this one mention in doc was out of sync with the actual exception type. Other two methods in this interface look correct. 📝

Correct exception class name in documentation

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java
src/main/java/graphql/execution/nextgen/ValueFetcher.java
src/main/java/graphql/nextgen/GraphQL.java
src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java
src/main/java/graphql/util/LogKit.java
src/test/groovy/graphql/util/LogKitTest.groovy

See #1585 
Now will log query data and things that might not be privacy safe as
```
[main] WARN graphql.GraphQL_NotPrivacySafe - Query failed to validate : '
fragment StoryDetail on Story {
id
text @defer
}
```

#1585 logging now has not privacy safe suffix

---

src/main/java/graphql/validation/ValidationUtil.java
src/test/groovy/graphql/IssueNonNullDefaultAttribute.groovy
src/test/groovy/graphql/validation/ValidationUtilTest.groovy

Update query validation to take default value for input object fields into account.
This should not break existing functionality but instead allow additional requests to pass validation. It should improve compliance with https://github.com/facebook/graphql/pull/418
Addresses: https://github.com/graphql-java/graphql-java/issues/1588

Non-null input object fields with default values should be valid

---

src/test/groovy/graphql/LocalContextAwareCascadingTest.groovy

This shows the test scenario where we are passing the local context to the grandchildren of nodes correctly. I will check up with the original issue reporter if this is the scenario that they are describing.

refs #1635: Create a test for making sure that local context can be consumed by grandchildren

---

src/main/java/graphql/GraphqlErrorBuilder.java
src/test/groovy/graphql/GraphqlErrorBuilderTest.groovy

We found a bug where GraphErrorBuilder.newError().message("A %s style string").build() would blow up wanting format args

If a message has a String.format() specifier in it and no formats are provided - BOOM

---

src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy

One of the most annoying things about DataFetchers is defaulting arguments
This adds this
```
String argVal =  dfEnv.getOrDefault("someArg", "someDefault");
```

get or default support in DFE

---

src/main/java/graphql/execution/ExecutionContext.java

Allow type inference for the context, similar `DataFetchingEnvironment#getContext`

Allow type inference for the context

---

src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This is a one step towards Apollo Federation support.
#1644
It now does two major things
* It captures the original AST type definitions including `extends` definitions
* SchemaPrinter now has a mode where you can print out the original AST definitions
Given the following SL
```
type Query {
foo: String
}
extend type Query {
bar: String
}
extend type Query {
baz: String
}
```
The original (and default mode) SchemaPrinter will print the combined runtime view eg
```
type Query {
foo: String
bar: String
baz: String
}
```
Now with the capture of the original AST type definitions we get it as it was in the SDL including `extends` declarations.
@pcarrier - does this make sense to help Apollo Federation?

This will capture `extend type` AST and put them into the runtime types

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Bugfix:
Description of Directive arguments were not captured when you create a GraphQLSchema from SDL.

bugfix: description for arg directives are captured correctly from SDL

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/relay/DefaultConnectionCursor.java
src/test/groovy/graphql/ScalarsIDTest.groovy

This is in response to Tomkes issue about ID scalars
That is if you return an object that generates specific ids (via its toString) then today you cant use them.
This allows String.valueOf() on any object

id scalar will now use String.valueOf on serialise

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Further ability to filter what directives get printed. My use-case is hiding individual internal directives (while exposing the rest) from SDL processing tools, like Apollo Federation. It potentially helps with #1017 as well. Relates to #1587 too.
Not sure if this is ready to merge, opened it more as a discussion point.

Fine grained directive filtering in printing

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

This PR changes the way a missed property is handled for performance reasons.
Previously if a field `foo` is defined in a schema but the underlying object did not have a `getFoo()` method / field then a null would be correctly returned however all the java reflection would be repeated on the next call and so on.
This means that for misconfigured SDL  -> runtime code you pay a high performance penalty.
This PR fixes it so that we negatively cache missing reflection look ups and hence are more performany in certain cases (where a field is defined by not possible to retrieve)
This is much like we do for positive caching (where we keep the method/field in memory for next time)
The drawbacks of this approach is that in contrived cases, you can change the underlying class and it wont be …

Negative cache of Property fetch misses

---

src/main/java/graphql/language/AstValueHelper.java
src/test/groovy/graphql/language/AstValueHelperTest.groovy

I've made a PR to address this [issue](https://github.com/graphql-java/graphql-java/issues/1712)
Actually the code for `jsonStringify()` can be refactored into using a Map<>. But I think we should NOT complicate this PR with such refactor

AstValueHelper: fixed jsonStringify() to NOT escape forward slashes

---

src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationState.java
src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationTest.groovy

See #1667 
If a Instrumentation enhances the `ExecutionInput` and hence the `DataLoaderRegistry` instance, we can now use the right instance during dispatching

Enhanced execution input (and hence data loader registry) is now captured before use

---

src/main/java/graphql/SerializationError.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/schema/CoercingParseLiteralException.java
src/main/java/graphql/schema/CoercingParseValueException.java
src/main/java/graphql/schema/CoercingSerializeException.java
src/main/java/graphql/validation/AbstractRule.java
src/main/java/graphql/validation/ArgumentValidationUtil.java
src/main/java/graphql/validation/ValidationError.java
src/main/java/graphql/validation/ValidationUtil.java
src/main/java/graphql/validation/rules/ArgumentsOfCorrectType.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/Issue739.groovy
src/test/groovy/graphql/schema/CoercingTest.groovy
src/test/groovy/graphql/validation/rules/ArgumentsOfCorrectTypeTest.groovy

This goes some way to addressing #1686 
This means that the coercing exception from a scalar implementation is carried into the error messages.
Previously this was not the case at all and custom information would be lost

Allows the messages from a scalar to be sent back to the user

---

src/main/antlr/Graphql.g4
src/main/antlr/GraphqlSDL.g4
src/main/java/graphql/language/SchemaExtensionDefinition.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/idl/SchemaExtensionsChecker.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeDirectivesChecker.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/errors/OperationRedefinitionError.java
src/main/java/graphql/schema/idl/errors/SchemaRedefinitionError.java
src/test/groovy/graphql/schema/idl/SchemaExtensionsCheckerTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

This adds support for schema extensions into graphql-java
```
extend schema {
mutation : SomeNewType
}
```
This also captures the schema extension definition objects and puts them into the runtime schema
This will allow Apollo to do their funky extension trick when stitching together schemas

Schema extension support

---

src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

bugfix: comments on nodes should not considered  when comparing arguments of interface vs implementation.
This fixes #1701

bugfix: comments on interface arguments cause wrong error for schema validation

---

src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorPostProcessing.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

We introduced recently the general `SchemaTransformer` class, therefore we rename this SDL specific post processor.

rename SDL schema transformer into SchemaGeneratorPostProcessing

---

src/main/java/graphql/schema/diff/DiffCategory.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy
src/test/resources/diff/schema_deprecated_fields_new.graphqls
src/test/resources/diff/schema_deprecated_fields_removed.graphqls

Addresses #1504
Let me know your thoughts on this. My strategy was to just add another category, which can provide the extra information and keep the `Danger` and `Breaking` levels untouched.
The two new combinations of level and category are:
1. level: `DANGER`, category: `DEPRECATED` for fields that become deprecated
1. level: `BREAKING`, category: `DEPRECATED` for fields that were deprecated and now missing
Todo:
Remarks:
It's actually interesting to note that `@deprecated` on anything but `FIELD_DEFINITION | ENUM_VALUE` is not currently a valid spec-compliant use of the directive.
See: https://graphql.github.io/graphql-spec/June2018/#sec--deprecated
and the corresponding implementation proposed on graphql-js: https://github.com/graphql/graphql-js/pull/1560/files

Get more information about @deprecated fields from SchemaDiff

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

So far `PropertyDataFetcher` only looks for private getter at the current class, not the super classes. This PR adds this functionality.

search private getter up the class hierarchy

---

src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/errors/InterfaceFieldArgumentNotOptionalError.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

This ensures that `MissingInterfaceFieldArgumentsError` is only thrown if the object type has less arguments than the interface type.
It also adds a new check to see if every additional argument in the object type is optional.
Ref: The [spec](https://graphql.github.io/graphql-spec/June2018/#sec-Objects) says:
```
The object field may include additional arguments not defined in the interface field, but any additional argument must not be required, e.g. must not be of a non‐nullable type.
```
Fixes #1595

Correctly support additional optional arguments in fields defined by interfaces

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This PR re-implements the printer() function to prevent an exception (ConcurrentModificationException) from happening due to a possible new, extended GraphQL type class used in schemaPrinter. The issue was happening due to the Map#computeIfAbsent() function and adding keys while still being modified. This issue can be found at https://github.com/graphql-java/graphql-java/issues/1709 .

Bugfix: multiple GraphQL sub types printing #1709

---

src/main/java/graphql/validation/ValidationUtil.java
src/test/groovy/graphql/IssueNonNullDefaultAttribute.groovy

Backport of #1589: Non-null input object fields with default values should be valid

backport of #1589 to 9.x: Non-null input object fields with default values should be valid

---

src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/errors/InterfaceFieldArgumentNotOptionalError.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

Correctly support additional optional arguments fields defined by interfaces

backport of #1694: additional optional arguments fields defined by interfaces

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Bugfix SchemaPrinter: Print directive argument only when it has a value

backport of #1637 to 9.x: Print directive argument only when it has a value

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalyzer.java
src/main/java/graphql/language/AstValueHelper.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/validation/ValidationUtil.java
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy

The Coercion for Scalars resembles the Coercion of Enum values, but GraphQLEnumType should not use the same `Coercing` interface and there is actually no need for it at all. The methods are just pulled up into the class in this PR
`Coercing` is actually an SPI and should only be used for  Scalars. 
Technical breaking change, but no normal user should be affected.

GraphQLEnumType does not not use the Coercing interface anymore

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeDirectivesChecker.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy
src/test/groovy/graphql/schema/transform/FieldVisibilitySchemaTransformationTest.groovy

We have an old flag to allow SDLs not to declare directives. This was done before SDL was part of the official spec.
This PR removes this features as it is not spec conform.

remove the option to have undeclared directives in your SDL

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/ScalarInfo.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/UnExecutableSchemaGenerator.java
src/test/groovy/graphql/schema/SchemaPrinterComparatorsTest.groovy
src/test/groovy/graphql/schema/idl/MockedWiringFactory.groovy
src/test/groovy/graphql/schema/idl/RuntimeWiringTest.groovy
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

* Removed flag for SchemaPrinting to include Extended Schema types
* Removed types from ScalarInfo so java types are treated as a custom scalar

Removing java types as standard scalars

---

src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

- Validate schemas created by sdl and programmatically don't contain built in scalars and show custom scalars that aren't referenced.

Adding tests to prove scalars are omitted if not used

---

src/main/java/graphql/schema/PropertyDataFetcherHelper.java

Fixes https://github.com/graphql-java/graphql-java/issues/1784.

Make PropertyDataFetcherHelpder#mkKey rely on Class#getName instead of Class#getCanonicalName

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/language/NullValue.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/test/groovy/graphql/language/NodeVisitorStubTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/validation/ValidationUtilTest.groovy
src/test/groovy/graphql/validation/rules/ArgumentsOfCorrectTypeTest.groovy

NullValue represent a certain Ast element, therefore it should not be used as a singleton.

Removing the single instance of NullValue 

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/language/AbstractDescribedNode.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/language/DescribedNode.java
src/main/java/graphql/language/DirectiveDefinition.java
src/main/java/graphql/language/EnumTypeDefinition.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/InputValueDefinition.java
src/main/java/graphql/language/InterfaceTypeDefinition.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/ScalarTypeDefinition.java
src/main/java/graphql/language/UnionTypeDefinition.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/language/AstPrinterTest.groovy

Changed comments to descriptions according the issue https://github.com/graphql-java/graphql-java/issues/1759 . The previous standard uses `#` to include comments and this PR includes descriptions wrapped around quotations.

Use descriptions instead of comments for AstPrinter and IntrospectionResultToSchema

---

src/main/java/graphql/schema/idl/CombinedWiringFactory.java
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

This provides the backport of #1797 to the 9.x branch.

backport #1797: add missing WiringFactory methods

---

src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/util/EscapeUtil.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/util/EscapeUtilTest.groovy

Not too sure on pulling in `commons-text` just to do this, but couldn't find a comprehensive solution without reinventing the wheel. Thoughts?
Need this for auto deploying schema to Apollo. Alternatively I could add an option to force multi line comments as a temporary fix, but that still leaves this functionality in a broken state.

Escape single line comments

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy

There are no visitors for Variable Definitions, so trying to visit
its value to extract data in order to create an environment object
will throw an NPE.
fix #1865

1865: Do not visit a variable definition value node

---

src/main/java/graphql/execution/ExecutionPath.java
src/test/groovy/graphql/execution/ExecutionPathTest.groovy

Technically breaking change because it is public API.

refactor ExecutionPath to improve performance and simplify it

---

src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java

This makes it easier to construct a `ChainedInstrumentation`.
Before:
```
Instrumentation instrumentation = new ChainedInstrumentation(
Arrays.asList(new TracingInstrumentation(), dlInstrumentation)
);
```
After:
```
Instrumentation instrumentation = new ChainedInstrumentation(
new TracingInstrumentation(), dlInstrumentation
);
```

Add an additional constructor for convenience

---

src/main/java/graphql/schema/idl/CombinedWiringFactory.java
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

The `WiringFactory` interface gained a couple of methods over time, but its implementor `CombinedWiringFactory` was not expanded accordingly to call those methods on its delegates. This appears to be an oversight which can lead to surprising behavior.

add missing WiringFactory methods to CombinedWiringFactory

---

src/main/java/graphql/schema/GraphQLInputObjectField.java
src/test/groovy/graphql/Issue1847.groovy

The source of the problem here is the circular reference created by the `toString` implementations in `GraphQLInputObjectField` and `GraphQLInputObjectType`. 
The stack overflow error will happen every time there's a circular reference between field/type and `toString` is called in one class or the other. This PR tries to fix that.
Fixes #1847

1847: Fix circular reference between input object field/type

---

src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy

For those who construct a CodeRegistry / type system by hand (eg not from SDL) then they have no way to provide the default data fetcher which is always the PropertyDataFetcher.
This opens that up
See https://spectrum.chat/graphql-java/general/question-about-the-default-data-fetcher~e023aded-ed95-4c34-aa47-02fc6cfc44ec

CodeRegistry can now have a default data fetcher factory

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Apollo Federation requires that we return the schema as part of the _Service field to help the gateway understand all the fields. See 'Fetch Service Capabilities' https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#fetch-service-capabilities. 
This schema should not contain the directive definitions but should contain all the directives on the types and fields. This PR adds a new option to the `SchemaPrinter`, `includeDirectiveDefinitions`, which is on by default. Setting it to false will remove the definitions from the top of the schema

Add new schema printer option includeDirectiveDefinitions

---

src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java
src/test/groovy/graphql/execution/pubsub/CapturingSubscriber.java
src/test/groovy/graphql/execution/reactive/CompletionStageMappingPublisherTest.groovy

This fixes the Subscription publisher so that it does not drop values… that have been received but not yet mapped by the graphql layer (#1801)

Stable backport of 1801

---

src/main/java/graphql/schema/FieldCoordinates.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/test/groovy/graphql/schema/FieldCoordinatesTest.groovy

* #1845: Implemented optimized FieldCoordinates creation methods
Description:
Implemented versions of FieldCoordinates creation methods that
do not perform validation in order to optimize performance.  This is
to allow for cases that need to create field coordinates that are
already known to be valid and need to optimize for performance.
Changes:
* Added optmized FieldCoordinates.coordinates method
* Added optmized FieldCoordinates.systemCoordinates method
Unit Tests:
* Added FieldCoordinates.groovy file to test all cases for
FieldCoordinates creation
* #1845: Updated field coordinates implementation based on feedback
Description:
Updated optimized field coordinates implementation based on feedback
from @bbakerman.  New implementation moves validation checks to the
GraphQLCodeRegistry. …

#1845: Implemented optimized FieldCoordinates creation methods (#1846)

---

src/main/java/graphql/schema/GraphQLInputObjectField.java
src/test/groovy/graphql/Issue1847.groovy

* 1847: Fix circular reference between input object field/type
Fixes #1847
* 1847: Add circular reference back on test
Co-authored-by: Felipe Reis <freis@atlassian.com>

1847: Fix circular reference between input object field/type (#1864)

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/nextgen/ValueFetcher.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/main/java/graphql/schema/PropertyDataFetcherHelper.java
src/main/java/graphql/util/FpKit.java
src/main/java/graphql/util/MemoizedSupplier.java
src/test/groovy/graphql/util/FpKitTest.groovy
src/test/java/benchmark/BenchMark.java

Why do work when many (most) data fetchers such as PropertyDataFetcher never used the arguments not all of the execution step info.
Like the DataSelectionSetimpl - this is a lazy pattern

Lazy data fetcher values support for arguments and execution step info

---

src/main/java/graphql/schema/validation/TypesImplementInterfaces.java
src/test/groovy/graphql/InterfacesImplementingInterfacesTest.groovy
src/test/groovy/graphql/schema/validation/TypesImplementInterfacesTest.groovy

I've missed one scenario on the my previous PR (#1920).
Since now we're no longer relying on argument positions to do the validation, it doesn't make sense to compare argument count anymore.

1897: Fix argument implementation in SchemaValidator

---

src/main/antlr/GraphqlSDL.g4
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/language/SchemaDefinition.java
src/main/java/graphql/language/SchemaExtensionDefinition.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy

The spec allows description to be placed on a the schema itself inside the SDL and to be queried.
This adds support for it.

add description to schema itself

---

src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java

I added `ExecutionStrategyParameters` parameter to `AbstractAsyncExecutionStrategy.handleResults` method. This would allow custom `handleResults` implementations to resolve information about currently mapped Type.
For backward compatibility, I kept the existing method with 3 parameters. I was thinking about marking it as `@Deprecated` but wasn't sure about it.
@andimarek what do you think about this change?
PS this PR addresses the problem in #1855

#1855 add ExecutionStrategyParameters parameter to handleResults method

---

src/main/java/graphql/language/InterfaceTypeDefinition.java

Simple PR to include `implementz` in the constructor of `InterfaceTypeDefinition.Builder(InterfaceTypeDefinition)`
More details described in the [issue](https://github.com/graphql-java/graphql-java/issues/1974)

ISSUE-1974: Included implementz in constructor

---

src/main/java/graphql/execution/UnknownOperationException.java

Useful if we are catching `GraphQLErrors` from execution and putting them as errors in the GraphQL response. With this change in place we don't have to have custom handling.

Make UnknownOperationException implement GraphQLError

---

src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/UnionTypesChecker.java
src/main/java/graphql/schema/idl/errors/UnionTypeError.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

union type check, details in https://spec.graphql.org/June2018/#sec-Type-System. 
especially in https://spec.graphql.org/June2018/#sec-Unions
Invalid name begin with "__" (two underscores);
Union type must include one or more member types;
The member types of a Union type must all be Object base types;
The member types of a Union type must be unique.

add union type checker

---

src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/util/EscapeUtil.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/util/EscapeUtilTest.groovy

Backport of fix #1832.
I couldn't do a copy carbon cherry pick of the original commit because of some whitespace changes that created merge conflicts. I had to modify it a little bit but this backport commit should be clean.

Backport of fix #1832: Escape single line comments

---

src/main/java/graphql/schema/PropertyDataFetcherHelper.java

…f Class#getCanonicalName
(cherry picked from commit a2dbaef973c7aaf51974306d76f2110bfc6bfba8)

Backport of fix #1785: Make PropertyDataFetcherHelpder#mkKey rely on Class#getName instead of Class#getCanonicalName

---

src/main/java/graphql/execution/ExecutionContext.java

We have been experiencing poor performance with our graphql-java application under heavy load during scale testing.  During these tests, several other backends have also struggled which results in timeout or circuit breaker exceptions being thrown and mapped to GraphQL errors added to the response.  We started profiling with Java Flight Recorder and reviewing the results in Mission Control.  One finding is that there is significant blocking on the ExecutionContext.addErrors() method, which is backed by a CopyOnWriteArrayList.  Researching CopyOnWriteArrayList vs. other options, CopyOnWriteArrayList blocks on write operations and is expensive because it has to create a new copy of the array on every write.  It is ideal for situations with limited concurrent writes and many concurrent …

Change ExecutionContext.errors from CopyOnWriteArrayList to Collections.synchronizedList(new ArrayList<>())

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionDataFetcher.java
src/main/java/graphql/introspection/IntrospectionDataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironment.java

This extracts a special `IntrospectionDataFetcher` which is only used inside in `Introspection`.
This is allows custom execution engines to reuse the Introspection code more easily.

extract special Introspection DF

---

src/main/java/graphql/schema/PropertyDataFetcherHelper.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy
src/test/java/benchmark/PropertyFetcherBenchMark.java

I found a bug on the VERY important PropertyDataFetcher where methods on derived classes are not cached properly.  
This leads to things running slower than they are intended.
We also invoke too much code when we DO have a cached method and this simplifies that, doing way less work on POJO method invocation
I created a benchmark for this - on my Mac Pro - 
```
Baseline:
Bencnchmark                                                            Mode  Cnt        Score       Error  Units
PropertyFetcherBenchMark.benchMarkThroughputDirectClassHierarchy    thrpt   15  1085518.250 ± 19039.649  ops/s
PropertyFetcherBenchMark.benchMarkThroughputInDirectClassHierarchy  thrpt   15    48904.567 ±  2916.355  ops/s
After Inprovements
Benchmark …
```

Faster Property fetching with derived classes 

---

src/main/java/graphql/ExceptionWhileDataFetching.java
src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java
src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java
src/main/java/graphql/execution/instrumentation/tracing/TracingSupport.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/FragmentSpread.java
src/main/java/graphql/language/ObjectValue.java

Helps to reduce garbage collector pressure and memory usage in general by avoiding some re-allocations of j.u.ArrayList and j.u.LinkedHashMap.
Following discussion in https://spectrum.chat/graphql-java/general/does-there-exist-a-more-efficient-implemantion-of-asyncexecutionstrategy~93dad126-8b9f-45fc-aaec-9dc04ddae4bc looks like most of our results are between 1 and 6 fields. By default LinkedHashMap is allocating 16 elements. With this change I would like to cut some memory waste and reallocations.

pre-sizing internal data structures

---

src/main/java/graphql/execution/Async.java

Looking at Flight Recorder allocation I noticed that Asyc.each is a hot spot method and hence this pre-allocates the result array and iterate the array we have

Small tweak in a hot spot method that pre-allocates the array list

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldCompleteParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldFetchParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldParameters.java

This adds lazy ExecutionStepInfo for instrumentation calls )where they MAY not ever use it) and also reduces the number of calls create them and variable resolving.
I ran this code under JProfiler and `graphql.execution.ExecutionStrategy#createExecutionStepInfo` showed up as a hotspot.  Looking into it I see it being called a lot but for low value.  I suspect some coy and paste happened here.
Anyway this is only marginally better performance
```
Baseline:
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  38.663 ± 1.852  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime      avgt   15  25.562 ± 1.043  ms/op
After: …
```

ExecutionStepInfo optimisations

---

src/main/java/graphql/validation/rules/KnownDirectives.java
src/test/groovy/graphql/validation/rules/KnownDirectivesTest.groovy

The test below will fail:
```
def sdl = '''
directive @subDirective on SUBSCRIPTION
type Query {
field: String
}
'''
def schema = TestUtil.schema(sdl)
def "valid  directive on SUBSCRIPTION"() {
def spec = '''
subscription sub @subDirective{
field 
}
'''
when:
def document = TestUtil.parseQuery(spec)
def validator = new Validator();
def validationErrors = validator.validateDocument(schema, document);
then:
validationErrors.size() == 0
}
```
Error message:
```
Condition not satisfied:
validationErrors.size() == 0
|                |      |
|                1      false
[ValidationError{validationErrorType=MisplacedDirective, queryPath=null, message=Validation error of type MisplacedDirective: Directive subDirective not allowed here, locations=[SourceLocation{line=2, column=30}], …
```

Bug fix and improvements to KnownDirectives

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/scalar/CoercingUtil.java
src/main/java/graphql/scalar/GraphqlBigDecimalCoercing.java
src/main/java/graphql/scalar/GraphqlBigIntegerCoercing.java
src/main/java/graphql/scalar/GraphqlBooleanCoercing.java
src/main/java/graphql/scalar/GraphqlByteCoercing.java
src/main/java/graphql/scalar/GraphqlCharCoercing.java
src/main/java/graphql/scalar/GraphqlFloatCoercing.java
src/main/java/graphql/scalar/GraphqlIDCoercing.java
src/main/java/graphql/scalar/GraphqlIntCoercing.java
src/main/java/graphql/scalar/GraphqlLongCoercing.java
src/main/java/graphql/scalar/GraphqlShortCoercing.java
src/main/java/graphql/scalar/GraphqlStringCoercing.java

This breaks down the monolithic Scalar class into a series of specific classes for each coercing.
This will make it easier to maintain and understand

The Scalar code is now broken down into their own implementations

---

src/main/java/graphql/language/Argument.java
src/main/java/graphql/language/Directive.java
src/main/java/graphql/language/DirectiveDefinition.java
src/main/java/graphql/language/DirectiveLocation.java
src/main/java/graphql/language/EnumTypeDefinition.java
src/main/java/graphql/language/EnumValue.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/FragmentDefinition.java
src/main/java/graphql/language/FragmentSpread.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/InputValueDefinition.java
src/main/java/graphql/language/InterfaceTypeDefinition.java
src/main/java/graphql/language/NodeUtil.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/OperationTypeDefinition.java
src/main/java/graphql/language/ScalarTypeDefinition.java
src/main/java/graphql/language/TypeName.java
src/main/java/graphql/language/UnionTypeDefinition.java
src/main/java/graphql/language/VariableDefinition.java
src/main/java/graphql/language/VariableReference.java

The reason for this change is for making the code more readable. #2029

replace isEqualTo with Objects.equals

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/DataFetcherExceptionHandlerTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy

Meta!!
If an exception handler throws an exception then that exception will be handled and turned into a graphql error via the default SimpleExceptionHandler that is used out of the box and does not throw exceptions
This is especially important for DataLoaders that MUST have the promises they return be completed otherwise they can hang
See #1973

This will handle exceptions if the exception handler itself throws exceptions

---

src/main/java/graphql/GraphQL.java

Make code more readable and avoid create duplicate class.
In most case, people will use `ExecutionStrategy` provided by graphql-java.

providing default ExecutionStrategy in GraphQL

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java

- presizing of few internal data structures
- removing unused method in ExecutionStrategy (public api, technically a breaking change)
- removing unused methods in Async (internal api)
- removing few unnecessary annotations

minor cleanups

---

src/main/java/graphql/DirectiveInfo.java
src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/schema/idl/DirectiveInfo.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

Changes about this PR:
1. **main purpose: create directive definition when map introspectionResult to schema**;
2. add `DirectiveInfo` to hold the directive info provided by graphql specification;
3. add some test about create scalars, create directives, create directives with arguments and default value, create schema with directives;
4. add description information of `ScalarTypeDefinition ` and `SchemaDefinition ` when map introspectionResult to schema;
5. add description information of `DirectiveDefinition` and `SchemaDefinition ` in `AstPrinter`;

Create directive definition when map introspectionResult to schema

---

src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/language/EnumTypeExtensionDefinition.java
src/main/java/graphql/language/InputObjectTypeExtensionDefinition.java
src/main/java/graphql/language/InterfaceTypeExtensionDefinition.java
src/main/java/graphql/language/ObjectTypeExtensionDefinition.java
src/main/java/graphql/language/ScalarTypeExtensionDefinition.java
src/main/java/graphql/language/UnionTypeExtensionDefinition.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/language/AstTransformerTest.groovy

When using the `AstTransformer`, and working on extensions, I noticed in some cases when changing a child node on an extension, the resulting node would wrongly be converted to its base type. 
Here is an **example**, given: 
```graphql
extend type MyType {
login: String
}
```
and changing the field `login` to say `signin` using the `AstTransformer` will have the effect of changing `MyType` extension object type to an object type. 
Resulting document would be:
```graphql
type MyType {
signin: String
}
```
This bug happens because the `AstTransformer` uses the `withNewChildren()` method on each definition to reattach the children and this method being missing in extensions would defer to using `withNewChildren()` on the base definition returning a new instance of the base instead of the …

Fix AstTransformer extension being converted to base type when changing child node

---

src/main/java/graphql/schema/idl/SchemaTypeDirectivesChecker.java
src/main/java/graphql/schema/idl/TypeUtil.java
src/main/java/graphql/schema/idl/errors/DirectiveIllegalReferenceError.java
src/main/java/graphql/schema/idl/errors/IllegalNameError.java
src/main/java/graphql/schema/idl/errors/MissingTypeError.java
src/test/groovy/graphql/schema/idl/SchemaTypeDirectivesCheckerTest.groovy

[Details in spec](https://spec.graphql.org/draft/#sec-Type-System.Directives.Validation):
1. A directive definition must not contain the use of a directive which references itself indirectly;
2. The directive must not have a name which begins with the characters "__" (two underscores).
3. For each argument of the directive:
- The argument must not have a name which begins with the characters "__" (two underscores);
-  _The type of argument must exist;_
- The argument must accept a type where IsInputType(argumentType) returns true.
others:

 Add directive validation rules defined in spec

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

Hi @bbakerman @andimarek,
please find my first attempt to be a bit more lazy during list processing in `completeValueForList`.
The basic idea is to avoid to "materialize" a `Stream` (and later maybe `Iterator`) into an `ArrayList`. 
I don't like some details of this PR (notably passing -1 as `listSize`) but let's start the discussion anyway. Maybe someone have better ideas there.

Support for Streams and Iterators

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/execution/preparsed/NoOpPreparsedDocumentProvider.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentEntry.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java
src/main/java/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupport.java
src/main/java/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCache.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQueryCache.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQueryCacheMiss.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQueryNotFound.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java
src/test/groovy/graphql/ExecutionInputTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/TestingPreparsedDocumentProvider.groovy
src/test/groovy/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupportTest.groovy
src/test/groovy/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCacheTest.groovy

This adds the basis for persisted query support in graphql-java.
In short consumers need to have their own cache implementation to be truly useful.  The `InMemoryPersistedQueryCache` one is too bare bones for production use at scale, as its not memory constrained.
`ApolloPersistedQuerySupport` has been provided which can read persistent query ids from the input extensions.
See #1972

Persisted query support in graphql-java

---

src/main/java/graphql/schema/validation/TypesImplementInterfaces.java
src/test/groovy/graphql/schema/validation/TypesImplementInterfacesTest.groovy

This is a fix for #2072.
It adds another check for the case where both types are of `GraphQLInterfaceType` and then checks if the implementing type actually has the correct interface, similar to how `objectImplementsInterface` works. It also includes a test for the case mentioned in the issue.

Fix TypesImplementInterfaces.check() for interfaces implementing interface #2072 

---

build.gradle

I am not sure if there is a reason that antlr4-runtime and antlt4 is on different versions ? In case this is ok to make them the same, here is a PR for that.
We get 
> ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8
in SmallRye (and Quarkus). I am not sure if this is related.
Thanks :)

Update antlr to 4.8

---

src/main/java/graphql/execution/FieldCollectorParameters.java
src/main/java/graphql/execution/MergedField.java

ExecutionContext uses immutable maps for variables and fragments, that could be shared freely.
And, since this is an internal class, we could change a bit the contract and avoid some allocations of LinkedHashMap:
.fragments(executionContext.getFragmentsByName())
.variables(executionContext.getVariables())

avoiding allocations in FieldCollectorParameters and MergedField

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/rules/ProvidedNonNullArguments.java
src/test/groovy/graphql/validation/rules/ProvidedNonNullArgumentsTest.groovy

[required Arguments rule](https://spec.graphql.org/draft/#sel-HALTHHFTCAACCnCjmR)
>Providing the explicit value null is also not valid since required arguments always have a non‐null type.
[demo](https://spec.graphql.org/draft/#example-0bc81):
```sql
fragment missingRequiredArg on Arguments {
nonNullBooleanArgField(nonNullBooleanArg: null)
}
```

New validation rule: providing the explicit value 'null' to non-null argument is invalid

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/Issue1914.groovy
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

Adds support for honoring the default values declared in input type definition ([Issue](https://github.com/graphql-java/graphql-java/issues/1914))
Schema:
```
type Query {
sayHello(arg: Arg! = {}): String
}
input Arg {
foo: String = "Bar"
}
```
Query:
```
query {
sayHello
}
```
arg value before change:
`{}`
arg value after change:
`{foo: "Bar"}`
Schema:
```
type Query {
sayHello(arg: Arg! = {field1: "F1ValOverride"}): String
}
input Arg {
field1: String = "F1V"
field2: String = "F2V"
}
```
Query:
```
query {
sayHello
}
```
arg value before change:
`{field1: "F1ValOverride"}`
arg value after change:
`{field1: "F1ValOverride", field2: "F2V"}`

#1914 Use default values for fields of input types when default argument value is provided

---

src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java

I thins that the override of default method in SimpleInstrumentation is redundant.

Remove the override of default method in SimpleInstrumentation

---

src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java

I think `withTracingExt` is more reasonable and semantically correct,
tracingMap can indicate the result of `tracingSupport.snapshotTracingData()`.

Minor fix: replace `tracingMap` with `withTracingExt`

---

src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/ConditionalNodes.java
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy

The bug was that variables are not coerced and hence the conditional nodes can fail especially with defaulting
See #2084

Variables are now coerced in the QueryTraverser

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/ValueUnboxer.java
src/test/groovy/graphql/GraphQLTest.groovy

This allows consumers to put ina  default data fetching exception handler more easily and after 2 years as deprecated we have removed the direct constructors on the `GraphQL` object

Makes a default data fetcher exception handler possible

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Fix for [coerceVariableValues](https://github.com/graphql-java/graphql-java/blob/0de364ae0fdc75126b0217ba6ad61253ec4007c0/src/main/java/graphql/execution/ValuesResolver.java#L54) to ensure that:
1. use null when variable defined in variableValuesMap is null;
2. if variableType is a Non‐Nullable type and value is null, throw a query error.
Linkage to [algorithm defined in spec](https://spec.graphql.org/draft/#sec-Coercing-Variable-Values)

Fix for coerceVariableValues

---

src/main/java/graphql/Directives.java
src/main/java/graphql/util/Anonymizer.java
src/test/groovy/graphql/util/AnonymizerTest.groovy

New class which takes a schema and queries matching that schema and returns an anonymous version of both. 
All type names, field names, fragment names etc are replaced with generic names like `Fragment1` or `Object10`

Add anonymizer 

---

src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/language/Directive.java
src/main/java/graphql/language/NodeUtil.java

Alternative fix for #2119 
Master:
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  42.681 ± 1.912  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime      avgt   15  23.026 ± 0.621  ms/op
```
This branch:
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  46.075 ± 2.372  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime      avgt   15  21.021 ± 0.602  ms/op
```

avoiding allocations in ConditionalNodes

---

build.gradle

This PR restores support for OSGi using the bndtool gradle plugin

Use bndtool plugin to generate OSGi manifest headers

---

src/main/java/graphql/normalized/FieldCollectorNormalizedQuery.java
src/test/groovy/graphql/normalized/NormalizedQueryTreeFactoryTest.groovy

caching leads to wrong normalized trees inn some cases. Caching removed

Bugfix: caching of visited fragments in Normalized tree

---

src/main/java/graphql/schema/CodeRegistryVisitor.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

This PR removes hardcoding the `PropertyDataFetcher` if no data fetcher is specified inside a `GraphQLFieldDefinition`. Instead, the default data fetcher defined in the `GraphQLCodeRegistry` is used now if a `GraphQLFieldDefinition` does not specify a custom data fetcher.
fixes #2145

use default df from GraphQLCodeRegistry

---

CONTRIBUTING.md
coding-guidelines.md
src/test/java/benchmark/AstPrinterBenchmark.java
src/test/java/benchmark/BenchMark.java
src/test/java/benchmark/PropertyFetcherBenchMark.java

- Improving the readability by applying minor adjustments to some of the top level project guideline documents
- JMH codebase looks like it's migrated from Mercurial to GitHub, so updating all references that have been pointing to the Mercurial repository.

Grammar tweaks in documentation, and update to use github for JMH samples

---

src/main/java/graphql/schema/validation/InvalidSchemaException.java
src/main/java/graphql/schema/validation/TypeAndFieldRule.java
src/test/groovy/graphql/schema/validation/TypeAndFieldRuleTest.groovy

This PR fixes two instances of ClassCastException in `TypeAndFieldRule` when the following conditions are met:
- union member types are not object types
- union member types are repeated.
It was quite hard to add a unit test since it looks like these two rules are already present in the [UnionTypesChecker](https://github.com/graphql-java/graphql-java/blob/7a8e9038df64ddba27a8aa4040ecdeb60fe387e5/src/main/java/graphql/schema/idl/UnionTypesChecker.java#L69).
Should we remove these two altogether?

Fix ClassCastException in TypeAndFieldRule

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/EnumValues.groovy

If you create a schema with SchemaGenerator with an EnumValuesProvider, you
would expect that your DataFetchers can call getArgument and get enum values as
returned by the EnumValuesProvider. This works fine when the value is explicitly
provided in the operation. But for default values, DataFetchers will just
receive a String with the name of the value!  This PR improves SchemaGenerator
to resolve enum values in default values (included nested in input objects,
lists, and non-null) using EnumValuesProvider.

Enum default values should use EnumValuesProvider

---

src/main/java/graphql/introspection/Introspection.java

Without this, schema introspection on directives will fail if any directive is defined as valid on `SUBSCRIPTION`.

Add subscription to __DirectiveLocation enum

---

src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationState.java

Hello!
The original implementation is throwing an exception only when the `register` method was invoked but in my reality, I'm using `computeIfAbsent` method to register a new data loader (kind of lazy initialization). Without such changes, if no data loader registry was provided it will not throw any exception and hangs on waiting for the data from the data loader, which in the first place is not very intuitive behavior. I think it's better to throw an exception for all three methods `register`, `computeIfAbsent` and `unregister`, not only one `register`.

Throw an exception when try to register or unregister data loader when no DataLoaderRegistry provided

---

src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java

Since SimpleInstrumentation is often used as base class, it would be
possible to skip some allocations in case the method is not overridden.

fix #2131: less allocations in SimpleInstrumentation

---

src/main/java/graphql/GraphqlErrorHelper.java
src/main/java/graphql/analysis/FieldComplexityEnvironment.java
src/main/java/graphql/analysis/QueryVisitorFieldEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorFragmentDefinitionEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorFragmentSpreadEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorInlineFragmentEnvironmentImpl.java
src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/language/IgnoredChar.java
src/main/java/graphql/language/NonNullType.java
src/main/java/graphql/language/SourceLocation.java
src/main/java/graphql/relay/DefaultConnectionCursor.java
src/main/java/graphql/schema/FieldCoordinates.java
src/main/java/graphql/schema/GraphqlTypeComparatorEnvironment.java
src/main/java/graphql/schema/PropertyFetchingImpl.java
src/main/java/graphql/schema/idl/TypeInfo.java
src/main/java/graphql/schema/validation/SchemaValidationError.java
src/main/java/graphql/util/Breadcrumb.java
src/main/java/graphql/util/NodeLocation.java

According to yourkit FieldCoordinates is allocating too many Object[]
and looks like to root-cause is the usage of `Objects.hash()`.
This patch is trying to standardize use of `Objects.hashCode()`
without allocating arrays.
@andimarek  @bbakerman  this is really micro optimization but please have a look anyway

avoiding array allocations in hashCode()

---

src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java
src/main/java/graphql/execution/instrumentation/SimpleInstrumentationContext.java

Previous fix was incomplete (33cd6e60df47bb1f6d407d3ff32804a05b335ae0): SimpleInstrumentationContext.noOp() should avoid allocations too.

fix #2131: single instance for noOp()

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This PR addresses issue #2158 where the schema directive would not be printed. Logic similar to the other places where directives are printed was added for schemas.

Add logic to print directives on schemas.

---

src/main/java/graphql/schema/GraphQLFieldsContainer.java
src/test/groovy/graphql/schema/GraphQLObjectTypeTest.groovy

It has annoyed me for the longest time that `objectType.getField("foo")` did not exist but `inputObject.getField("foo")` does.
getField() is the perfect name.  Short and to the point.
This adds that

Aded getField to FieldsContainers

---

src/main/java/graphql/schema/AsyncDataFetcher.java

In some case, Instrumentation#instrumentDataFetcher need to know the information about the wrapped DF and Executor. such as whether DF is trivial, and which Executor the DF use.

Add getter for AsyncDataFetcher

---

src/main/java/graphql/Directives.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionQuery.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/Issue2141.groovy
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/GraphQLArgumentTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectFieldTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

See #1770 
See also https://github.com/smitt04/graphql/blob/ac15638ac02ac88013d838785d907c24bbaeff6b/spec/Section%204%20--%20Introspection.md
This now allows @deprecated to be on input fields and arguments.
```
type Query {
someField(someArg : Int @deprecated) : String
}
input InputType {
someInputField : String @deprecated
}    
```

This provides @deprecated on input fields and arguments

---

src/main/java/graphql/execution/instrumentation/threadpools/ExecutorInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/threadpools/ExecutorInstrumentationTest.groovy

This will allow ANY data fetcher to be automatically executed on a a fetch thread pool and then control passed back to a processing thread pool

Support for thread switching in a cross cutting way

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

This PR adds feature requested in issue https://github.com/graphql-java/graphql-java/issues/927 -
a way to collect the path/name of the field that failed to be deserialized.

Add path to errors thrown during coercion

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionWithDirectivesSupport.java
src/main/java/graphql/schema/FieldCoordinates.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy
src/test/java/graphql/introspection/IntrospectionWithDirectivesSupportTest.groovy

Previously the Introspection data fetchers were placed into the code registry ALWAYS and replaced any from before
Now we do a replace if absent and hence allow people to replace the default Introspection data fetchers.
(They will of course want to keep the fetching contract in place otherwise they will shoot themselves in the foot)

This allows system data fetchers to be replaced

---

build.gradle

Fixes #2251
This also removes the Guava imports, because it is relocated inside the bundle.

Build: Export all graphql packages in OSGi bundle.

---

build.gradle
src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

This refactors the input object value coercion to align with the rest of the code.
As a side effect it fixes a bug where a `null` value in the object was overwritten with a default value.

Bugfix input object default value when value is null coercion 

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy

inside of `visitValue` method we check whether a parent of a node is a var reference
```java
if (context.getParentNode() instanceof VariableDefinition) {
return TraversalControl.CONTINUE;
}
```
But if a grandparent of a node is a var reference we won't exit the method. The method fails with NPE

fix npe in query traverser when default variable value is a list

---

src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/collect/ImmutableKit.java
src/main/java/graphql/execution/DataFetcherExceptionHandler.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/collect/ImmutableKitTest.groovy
src/test/groovy/graphql/execution/DataFetcherExceptionHandlerTest.groovy

This makes the data fetching exception handlers async.
The old method is left in place for backwards compatibiility reasons but the new async version is the one called.
It will delegate back to the old sync method.
New implementations can use proper async processing in making fetching errros

Adding support for making the exception handlers async

---

src/main/java/graphql/language/IgnoredChar.java
src/main/java/graphql/language/IgnoredChars.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/InvalidSyntaxException.java
src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/ParserTest.groovy

See #2207
This will save memory by default.  graphql-java will not capture ignored characters by default.
A static is provided to allow a JVM wide default (set to false) or new parse methods will allow it to be explicitly set
on the parse method call

Do not capture Ignored characters by default

---

src/main/java/graphql/util/Anonymizer.java
src/test/groovy/graphql/util/AnonymizerTest.groovy

This PR revises anonymizer's handling of default values. Specifically it adds support for correctly anonymizing default values of type enum, object, and list in both schema and queries.
This PR also fixes a bug where the anonymizer would produces a schema that fails GraphQL spec schema validation because fields on implementing types would have different anonymized default values as the default values on the fields of the implemented interface. 
Example:
```
type Human implements Character {
id: String
friends(limit: Int = 100): [Character]
}
interface Character {
id: String
friends(limit: Int = 100): [Character]
}
```
would anonymize to:
```
type Object1 implements Interface1{
field1: String
field2(arg1: Int = 1): [Interface1]
}
interface Interface1 {
field1: String
field2(arg1: Int = 2): …
```

Anonymizer default values fixes

---

src/main/antlr/GraphqlSDL.g4
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/test/groovy/graphql/Issue2274.groovy
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy
src/test/groovy/graphql/parser/SDLParserTest.groovy
src/test/groovy/graphql/schema/GraphqlTypeComparatorsTest.groovy
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy

Fixes issue #2274.
The current spec for `implementsInterfaces` expects `&` between type names, where there are at least 2 type names. This pull request fixes the parser and tests with the current spec.
Before the June 2018 spec release, interface names were delimited with a space or comma (effectively the same thing, as commas are ignored). Implementation of an old spec then caused the parsing issue raised in #2267 & #2274.
Spec link: https://spec.graphql.org/draft/#sec-Objects

Fix extend type parsing issue

---

src/main/java/graphql/schema/DataFetchingFieldSelectionSet.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/test/groovy/graphql/schema/DataFetchingFieldSelectionSetImplTest.groovy

The ExecutableNormalisedField backed selection set work made an assumption about how we have 2 ways to do glob matching, eg by name (`age`) or full field name (`Person.age`)
However this got reflected back in the API when you get the actual fields back on `getFields` calls.
This fixes it in that it provides set semantics on the returned list.  It still matches multiples ways but it considers the list of fields to be the ones that map to the same ExecutableNF.
See https://github.com/graphql-java/graphql-java/issues/2303
https://github.com/graphql-java/graphql-java/issues/2275

Fix for duplicate selected fields in the selection set

---

src/main/java/graphql/scalar/GraphqlBooleanCoercing.java
src/test/groovy/graphql/ScalarsBooleanTest.groovy

When a AST literal is coerced it must be `true` or `false` - easy because the parser enforces that
However if you use variables then
`{"someBoolVar" : "TEST"}`
will be accepted and evaluated to false.
The old code uses Boolean.parse in Java which I have argued IS idiomatic Java however it creates strangle edge cases
We could be more strict in what we accept as a boolean.
This is that PR
If we decide to go with this PR then it would break anyone how is currently sending in strings outside "true" and "false" (case insensitive) .
See 
https://github.com/graphql-java/graphql-java/issues/1103
https://github.com/graphql-java/graphql-java/issues/865

Strict boolean support for Strings in and out

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/GraphQLContext.java
src/main/java/graphql/cachecontrol/CacheControl.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ResolveType.java
src/main/java/graphql/execution/TypeResolutionParameters.java
src/main/java/graphql/execution/instrumentation/nextgen/InstrumentationExecutionParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionParameters.java
src/main/java/graphql/execution/nextgen/ExecutionHelper.java
src/main/java/graphql/nextgen/GraphQL.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java
src/test/groovy/example/http/HttpMain.java
src/test/groovy/graphql/ExecutionInputTest.groovy
src/test/groovy/graphql/GraphQLContextTest.groovy
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/NullValueSupportTest.groovy
src/test/groovy/graphql/cachecontrol/CacheControlTest.groovy
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy
src/test/groovy/graphql/schema/DelegatingDataFetchingEnvironmentTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/groovy/readme/ConcernsExamples.java
src/test/groovy/readme/DirectivesExamples.java

The original graphql-java code copied the graphql-js pattern of having a opaque context object
Since everything in JS is untyped and mutable this works because one can just "wack" another property into the context
However we have learnt over time that since the context is sa shared place (for both frameworks and user code to use) we need to have a more formal mechanism that just a `Object getContext()` pattern.
So we have made the `GraphqlContext getGraphqlContext()` the preferred context mechanism and deprecated the older `Object getContext` methods.
At some point the legacy `getContext` will disappear but since this is a WIDELY used mechanism that will not be any time soon.

Adding GraphQlContext in preference to the legacy context

---

src/main/java/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupport.java
src/main/java/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCache.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQueryError.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQueryIdInvalid.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java
src/test/groovy/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupportTest.groovy
src/test/groovy/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCacheTest.groovy

Hello! 👋 
This PR would address two of the proposed ideas in this issue: https://github.com/graphql-java/graphql-java/issues/2395.
There are two proposals here. 
The first adds a new Persisted Query Error: PersistedQueryIdInvalid. This error is thrown if invocation of the method `persistedQueryIdIsInvalid` returns true. To go along with this, I also added an implementation of this protected method to `ApolloPersistedQuerySupport`. That implementations check the provided query ID is equal to the sha256 checksum of the queryText to be validated.
The second proposal is to have the example implementation `InMemoryPersistedQueryCache` register query from the execution input, much like Apollo implementation does in [requestPipeline.ts](https://github.com/apollographql/apollo-server/blob/0aa0e4b2 …

Apollo Persisted Query check hash & In Mem cache use Execution Input Query

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java

- Related to: #1099
- Related to: #1102
This pull request proposes a more permissive fix for the bug observed in #1099.
The current fix, introduced in #1102, disables data loader batching on mutations altogether. While it works great when staying within the realms of specification compliance, it seems too restrictive: if mutations are configured to use `AsyncExecutionStrategy`, then I believe it shouldn't be an issue to allow data loader batching there too–as the `bug #1099 test mutation completes as expected and does not hang - running #note` test suggests.
For context, the reason I'm opening this PR is that my mutations become far too expensive to compute when batching is disabled; and while the ideal solution would be a core fix of #1099, I would be okay with trading spec. compliance …

More permissive fix for #1099.

---

src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy

This commit fixes `TypeDefinitionRegistry.isPossibleType` and
`isSubType` to consider an _interface_ that implements another interface
as a sub-type of the implemented interface. Before this commit, only an
_object_ type implementing an interface was considered as a sub-type of
the implemented interface. So this small change brings the
implementation into full alignment with the below part of the spec:
```
IsValidImplementationFieldType(fieldType, implementedFieldType):
...
5. If {fieldType} is an Object or Interface type and
{implementedFieldType} is an Interface type and {fieldType}
declares it implements {implementedFieldType} then return {true}.
...
```

Fix interfaces implementing interfaces sub-type validation

---

src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java
src/test/groovy/graphql/execution/SimpleDataFetcherExceptionHandlerTest.groovy

For now the one we handle is CompletionException
See https://github.com/graphql-java/graphql-java/issues/1652

Unwrap certain exceptions in the SimpleDataFetcherExceptionHandler

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This allows for printing just a directive, which is not a `GraphQLType`
cc @skevy

allow printing of just directives

---

src/test/java/benchmark/SchemaTransformerBenchmark.java
src/test/resources/large-schema-3.graphqls

Early results on my local machine (Macbook pro 2.4 GHz 8-Core Intel Core i9 32 GB 2667 MHz DDR4)
```
Iteration   1: 28894.776 ms/op
Result "benchmark.SchemaTransformerBenchmark.benchMarkSchemaTransformerRemove":
28894.776 ms/op
REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.
Benchmark                                                    Mode  Cnt      Score   Error  Units …
```

Early Perf benchmark for SchemaTransformer

---

src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy
src/test/java/benchmark/BenchmarkUtils.java
src/test/java/benchmark/TypeDefinitionParserVersusSerializeBenchMark.java

This would allow a "parsed" SDL file to be put into an external cache say.
All of the AST nodes are serializable - why not the parsed container of them?  Hence this PR.
However in practice is not that much faster than parsing really.  So caching the SDL String and reparsing might be in the same ballpark and  a String is a simpler contsruct to cache
The benchmark shows that serialization is faster - YMMV
```
Benchmark                                                                                                    Mode  Cnt   Score   Error  Units
TypeDefinitionParserVersusSerializeBenchMark.benchMarkParsing      thrpt   15  16.590 ± 0.320  ops/s
TypeDefinitionParserVersusSerializeBenchMark.benchMarkSerializing  thrpt   15  20.066 ± 0.458  ops/s
```
In a low CPU constrained environment, …

Make TypeDefinitionRegistry serializable

---

src/main/java/graphql/schema/idl/FetchSchemaDirectiveWiring.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorDirectiveHelper.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

This tracks whether SchemaDirectiveWiring is required and hence allows us to short cut things if not
It also removes FetchSchemaDirectiveWiring.java from automatically being used - its now deprecated and will be removed at a future date
This is therefore a breaking runtime change for those who rely in `@fetch` but we don't think anyone really does

Performance improvement - Track  whether SchemaDirectiveWiring is required

---

src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy

Previously object types which were only references by a Union were not checked
cc @skevy

SchemaDiff bugfix: check types only referenced by a Union too

---

src/main/java/graphql/schema/SchemaTransformer.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

When a deleted node is visited again via backRef it should not call the visitor and `zipper.curNode()` actually returns `null` causing a NPE, therefore exiting early.
cc @skevy

SchemaTransformer bugfix: handle a deleted node visited again via backref

---

src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/SchemaTransformer.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringSchemaGeneratorPostProcessing.java
src/main/java/graphql/util/DefaultTraverserContext.java
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/java/benchmark/SchemaBenchMark.java
src/test/resources/large-schema-rocketraman.graphqls

I started by running things under JProfiler
I noticed some hotspots and then decided to have a look at them
I added benchmark to ensure I got progress
```
Starting Benchmark
SchemaBenchMark.benchMarkLargeSchemaCreate  thrpt   15  16.243 ± 2.037  ops/s
```
I then applied the Immutable list breadcrumb fix
```
BreadCrumb change in graphql.util.DefaultTraverserContext#DefaultTraverserContext
SchemaBenchMark.benchMarkLargeSchemaCreate  thrpt   15  18.862 ± 1.120  ops/s
```
and then I applied the SchemaDirectiveWiringSchemaGeneratorPostProcessing change
```
After graphql.schema.idl.SchemaDirectiveWiringSchemaGeneratorPostProcessing change …
```

Some benchmarking and improvements to schema creation times and object allocations

---

src/main/java/graphql/schema/DataFetcherFactoryEnvironment.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

The code registry was always meant to be a place of data fetching defaults but this was missed in schema generation
See https://github.com/graphql-java/graphql-java/issues/2282

CodeRegistry can be used to provide the default data fetcher as intended

---

src/main/java/graphql/schema/CodeRegistryVisitor.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/SchemaTransformer.java
src/main/java/graphql/schema/impl/GraphQLTypeCollectingVisitor.java
src/main/java/graphql/schema/impl/MultiReadOnlyGraphQLTypeVisitor.java
src/main/java/graphql/schema/impl/SchemaUtil.java
src/main/java/graphql/schema/impl/StronglyConnectedComponentsTopologicallySorted.java
src/main/java/graphql/util/Anonymizer.java
src/test/groovy/graphql/schema/impl/SchemaUtilTest.groovy
src/test/java/benchmark/SchemaBenchMark.java

This is a WORK implementation of building a GraQhlSchema object with only less traversal
At this stage I left the OLD code in there so you could see what's different
It would be cleaned up if we accepted this code.
I copied the bench mark from the previous PR and run it.
It shows that this code as is BETTER - but not ground breakingly better.
Start
```
SchemaBenchMark.benchMarkLargeSchemaCreate  thrpt   15  18.134 ± 1.099  ops/s
```
This work as is
```
SchemaBenchMark.benchMarkLargeSchemaCreate  thrpt   15  19.771 ± 0.685  ops/s
```
I then took out the validation steps just to see what would happen to the numbers.
```
Benchmark …
```

Initial work on Traversal Improvements in GraphqlSchema builds

---

src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy

This creates a fast path way to change schema properties that are not related to the complex rule driven type graph
This is simple object re-allocation - no traversals and zippers etc...

Simple builder for graphql schema

---

src/main/java/graphql/schema/SchemaTransformer.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

curZippers was never cleaned up before, now the zippers get removed when no longer needed.
This especially affected `zipperWithSameParent` for long large schemas

SchemaTransformer performance improvements 

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

This allows the schema gen to NOT contain AST type definitions and hence saves memory
The real question is - should we make this the default (save memory by default) or not.

Options to control whether AST definitions are captured or not

---

src/main/java/graphql/schema/SchemaTransformer.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

a single changed element inside a scc caused a bug. Example test is changing __Field.

bugfix SchemaTransformer: a single changed element inside a scc

---

build.gradle
src/test/groovy/readme/DataLoaderBatchingExamples.java

Dataloader 3.x introduced a new "async `ValueCache`" which, while powerful, is causing problems and need revision
As such, with graphql-java 17.0 imminent, we have decided to revert back to the battle tested 2.2.3 version and we will revisit the dataloader code in another version

Reverting DataLoader to 2.x version for graphql-java 17

---

src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/ExecutionStrategyInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
src/test/groovy/graphql/Issue2068.groovy

This an attempt to fix #2068 . It might be a bit too naive, but i wanted to get another set of eyes on this issue.
Here my reasoning for this fix:
As explained in the issue, the problem lies in how the dataloader determines when to dispatch different levels. When one of the `resolveFieldWithInfo` futures completes exceptionally, the `Async.each` Future also completes exceptionally and the dataloader instrumentation is not made aware of this. Since `expectedStrategyCallsPerLevel` is increased by calls to `handleOnFieldValuesInfo` by previous levels and `allOnFieldCallsHappened` is checked for the previous level when dispatching, it means that all deeper levels will never be dispatched (`expectedStrategyCallsPerLevel` is bigger than `happenedOnFieldValueCallsPerLevel`) and we leak a thread. …

Fixes #2068 - Silent thread leak on exception in completeValueForList

---

src/main/java/graphql/Mutable.java
src/main/java/graphql/normalized/ENFMerger.java
src/main/java/graphql/normalized/ExecutableNormalizedField.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/main/java/graphql/normalized/FieldCollectorNormalizedQueryParams.java
src/main/java/graphql/schema/GraphQLTypeUtil.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

This PR fixes a problem with the ENOF which could lead to wrong executable normalized operations.
Specifically it is about diverging fields, which are fields with the same result key, but they can't be merged together:
E.g.:
```graphql
{
pets {
... on Dog {
friends { #P1
... on Dog {
breed: dogBreed #F1
}
}
}
... on Cat {
friends {  #P2
... on Dog {
breed #F2
}
}
}
}
}
```
Here P1 and P2 need to result into two different normalized fields, because the children actually differ: F1 is different from F2.

Bugfix for ExecutableNormalizedOperationFactory

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/language/BooleanValue.java
src/main/java/graphql/language/FloatValue.java
src/main/java/graphql/language/IntValue.java
src/main/java/graphql/language/ObjectField.java
src/main/java/graphql/language/StringValue.java
src/test/groovy/graphql/execution/ValuesResolverTestLegacy.groovy
src/test/groovy/graphql/language/NodeVisitorStubTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This fixes a Bug in the ValueResolver when called from the SchemaPrinter such that object values had null names
It also adds some handy `Value.of` methods to make AST VALUE literals easier to use

This fixes a Bug in the ValueResolver 

---

src/main/java/graphql/validation/ValidationErrorCollector.java
src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/test/groovy/graphql/validation/MaxValidationErrorsTest.groovy
src/test/java/benchmark/TypeDefinitionParserVersusSerializeBenchMark.java

Its not useful to have 10,000 validation errors in a response
However an attack can use this to DOS the engine and force it to produce lots of validation errors at the expense of CPU nd memory.
This introduces a maximum number of validation errors messages.

Support Max validation errors being produced

---

src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/ParseCancelledException.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/schema/idl/SchemaParser.java
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

PR for limiting parsing tokens

Help prevent DOS attacks on graphql servers

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

When we build the applied directives we dont put in the AST definitions if they are asked for.
This was missed

This adds the AST definitions onto applied directives and applied arguments

---

src/main/java/graphql/ParseAndValidate.java
src/main/java/graphql/PublicSpi.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/ParsingListener.java
src/test/groovy/graphql/parser/ParserTest.groovy

This adds a parser listener interface that allows a caller to add an parse listener pew request or JVM wide
With this one could count how many tokens or keep metrics on how many tokens are being presented etc..

Adding a parser listener AND the ability to set parser options per request

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Addresses #2524.
Previously, an non-nullable argument with a coerced null value raised a generic `RuntimeException`. This PR updates the exception to be more meaningful.

Improve non-nullable argument exception in ValuesResolver

---

src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/GraphQLTypeUtil.java
src/main/java/graphql/schema/idl/SchemaParseOrder.java
src/main/java/graphql/schema/idl/SchemaParser.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy

This provides a tracker class that remembers the order of elements
as they were parsed.
This could then be used by a print a schema in parse order say

Support for tracking the parse order

---

src/main/java/graphql/language/AstTransformer.java
src/test/groovy/graphql/language/AstTransformerTest.groovy

Hello from Twitter!
I'm working on a task for my overlord @jbellenger to prune unused fragments from a `Document`. To accomplish this, I'm hoping to pass a context argument into the `AstTransfromer` which will provide the names of the nodes to prune. This seems like functionality other users may want from `AstTransfromer` so I'm raising a pull request to add it. 
I overloaded the `.transform()` method of `AstTransformer` so that it accepts a "rootVars" object, and passes it to the `TreeTransformer`. 
This is my first time contributing to graphql-java, or any open source project, so please let me know if I should add other details before raising a PR in the future. Looking forwards to working with y'all.

Added support for a context object to the AstTransformer

---

src/main/java/graphql/schema/GraphQLInterfaceType.java
src/test/groovy/graphql/schema/GraphQLInterfaceTypeTest.groovy

Fixes #2546.
An interface (or object) can contain a type reference to itself. The referenced type is replaced with the real type object when the schema is built.
This PR adds support for type references in `GraphQLInterfaceType` builders, making these equivalent to builders in `GraphQLObjectType`.

Add type reference support to interface builders

---

src/test/groovy/graphql/ExecutionInputTest.groovy

The integration test was checking if DataFetchingEnvironment#getLocale()#getDisplayName() returned "German" when the locale passed to the ExecutionInput was Locale.GERMAN.
This PR changes the call to [getDisplayName(Locale.ENGLISH)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Locale.html#getDisplayName(java.util.Locale)). Making sure the system locale doesn't affect the test.
My Locale is nl_NL, so the test was comparing `Duits` ("German" in Dutch) to `German` (in English of course)

Fix integration test using the default Locale in Locale#getDisplayName()

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy

This is my first PR on this project, glad to be able to finally contribute! Please let me know if I should change anything.
This PR fixes #2609.
~~The same issue may also emerge at line [461](https://github.com/graphql-java/graphql-java/commit/0d52319db6d0b02bf9126297dcee6aad304b5bdc#diff-2ece51452808f5a3fd08db50de534a12806aa6cd4e236c549dff9759884e43ffR461) and [476](https://github.com/graphql-java/graphql-java/commit/0d52319db6d0b02bf9126297dcee6aad304b5bdc#diff-2ece51452808f5a3fd08db50de534a12806aa6cd4e236c549dff9759884e43ffR476) (I wouldn't know in which situations though). LMK if I should apply the same change there.~~
The PR fixes compliance with the GraphQL (October 2021) spec [section 6.2.3.2 ("Response Stream") under ExecuteSubscriptionEvent point 5. …

Propagate errors to individual Subscription events

---

src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
src/main/java/graphql/execution/instrumentation/dataloader/IntMap.java
src/test/groovy/graphql/execution/instrumentation/dataloader/IntMapTest.groovy
src/test/java/benchmark/IntMapBenchmark.java

@andimarek @bbakerman hello :) 
I would like to propose the following optimization in `FieldLevelTrackingApproach`. By using a custom data structure (a glorified int[] array), it is possible to gain some performance.
I wrote 2 performance tests:
- JMH `IntMapBenchmark` (included in the PR) on my machine, I get 5x better performance:
```
Benchmark                                Mode  Cnt        Score         Error  Units
IntMapBenchmark.benchmarkIntMap         thrpt   10  5698421.790 ± 1355795.218  ops/s
IntMapBenchmark.benchmarkLinkedHashMap  thrpt   10  1089616.718 ±   72838.075  ops/s
```
- quickperf memory test (not included in the PR):
```java
@RunWith(QuickPerfJUnitRunner.class)
public class QuickPerfTest {
@Test
@MeasureHeapAllocation
public void measureLinkedHashMap() {
for (int j …
```

Using custom data structure for callstack tracking

---

build.gradle

Our test output is getting large and its HARD to find the failing tests - so lets only print out failing or skipped tests

Only print out important tests

---

src/main/antlr/GraphqlSDL.g4
src/test/groovy/graphql/parser/SDLParserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Fixes graphql-java/graphql-java#2649
Represented as |opt in the GraphQL specification
Link to union tests in graphql-js: https://github.com/graphql/graphql-js/blob/3ab82f4981970f50dd3a96e22a11839e4ec5bb7b/src/language/__tests__/schema-parser-test.ts#L892-L962
Spec blame: https://github.com/graphql/graphql-spec/blame/c18590c477d6817d73e19b6c248c9fcc62b03017/spec/Appendix%20B%20--%20Grammar%20Summary.md#L327
graphql-js does not seem to provide directive tests for this specific circumstance (I should really open a PR over there)

Allow leading pipe in directive SDL, and add leading union pipe tests

---

src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java
src/test/groovy/graphql/schema/idl/SchemaTypeDirectivesCheckerTest.groovy

`ArgValueOfAllowedTypeChecker#checkArgValueMatchesAllowedScalar()` doesn't check the runtime wiring's wiring factory first when fetching scalar implementations, which can lead to it missing them. This PR updates the code to check it.

Bugfix: Check wiring factory when fetching scalar implementations in ArgValueOfAllowedTypeChecker

---

src/main/java/graphql/validation/rules/VariableTypesMatchRule.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/validation/rules/VariableTypesMatchRuleTest.groovy

Hi folks!
Graphql-java currently fails the document validation for queries that use nullable types for non-nullable schema field arguments with default values. As per [spec](https://spec.graphql.org/June2018/#sec-All-Variable-Usages-are-Allowed):
> A notable exception to typical variable type compatibility is allowing a variable definition with a nullable type to be provided to a non‐null location as long as either that variable or that location provides a default value.
Here's a discussion from 2018 where this change to the spec was adopted: https://github.com/graphql/graphql-spec/pull/418.
Schema:
```
type Query {
hello(arg: Boolean! = true)
}
```
Query:
```
query Test($var: Boolean) {
hello(arg: $var)
}
```
This is expected to pass the validation, but currently fails: …

Bugfix: spec-compliant behaviour for non-nullable types with default values.

---

src/main/java/graphql/TypeResolutionEnvironment.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ResolveType.java
src/main/java/graphql/execution/TypeResolutionParameters.java
src/main/java/graphql/execution/nextgen/ExecutionStrategyUtil.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalyzer.java
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy
src/test/groovy/graphql/TypeResolverExecutionTest.groovy

This makes the field selection set available to the TypeResolvers
This relates to #2593 
Even if this PR is not accepted, we should take elements of it.  Namely a miss labeled API class, the missing GraphqlContext and the missing deprecation on context object

This adds the field selection set to the type resolver

---

src/main/java/graphql/introspection/Introspection.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy

The `GraphQLEnumValueDefinition.value` of `VARIABLE_DEFINITION` was `DirectiveLocation.INPUT_VALUE_DEFINITION` instead of `DirectiveLocation.VARIABLE_DEFINITION`.
Closes graphql-java/graphql-java#2702

Fix gh-2702 and add `Introspection.__DirectiveLocation` regression tests

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/ParseAndValidate.java
src/main/java/graphql/nextgen/GraphQL.java
src/main/java/graphql/validation/Validator.java
src/test/groovy/graphql/ParseAndValidateTest.groovy

This used a `GraphqlContext` hint to pass in the predicate needed to skip certain rules

Allow certain query validation rules to be skipped

---

src/main/java/graphql/schema/idl/SchemaPrinter.java

The printer was printing `\r\n` sequences instead of `\n`, because it was using `PrintWriter#println`
Fixes the `"can print a schema as AST elements"` test in `SchemaPrinterTest.groovy` on Windows
See
https://docs.oracle.com/javase/8/docs/api/java/io/PrintWriter.html#println--
> The line separator string is defined by the system property line.separator, **and is not necessarily a single newline character ('\n')**.

Fix wrong newline on Windows in `SchemaPrinter` (`\r\n -> \n`)

---

src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsIntTest.groovy

ScalarFloatTest and ScalarIntTest used the wrong constructor. This caused failing tests when compiling past JDK 8.
Also adds a ScalarFloatTest testcase for `new BigDecimal("4.2") -> 4.2d`
Part of my CI effort (#2676 )

Replace wrong constructor call to BigInteger in tests

---

src/main/java/graphql/schema/idl/ImplementingTypesChecker.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/idl/UnionTypesChecker.java

Compilation of these specific methods fails on JDK 9+. IntelliJ does not produce IDE warnings/errors.
Probably related to JEP 215 "Tiered Attribution for javac"
See: https://openjdk.java.net/jeps/215
Part of my CI effort (#2676 )

Fix generics on JDK 9+

---

src/main/java/graphql/execution/ExecutionStepInfo.java

This missing annotation causes compilation failures on JDK 9+ because of JEP 277 "Enhanced Deprecation"
The method is annotated in the javadoc comment, hence causing compilation failure.
See: https://openjdk.java.net/jeps/277
Part of my CI effort (#2676 )

Add missing `@Deprecated` to `ExecutionStepInfo#getFieldContainer()`

---

src/main/java/graphql/language/AstPrinter.java
src/test/java/benchmark/AstPrinterBenchmark.java

```
Benchmark                                           Mode  Cnt     Score     Error  Units
AstPrinterBenchmark.benchMarkAstPrinterThroughput  thrpt   15  3715.744 ± 102.575  ops/s
AstPrinterBenchmark.benchMarkAstPrinterAvgTime      avgt   15     0.282 ±   0.022  ms/op
Benchmark                                           Mode  Cnt     Score     Error  Units
AstPrinterBenchmark.benchMarkAstPrinterThroughput  thrpt   15  4468.229 ± 153.149  ops/s
AstPrinterBenchmark.benchMarkAstPrinterAvgTime      avgt   15     0.220 ±   0.015  ms/op
```
ps - this is the benchmarks but with printCompact - its still MUCH faster
```
Benchmark                                                  Mode  Cnt     Score     Error  Units
AstPrinterBenchmark.benchMarkAstPrinterCompactThroughput  thrpt   15  8555.174 ± …
```

AstPrinter performance improvements

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/nextgen/Common.java
src/main/java/graphql/normalized/ExecutableNormalizedField.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/main/java/graphql/normalized/VariableAccumulator.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Not done, need to review the logic, clean it up and add tests etc. Just putting up for early review.
This heavily compresses some queries described in GQLGW-1181.
It got the query I had down from 4k lines to 800

Improve ExecutableNormalizedField.isConditional for interface fields and fix a bug regarding covariant fields

---

src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLUnionType.java

The removal of the builder methods into a common base lib created a binary incompatible change.  This moves them back

Avoid a binary incompatible change while retaining common code

---

src/main/java/graphql/normalized/ENFMerger.java
src/main/java/graphql/normalized/ExecutableNormalizedField.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy
src/test/groovy/graphql/schema/DataFetchingFieldSelectionSetImplTest.groovy

This also includes a test for the DFSelectionSet for covariance fields.
It also fixes a bug for ENF where __typename in Unions were not merged.

Rework isConditional to work without parent type name and adopt DataFetchingSelectionSet to ENF changes

---

src/main/java/graphql/TypeResolutionEnvironment.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/ExecutionStepInfoFactory.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ResolveType.java
src/main/java/graphql/execution/TypeResolutionParameters.java
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy

This will improve memory usage if you don't use the ESI arguments, and it will reduce CPU usage somewhat in heavy systems by doing less work (albeit by a small amount)
If a DFE or other code does not ask for the arguments - then no value resolving will happen for them.

Make ExecutionStepInfo values be lazy

---

src/main/java/graphql/schema/idl/ScalarInfo.java

Public static fields in ScalarInfo were exposing mutable collections
that are obviously not intended to be modified. Switch to immutable
collection types to avoid accidental mutation.

Make public static fields immutable in ScalarInfo

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/Issue743.groovy
src/test/groovy/graphql/NullVariableCoercionTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

In #2761, the message from `NonNullableValueCoercedAsNullException` made it hard to identify the offending value. This PR improves the exception's message.
**Before**, we would throw
```
throw new NonNullableValueCoercedAsNullException("", emptyList(), graphQLType);
```
Which led to this unclear message
```
Field '' has coerced Null value for NonNull type 'String!'
```
**Now**, the message will include the offending variable's name and the reason for the exception
```
Variable 'foo' has invalid value: Coerced Null value for NonNull type 'String!'
```

Improve NonNullableValueCoercedAsNullException message

---

src/main/java/graphql/schema/idl/DirectiveInfo.java

Public static fields in DirectiveInfo were exposing mutable collections
that are obviously not intended to be modified. Switch to immutable
collection types to avoid accidental mutation.

Make public static fields immutable in DirectiveInfo

---

src/main/java/graphql/schema/idl/TypeInfo.java

Replace Stack with ArrayDeque in TypeInfo.
See https://errorprone.info/bugpattern/JdkObsolete

Replace usage of Stack with Deque / ArrayDeque

---

src/main/java/graphql/schema/idl/errors/NonSDLDefinitionError.java
src/main/java/graphql/util/Anonymizer.java

Fix instances where too many or too few arguments were supplied to String.format.

Fix argument / format string mismatches

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

When converting the introspection response to GraphQLSchema, the descriptions in the enumvalues are missing. Please accept my contribution to fix this issue.

Fixing the missing description for enum values for introspection to schema conversion

---

src/main/java/graphql/language/EnumValue.java
src/main/java/graphql/language/NullValue.java
src/main/java/graphql/normalized/ValueToVariableValueCompiler.java
src/test/java/graphql/normalized/ValueToVariableValueCompilerTest.groovy

Two bugs where discovered in rthe Atlassian graphql gateway
```
java.lang.NullPointerException: null
at graphql.normalized.ValueToVariableValueCompiler.normalisedValueToVariableValue(ValueToVariableValueCompiler.java:56)
at graphql.normalized.ValueToVariableValueCompiler.lambda$normalisedValueToVariableValues$0(ValueToVariableValueCompiler.java:79)
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
at graphql.normalized.ValueToVariableValueCompiler.normalisedValueToVariableValues(ValueToVariableValueCompiler.java:78)
at graphql.normalized.ValueToVariableValueCompiler.normalisedValueToVariableValue(ValueToVariableValueCompiler.java:54)
at graphql.normalized.ValueToVariableValueCompiler.normalizedInputValueToVariable(ValueToVariableValueCompiler.java:31)
at …
```

Variable document compilation now handles enums properly AND also null input values

---

src/main/java/graphql/language/Comment.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/ParserOptions.java
src/test/groovy/graphql/parser/ParserTest.groovy

This commit adds the ability to ignore single-line comments during AST conversion.
Fixes graphql-java/graphql-java#2767
Always glad to help ❤️

Add ParserOption to ignore single-line comments

---

src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/validation/rules/UniqueArgumentNamesRule.java

Fix a few occurrences where a Map or Set was initialized with an initial capacity
value N, and then immediately filled with N items, which would always trigger
a resize.

Fix instances of incorrectly sized Maps and Sets

---

src/main/java/graphql/GraphqlErrorBuilder.java
src/main/java/graphql/execution/directives/QueryAppliedDirective.java

Use jetbrains annotations

---

src/main/java/graphql/cachecontrol/CacheControl.java
src/main/java/graphql/schema/GraphQLTypeResolvingVisitor.java

There were a few instances where inner classes were used unnecessarily over
static inner classes.

Make some inner classes static

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/language/AstPrinterTest.groovy

`AstPrinter.printAst` omits field descriptions when there are no arguments or the arguments have no descriptions.
**To reproduce** 
```graphql
AstPrinter.printAst(Parser().parseDocument("""type Query { "comment" a: String }"""))
```
```graphql
AstPrinter.printAst(Parser().parseDocument("""type Query { "comment" a("comment2" s: String): String }"""))
```

Fix `AstPrinter` to print field descriptions

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/analysis/QueryComplexityInfo.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy
src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy

Previously the MaxQuery depth instrumentation was called on the end of the validation step.  But this is too early if there are null / non null variables mismatched.  This caused and exception to be thrown and not a graphql error.
We now call the instrumentation during the `beginExecuteOperation` which is JUST before execution proper and not after validation - because the `Execution` code does some more sensibility checks on the state of the call
I started this branch from https://github.com/graphql-java/graphql-java/pull/2763 which showed the problem happening
I am leaving that PR so we can improve the error messages - but this PR fixes the actual problem in the sense query checks are done a smidge later and avoid the problem all together

Max query depth called later in beginExecuteOperation

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/analysis/QueryTransformerTest.groovy
src/test/groovy/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupportTest.groovy
src/test/groovy/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCacheTest.groovy
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/language/AstSignatureTest.groovy
src/test/groovy/graphql/language/AstSorterTest.groovy
src/test/groovy/graphql/language/AstTransformerTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy
src/test/groovy/graphql/util/AnonymizerTest.groovy
src/test/groovy/graphql/util/TreeParallelTransformerTest.groovy

AstPrinter's operationDefinition method had a String comparison that would
always fail when checking the node's operation; the String contained in
the op variable was already lowercased, while the constant "QUERY" was
used in the comparison. The result was that query short form was
never used when printing queries.

Fix bug in AstPrinter preventing query short form from being used

---

src/main/java/graphql/schema/idl/RuntimeWiring.java
src/test/groovy/graphql/schema/idl/RuntimeWiringTest.groovy

Hi!
In [Federation-JVM](https://github.com/apollographql/federation-jvm) we have a use-case where we need to 'augment' an existing `RuntimeWiring`, but there is no straightforward way to do that ([here](https://github.com/apollographql/federation-jvm/blob/master/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/Federation.java#L174) is how we do it currently, but it's not ideal).
This PR adds a `newBuilder` method for this use-case.

Add RuntimeWiring.newBuilder

---

src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy

Hello from Twitter!
We've discovered that our deprecated enums were marked as DEPRECATION_ADDED when they were unchanged. We used a pre-existing test schema file that already contained a deprecated enum but if you'd like us to create a new schema file, let me know!
Thank you,
Cynthia Qian

Fixes SchemaDiff Bug where unchanged deprecated enum marked DEPRECATION_ADDED

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationSupport.java
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy
src/test/groovy/graphql/schema/CoercingTest.groovy

This PR fixes double variable coercion in `QueryTraverser` and classes using traversal such as `MaxQueryComplexityInstrumentation`, `MaxQueryDepthInstrumentation`, and `FieldValidationSupport`. Fixes #2819.
Previously, raw and coerced variables were represented as plain maps `Map<String, Object>`. Using the same type made it hard to distinguish raw from coerced variables and in some places, such as `MaxQueryDepthInstrumentation`, we unintentionally coerced variables twice. The double coercion was there for some time (e.g. #2458), but became a problem in v18.1 (see #2819)
```
Caused by: graphql.schema.CoercingParseValueException: Variable 'memberDues' has an invalid value: Failed to parse input value 2022-05-16T19:52:37Z as ZonedDateTime
Caused by: java.lang.IllegalArgumentException: …
```

Fix double variable coercion in QueryTraverser

---

src/main/java/graphql/normalized/ValueToVariableValueCompiler.java
src/test/groovy/graphql/normalized/ValueToVariableValueCompilerTest.groovy

Some values in the NIV can be a list with null values.  So we cant use ImmutabvleList in the mapper as its wont accept nulls entries
```
java.lang.NullPointerException: null
at graphql.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
at graphql.com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:813)
at graphql.collect.ImmutableKit.map(ImmutableKit.java:85)
at graphql.normalized.ValueToVariableValueCompiler.normalisedValueToVariableValues(ValueToVariableValueCompiler.java:75)
at graphql.normalized.ValueToVariableValueCompiler.normalisedValueToVariableValue(ValueToVariableValueCompiler.java:53)
at graphql.normalized.ValueToVariableValueCompiler.lambda$normalisedValueToVariableValues$0(ValueToVariableValueCompiler.java:82)
at …
```

This fixes the ImmutableMap .map problem where lists can have null in them

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java

@bbakerman @andimarek  hi guys :)
while profiling in YourKit, I spotted some extra array allocations for CompletableFuture. This is still an idea... and a work in progress... please have a look :-) There is a special handling for SelectionSet of only 1 field: in this case the array allocation  could be removed completely. 
Baseline:
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  52.398 ± 0.944  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime      avgt   15  19.028 ± 0.376  ms/op
```
After this PR:
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  55.134 ± 0.782  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime …
```

Avoiding Async array copies 

---

src/main/java/graphql/introspection/Introspection.java
src/test/java/benchmark/IntrospectionBenchmark.java

I spent some time trying to see if Introspection could be made faster.  But after some half a day at it - I learnt its pretty much as fast as its going to be.
This particular test file (large-schema-4) has 18,850 types and that results in 1,271,620 data fetcher calls.
df fetches like
```
/__schema/types[18375]/fields[4]/args               
/__schema/types[18375]/fields[4]/type                 
/__schema/types[18375]/fields[4]/type/kind        
/__schema/types[18375]/fields[4]/type/name             
/__schema/types[18375]/fields[4]/type/ofType               
/__schema/types[18375]/fields[4]/isDeprecated                 
/__schema/types[18375]/fields[4]/deprecationReason                    
/__schema/types[18375]/fields[5]/name …
```

Introspection performance investigation

---

src/main/java/graphql/collect/ImmutableKit.java
src/test/java/benchmark/ListBenchmark.java

@bbakerman  @andimarek a breaking change in `ImmutableKit`  that provides a nice "free lunch": 
by switching the signature from `Iterable` to `Collection` it is possible to pre-size the builder to avoid any extra allocation.
The class is is marked as `@Internal` so maybe it not a problem at all :)
List size = 10000
```
Benchmark                                          Mode  Cnt     Score     Error  Units
ListBenchmark.benchmarkArrayList                  thrpt   10  1879.357 ± 185.666  ops/s
ListBenchmark.benchmarkImmutableCollectorBuilder  thrpt   10  1879.835 ±  16.009  ops/s
ListBenchmark.benchmarkImmutableListBuilder       thrpt   10  1916.382 ±  13.232  ops/s
ListBenchmark.benchmarkImmutableListBuilder2      thrpt   10  1996.370 ±  15.618  ops/s <- new …
```

ImmutableKit.map with pre-size

---

build.gradle

[The issue preventing the current version of graphql-java from working with the Java module system](https://github.com/graphql-java/java-dataloader/issues/110) has been resolved, so the java-dataloader dependency should be upgraded.
The latest version update for java-dataloader was in graphql-java 18.0 (Mar 15, 2022) to version 3.1.2. This update will pull in the 3.1.4 fix and also the 3.1.3 changes.

Upgrade dataloader to 3.1.4

---

build.gradle
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java

This PR shades `antlr-runtime` and removes it off the pom.
`antlr-runtime` version clashes can be a blocker as described in https://github.com/graphql-java/graphql-java/issues/2809 and https://github.com/openrewrite/rewrite/issues/1615

Shade antlr-runtime

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Schema description is available through introspection but is not included in the printed SDL. Update `SchemaPrinter` to also include schema description in the printed SDL.

SchemaPrinter should include schema description in printed SDL

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/CoercedVariables.java
src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStepInfoFactory.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/RawVariables.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/directives/DirectivesResolver.java
src/main/java/graphql/execution/nextgen/ExecutionHelper.java
src/main/java/graphql/execution/nextgen/ValueFetcher.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/ExecutionInputTest.groovy
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/execution/ConditionalNodesTest.groovy
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy
src/test/java/benchmark/NQBenchmark1.java
src/test/java/benchmark/NQBenchmark2.java

Cherry picks the raw and coerced variable refactor changes in #2802, master commit `86d54438`
We'll be releasing a few bugfixes from this branch, to allow users to choose between bugfixes only or all master changes (to be released as v19). We're using the pull request format to keep track of changes

Cherry pick raw and coerced variable refactor for 18.x branch

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionQuery.java
src/main/java/graphql/schema/idl/SchemaGeneratorAppliedDirectiveHelper.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy

See #2822 
When we added input type deprecation we missed these in introspection.  Other tooling such as graphql-js tooling will send them in and they will be rejected as invalid (eg that arg does not exist)

 introspection was missing some deprecation filtering support

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/CoercedVariables.java
src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/RawVariables.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/directives/DirectivesResolver.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

The new RawVariables and CoercedVariables are currently marked as `@Internal` but they are not - they can be read back from very public places like ExecutionInput and they are required as parameters into very public places like QueryTraverser

RawVariables and CoercedVariables are public API

---

src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironment.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironmentImpl.java
src/main/java/graphql/schema/idl/SchemaGeneratorDirectiveHelper.java

This deprecation was missed in 18.0 and should have been done then
See #2824

SchemaDirectiveWiringEnvironment now deprecates the old directive getters in lieu of applied directives

---

.github/workflows/pull_request.yml
src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationSupport.java
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy
src/test/groovy/graphql/schema/CoercingTest.groovy

Cherry pick the double variable coercion fix #2836 for our bugfix branch

Cherry pick double variable coercion fix

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/CoercedVariables.java
src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/RawVariables.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/directives/DirectivesResolver.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Cherry picks @bbakerman's PR RawVariables and CoercedVariables are public API (#2868) (cherry picked from commit 6090f3cc8b94d3b24c203ed8b798dfd6787dbf2d)
This is the last cherry pick before we release 18.2.

Bugfix cherry pick: RawVariables and CoercedVariables are public API (#2868)

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/analysis/QueryTransformerTest.groovy
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/language/AstTransformerTest.groovy
src/test/groovy/graphql/util/AnonymizerTest.groovy

See #2869
Tests need to be fixed

This tightens the AST compact printing

---

src/main/java/graphql/schema/transform/FieldVisibilitySchemaTransformation.java
src/test/groovy/graphql/schema/transform/FieldVisibilitySchemaTransformationTest.groovy

Fixes a bug in `FieldVisibilitySchemaTransformation` that caused types reachable via interface implementations to not be included in the filtered schema.
The bug can cause the transformation to throw an assertion exception

Field visibility schema transform supports types reachable via interfaces only

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Fix for #2883.
Callers of `buildOutputType` were wrongly expecting result could be cast to `GraphQLInterfaceType`.  Using `GraphQLNamedOutputType` is a wider type that is compatible.

#2883 Fix classCastException when using an extension 

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStepInfoFactory.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/directives/DirectivesResolver.java
src/main/java/graphql/execution/nextgen/ExecutionHelper.java
src/main/java/graphql/execution/nextgen/ValueFetcher.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Make every method in `ValuesResolver` static and save some object allocations. It's a util class that doesn't need to have instances.

Make ValuesResolver methods static

---

build.gradle

After the release graphql-java v19, this will fix #2817.

Bump java-dataloader ahead of release

---

src/main/java/graphql/ParseAndValidate.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/SafeTokenSource.java
src/main/java/graphql/schema/idl/SchemaParser.java
src/test/groovy/graphql/parser/BadParserSituations.java
src/test/groovy/graphql/parser/ParserOptionsTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/parser/SafeTokenSourceTest.groovy
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

This is related to #2888
The bug was that we do indeed have a max token counting mechanism in graphql-java BUt it was being enacted too late.
Testing showed that the max token code was indeed being hit BUT the ANTLR lexing and parsing code was taking proportionally longer to get to the max token state as the input size increased
This is cause bv the greedy nature of the ANTLR Lexer - it will look ahead and store tokens in memory under certain grammar conditions and butted directives like `@lol@lol` are one of them.  This meant that the lexer was the code contributing to CPU time and not the parser - BUT the max token code check was in the parser.
This PR puts the same max token checks on the lexer as it does in the parser.  In fact it debatable if the parser checks should still be …

READY - Stop DOS attacks by making the lexer stop early on evil input.

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/cachecontrol/CacheControl.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java

Fixes #2759 
Apollo has deprecated their Cache Control specification for a while now, and they offer an alternative directive driven approach. Thus we no longer should have `CacheControl` inside graphql-java.
Deprecation notice: https://github.com/apollographql/apollo-cache-control
New directive driven approach: https://github.com/apollographql/apollo-cache-control
This PR deprecates everything related to Cache Control. It will be deleted in an upcoming release.

Deprecate Apollo Cache Control

---

.github/workflows/pull_request.yml
src/main/java/graphql/ParseAndValidate.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/SafeTokenSource.java
src/main/java/graphql/schema/idl/SchemaParser.java
src/test/groovy/graphql/parser/BadParserSituations.java
src/test/groovy/graphql/parser/ParserOptionsTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/parser/SafeTokenSourceTest.groovy
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

17x port of https://github.com/graphql-java/graphql-java/pull/2892

17.x port - Stop DOS attacks by making the lexer stop early on evil input

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/ParseAndValidate.java
src/test/groovy/graphql/GraphQLTest.groovy

If a caller explicitly sets the Locale to null (for whatever reason) we need to be able to default it so the validation I18n code works.
See https://github.com/graphql-java/graphql-java/issues/2907
The design question is - should we default this on `ExecutionInput` construction OR like I have done it here.
This fixes the bug - however defaulting it in EI construction is more systemic.  It would mean that DataFetcherEnvs etc... would always get a Locale say.

Defaults Locale when calling validation

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

See https://github.com/graphql-java/graphql-java/issues/2909
This just hardens the code in this case

Handles isDeprecated not being present in the json

---

src/main/java/graphql/Directives.java
src/test/groovy/graphql/Issue2141.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

There's a unnecessary apostrophe in the description of the skip directive.

Fix typo in description of skip directive

---

src/main/java/graphql/schema/GraphQLTypeUtil.java
src/main/java/graphql/schema/impl/GraphQLTypeCollectingVisitor.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
src/test/groovy/graphql/schema/GraphQLTypeUtilTest.groovy

This is the same code as https://github.com/graphql-java/graphql-java/pull/2905 but with an extra test for `SchemaTransformer` which also fails

Xuorig Fix PR - Edge case with GraphQLTypeReference and Schema Transforms

---

src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/util/FpKitTest.groovy
src/test/java/benchmark/NQExtraLargeBenchmark.java
src/test/resources/extra-large-schema-1-query.graphql
src/test/resources/extra-large-schema-1.graphqls

After parsing and validating an incoming GraphQL operation, the engine creates a normalized version of that operation, the `ExecutableNormalizedOperation`.
For fragments, there is a little more work involved to determine the possible types. Inside `narrowDownPossibleObjects`, there is a set intersection between the current set of possible objects and the set of types from the resolved type condition.
This set intersection can be expensive for very large queries with hundreds of fragments. This PR includes one such example.
In almost every case in the example query, one of the sets being compared only has one member. For example, the resolved types set often has only 1 member, because an inline fragment on a concrete type has only one possible type. It would be equivalent, and much …

Reduce calculation for fragments in ExecutableNormalizedOperation

---

README.md
README.zh_cn.md

Maven is confused and thinks the latest snapshot is from a year ago. It's looking at the version name and not the release date.
This PR fixes up the badge on the readme.

Fix snapshot badge

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/resources/extra-large-schema-1.graphqls

The removed logic belongs inside a scalar's `serialize` method and should not be handled in this location inside `ExecutionStrategy`.
We have already handled the `NaN` case inside `GraphqlFloatCoercing` and we already had a `NaN` test in `ScalarsFloatTest`, see `serialize throws exception for invalid input #value`.
This is an old TODO from 2018. The Float spec has changed since then, now an error is to be raised for non-finite values such as `NaN`. 
Spec: https://spec.graphql.org/draft/#sec-Float
Spec PR: https://github.com/graphql/graphql-spec/issues/778

Remove redundant NaN check, already handled in GraphqlFloatCoercing

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java
src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationInstrumentation.java
src/main/java/graphql/execution/instrumentation/threadpools/ExecutorInstrumentation.java
src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy
src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/threadpools/ExecutorInstrumentationTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy

This is mostly the production classes and their tests.
I have NOT gone to all the tests class implementations of `Instrumentation` and fixed them up
This works because the callers of the instrumentation methods (our code) only ever come in on the on deprecated methods.

Change Instrumentation production implementations to use non deprecated methods

---

src/test/groovy/graphql/DataFetcherWithErrorsAndDataTest.groovy
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/MutationSchema.java
src/test/groovy/graphql/NestedInputSchema.java
src/test/groovy/graphql/NonNullHandlingTest.groovy
src/test/groovy/graphql/RelaySchema.java
src/test/groovy/graphql/ScalarsQuerySchema.java
src/test/groovy/graphql/StarWarsData.groovy
src/test/groovy/graphql/StarWarsSchema.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/AsyncSerialExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderNodeTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DeepDataFetchers.java
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy
src/test/groovy/graphql/schema/GraphQLFieldDefinitionTest.groovy
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy
src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy

Cleaning up tests to use `GraphQLCodeRegistry` for datafetchers, rather than directly on the `GraphQLFieldDefinition`.
You might be thinking, that's so many lines of code for only one builder cleanup! We were using it everywhere.

Deprecation test cleanup: GraphQLFieldDefinition datafetcher builder

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

When @skip/@include is defined in a SDL, schema generation will create a GraphQLSchema with multiple skip/include definitions. This can cause problems when a schema is serialized and parsed multiple times.
A little far fetched example:
```kotlin
@Test
fun parse() {
val schema: GraphQLSchema = """
type Query {
hello: String
}
""".trimIndent().mockSchema()
val sdl = schema.printSdl()
val schema2 = sdl.mockSchema()
val sdl2 = schema2.printSdl()
sdl2.mockSchema() // throws
}
fun GraphQLSchema.printSdl(): String {
return SchemaPrinter(SchemaPrinter.Options.defaultOptions()
.includeDirectiveDefinitions(true)
).print(this)
}
```
will throw:
```
Caused by: SchemaProblem{errors=['include' type [@13:1] tried to redefine existing directive 'include' type [@7:1], 'skip' type [@25:1] tried to redefine …
```

Fix @skip definition is added twice to the GraphQLSchema when defined in sdl

---

src/main/java/graphql/schema/GraphQLAppliedDirectiveArgument.java
src/main/java/graphql/util/Breadcrumb.java
src/main/java/graphql/util/NodeLocation.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

Merge pull request #2934 from graphql-java/Renamed_scalar_still_present_in_the_schema_if_used_as_directive_argument
Reproduction of renaming scalars and applied directives bug # Conflicts:
#	src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

Stable fix for #2934 

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Fix bug where parsing a sdl with @skip definition would result in 2 directive definitions on the GraphQLSchema (#2940)

Stable port of #2940

---

src/main/java/graphql/schema/GraphQLDirectiveContainer.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/InterfacesImplementingInterfacesTest.groovy
src/test/groovy/graphql/TypeMismatchErrorTest.groovy
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy
src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy
src/test/groovy/graphql/execution/ExecutionStepInfoTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/directives/QueryDirectivesIntegrationTest.groovy
src/test/groovy/graphql/execution/instrumentation/LegacyTestingInstrumentation.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationTest.groovy
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy
src/test/groovy/graphql/schema/GraphQLArgumentTest.groovy
src/test/groovy/graphql/schema/GraphQLFieldDefinitionTest.groovy
src/test/groovy/graphql/schema/GraphQLInterfaceTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLUnionTypeTest.groovy
src/test/groovy/graphql/schema/SchemaPrinterComparatorsTest.groovy
src/test/groovy/graphql/schema/SchemaTraverserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/impl/SchemaUtilTest.groovy
src/test/groovy/graphql/schema/transform/FieldVisibilitySchemaTransformationTest.groovy
src/test/groovy/graphql/schema/validation/TypeAndFieldRuleTest.groovy
src/test/groovy/graphql/schema/validation/TypesImplementInterfacesTest.groovy
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

This PR fixes more tests with deprecated methods.
This is the last wave of Groovy test fixes. Next PR will fix deprecated usages in a few Java test/util files.

Test cleanup: typeResolver builder on unions and interfaces, applied directive tests, and more

---

src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/test/groovy/example/http/ExecutionResultJSONTesting.java
src/test/groovy/example/http/HttpMain.java
src/test/groovy/graphql/GarfieldSchema.java
src/test/groovy/graphql/NestedInputSchema.java
src/test/groovy/graphql/ScalarsQuerySchema.java
src/test/groovy/graphql/StarWarsSchema.java
src/test/groovy/graphql/TypeReferenceSchema.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/DataFetcherExceptionHandlerTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyExceptionHandlingEquivalenceTest.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/BatchCompareDataFetchers.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderCompanyProductBackend.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/schema/DelegatingDataFetchingEnvironmentTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectTypeTest.groovy
src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy
src/test/groovy/graphql/validation/SpecValidationSchema.java
src/test/groovy/graphql/validation/ValidateCustomDirectives.groovy
src/test/groovy/graphql/validation/ValidationUtilTest.groovy
src/test/groovy/graphql/validation/rules/Harness.java

Fixing up deprecated API usages in programmatic test schemas, fix last few remaining Java deprecated method overrides
This is the last deprecation fix PR for tests. Next PR will fix deprecated usages in documentation examples

Deprecation cleanout - programmatic schemas

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ResolveType.java

This will improve the runtime for every object type encountered since the type env allocation (and indeed method call) is not needed

Avoid allocating a type resolve env if the type is already an object type

---

src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy
src/test/resources/diff/schema_ABaseLine.graphqls
src/test/resources/diff/schema_changed_field_arguments.graphqls
src/test/resources/diff/schema_changed_input_object_fields.graphqls
src/test/resources/diff/schema_changed_nested_input_object_fields.graphqls
src/test/resources/diff/schema_changed_object_fields.graphqls
src/test/resources/diff/schema_changed_type_kind.graphqls
src/test/resources/diff/schema_dangerous_changes.graphqls
src/test/resources/diff/schema_deprecated_fields_new.graphqls
src/test/resources/diff/schema_interface_fields_missing.graphqls
src/test/resources/diff/schema_missing_enum_value.graphqls
src/test/resources/diff/schema_missing_field_arguments.graphqls
src/test/resources/diff/schema_missing_input_object_fields.graphqls
src/test/resources/diff/schema_missing_object_fields.graphqls
src/test/resources/diff/schema_missing_operation.graphqls
src/test/resources/diff/schema_missing_union_members.graphqls
src/test/resources/diff/schema_with_additional_field.graphqls

SchemaDiff had a single method `checkTypeWithNonNullAndList` that always applied the rule "non-null to nullable is safe; nullable to non-null is breaking."
This is true for input types and arguments, but the opposite should be true for fields on output types -- "nullable to non-null is safe; non-null to nullable is breaking."
A consumer operating on a nullable field should already be checking for presence, and adding an additional guarantee of non-null is safe.
A consumer operating on a non-null field may not be checking for presence, and removing the guarantee of non-null may break when that field is null.
Two methods are defined -- one for input and argument types, and one for output types.
The methods are rewritten in a style of handling three top-level cases for the old type …

Patch SchemaDiff to apply respective nullability change validation for input vs. output types

---

src/main/java/graphql/relay/DefaultConnection.java
src/main/java/graphql/relay/DefaultEdge.java
src/main/java/graphql/relay/DefaultPageInfo.java
src/test/groovy/graphql/relay/DefaultConnectionTest.groovy
src/test/groovy/graphql/relay/DefaultEdgeTest.groovy
src/test/groovy/graphql/relay/DefaultPageInfoTest.groovy

Add equals/hashcode methods to DefaultConnection, DefaultEdge, DefaultPageInfo.
As discussed: https://github.com/graphql-java/graphql-java/discussions/2986
This is my first time using Spock, so please let me know if there's a different or better way to do this testing. I used the tables to try to reduce the test noise.

Add missing equals/hashcode methods to relay classes

---

src/main/java/graphql/execution/ValuesResolverLegacy.java
src/main/java/graphql/scalar/GraphqlFloatCoercing.java
src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsQuerySchema.java
src/test/groovy/graphql/execution/ValuesResolverTestLegacy.groovy

The GraphQL Float spec was updated a year ago to specifically not allow NaN and positive/negative infinity in both result coercion and input coercion 
https://spec.graphql.org/draft/#sec-Float
https://github.com/graphql/graphql-spec/issues/778
The float coercing was mostly compliant with this spec update, as NaN and positive/negative infinity are not allowed in the BigDecimal String constructor used in `GraphqlFloatCoercing`, specifically the line `value = new BigDecimal(input.toString());`.
I say mostly, there was one uncaught case. It's possible for the old `convertImpl` method to return a Double value that is later converted to positive infinity with `BigDecimal.valueOf`, such as in the `valueToLiteralImpl`
```
private FloatValue valueToLiteralImpl(Object input, @NotNull Locale locale) …
```

Float coercion tidy up

---

.github/workflows/invoke_test_runner.yml

We only want this action to run on the main repository. Right now it attempts to execute on all the forks as well – e.g. see failed actions on my fork: https://github.com/folone/graphql-java/actions.
This PR makes use of the syntax described in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif to skip GCP-based tests for all the forks and only run them on main repo.

Only run GCP tests on main graphql-java repo (skip on forks).

---

build.gradle

Our builds are failing because the old builder version was referencing bintray, which was sunset ~11 months ago.
This PR bumps the aQute builder version.
We are using this builder to create OSGI compliant jars.

Update aQute builder version

---

src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringSchemaGeneratorPostProcessing.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorPostProcessing.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

SchemaGeneratorPostProcessing was a previous mechanism that `graphql.schema.SchemaTransformer` is better suited to
We should not have two mechanisms for the same thing
I propose we deprecated it and remove at a later date

SchemaGeneratorPostProcessing should be deprecated

---

src/main/java/graphql/schema/idl/ImplementingTypesChecker.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

Applied directives on arguments are not relevant when checked if an interface is implemented correctly.
For example this SDL should be valid, but it was rejected:
```graphql
directive @d on ARGUMENT_DEFINITION
type Query implements I {
foo(arg: String @d): String
}
interface I {
foo(arg: String): String
}
```
This fixes this bug.

Bugfix for SDL check if an Interface is implemented correctly

---

src/main/java/graphql/TypeResolutionEnvironment.java

Local context is accessible everywhere else. Seems inaccessible here purely by accident.

TypeResolutionEnvironment#getLocalContext seems accidentally non-public

---

src/main/java/graphql/validation/ValidationError.java
src/test/groovy/graphql/validation/ValidationErrorToString.groovy

- Updated `toString` method in `ValidationError` class to print the `extensions` field. If the field is null then an empty array will be printed `...extensions=[]`
- Removed the `message` field because it was always initialized with the description but the getMessage() method is still there and returns the content of the description
- Initialized the `extensions` and `queryPath` fields during their declaration to align with the `sourceLocations` field
- Added a couple of UTs to test the ValidationError#toString method
It resolves #3005

Update ValidationError#toString to print the extentions field 

---

build.gradle
settings.gradle
src/main/java/graphql/scalar/GraphqlStringCoercing.java
src/main/resources/i18n/Scalars.properties
src/main/resources/i18n/Scalars_de.properties
src/test/groovy/graphql/ScalarsStringTest.groovy

This PR makes String `parseValue` coercion consistent with the JS reference implementation, by only allowing String input values. Fixes #2990.
Consistent implementation of String coercion is particularly important for [String-based custom scalars](https://scalars.graphql.org/template-string.html).
Note that this is a breaking change.
`parseValue` in JS implementation: https://github.com/graphql/graphql-js/blob/main/src/type/scalars.ts#L156
----
This PR also fixes the Gradle settings to avoid redirecting to the defunct JCenter when the Gradle module metadata is not published by a plugin (in our case, the jmh plugin). https://github.com/gradle/gradle/issues/22864#issuecomment-1327978524
There was a problem with a JCenter SSL certificate expiring earlier today.

Make String parseValue coercion consistent with JS implementation & Gradle JCenter fix

---

src/main/java/graphql/i18n/I18n.java
src/test/groovy/graphql/i18n/I18nTest.groovy

This is a small improvement to see if this reduces the confusion on where a resource bundle is used
See https://stackoverflow.com/questions/13598351/loading-a-resourcebundle-within-an-osgi-bundle
This is intended for 19.x and then we will port it to master

19.x fix - use class loader on i18n

---

src/main/java/graphql/analysis/values/ValueTraverser.java
src/main/java/graphql/analysis/values/ValueVisitor.java
src/main/java/graphql/schema/GraphQLInputSchemaElement.java
src/main/java/graphql/schema/GraphQLInputType.java
src/main/java/graphql/schema/GraphQLInputValueDefinition.java
src/test/groovy/graphql/analysis/values/ValueTraverserTest.groovy

This traverser allows you to change input values - eg arguments to fields.
It is intended to be used inside DataFetchers say to allow you to change the arguments after validation
Some design choices I made
* I looked at using the traverser code (versus a hand coded visitor) but this requires a `accept()` method on objects to traverse AND it can only traverse on a single set of values.  
*  And we need two - the in memory value and the runtime input types involved
* This assumes coerced values - that is what gets passed to a DataFetcher
* This does NOT check for valid input - and it leaves alone any object values that have no corresponding fields
* earlier validation should ensure that is never the case
* This does not check for valid output - eg it would be possible to put nullable values …

Added a ValueTraverser allowing you to visit and optionally change input argument values

---

src/main/java/graphql/scalar/GraphqlBooleanCoercing.java
src/main/java/graphql/scalar/GraphqlFloatCoercing.java
src/main/java/graphql/scalar/GraphqlIntCoercing.java
src/main/resources/i18n/Scalars.properties
src/main/resources/i18n/Scalars_de.properties
src/test/groovy/graphql/ScalarsBooleanTest.groovy
src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsIntTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Aligning `parseValue` coercion to be closer to the JavaScript reference implementation https://github.com/graphql/graphql-js/blob/main/src/type/scalars.ts
Key change is that a string will no longer be accepted as an input, e.g. `"true"` is no longer accepted as a `parseValue` input for Boolean.
There is no change corresponding change for ID as coercion for ID was already aligned.
I tried to make coercion as close as possible, keeping in mind that JavaScript uses the floating point `Number` type to represent integer values.

parseValue coercion alignment for Boolean, Float, and Int

---

build.gradle

This PR upgrades ANTLR to 4.11.1, the latest version.
Note that v4.10 was a major change, and generated lexers and parsers are not backwards compatible. Not an issue for us as we always regenerate these files https://github.com/antlr/antlr4/releases/tag/4.10

Upgrade ANTLR to 4.11.1

---

src/main/resources/i18n/Parsing_de.properties
src/main/resources/i18n/Scalars_de.properties
src/main/resources/i18n/Validation_de.properties

Now that we're on Java 11 we can have UTF-8 in properties files!
This PR updates the German strings

Update German strings to use UTF-8

---

src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/test/groovy/graphql/parser/ParserOptionsTest.groovy

PR for #3061 
This change adds a new option into `ParserOptions` which is configurable by users so that we can pass it down to the underlying `MultiSourceReader` to control whether to enable `trackData` or not.

Allow users to disable MultiSourceReader trackData through ParserOptions

---

src/main/java/graphql/schema/Coercing.java

Because `Coercing` is a SPI, leaving the deprecated methods undefaulted means that people MUST implement the old methods even though they won't be called
This defaults them.  It does introduce possible confusion since no methods needs to be implemented like before however this is clear in reality - You need to implement the non deprecated methods and if you don't it will throw an exception

defaulting the deprecated methods in Coercing

---

build.gradle

Addresses issue raised in this discussion thread https://github.com/graphql-java/graphql-java/discussions/3089. Thanks @schaefa for reporting!
From https://github.com/diffplug/osgiX
> The cause of the problem is that OSGi doesn't supply the entire JRE to its bundles - it only provides the most standardized packages. This means that non-standard packages like sun.misc and sun.reflect aren't available to your bundles, even though they are in common usage.
graphql-java does not directly use anything from `sun.misc`, but it still is turning up in the `MANIFEST.MF` file generated by the plugin `biz.aQute.bnd.builder`.
This PR removes `sun.misc.*` from the Import-Package header.

Remove sun.misc.* from MANIFEST.MF

---

src/main/java/graphql/execution/instrumentation/ExecutionStrategyInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/SimpleInstrumentationContext.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/GraphQLEnumType.java

Whoops we were using javax `@Nullable` and `@Nonnull` annotations in a few places when we should have used the JetBrains equivalent annotation.
This PR fixes up and removes all usages of javax.annotation.*

Replace javax nullable annotations with JetBrains equivalent

---

build.gradle

as it is required for java.util.jar.JarFile to obtain the manfiest entry which is essential for Sling to work as discussed in #3089. This will fail to work with Sling's bundle installer as it is using JarFile to obtain the manifest and that is not found if it is not the first entry.

Ensured that the MANIFEST.MF files is the first entry in the JAR File

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerAppliedDirectivesTest.groovy
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

I think at some point the Edges to retain more information from the original schema e.g. relationship information. Ideally not in a `String`.
It's possible that future changes to the GraphQL spec could change the schema. A lot of this code relies on implicit assumptions that could be broken.
e.g. instead of saying I want to only look at union members, I have to assume that there are only union members and applied directives. Then ignore the applied directives.
```
oldEdge.getFrom().isOfType(SchemaGraph.UNION) && !oldEdge.getTo().isOfType(SchemaGraph.APPLIED_DIRECTIVE)
```
Either way, it works now.

Fix type change and directive deletion problems in schema diffing

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/extensions/ExtensionsBuilder.java
src/test/groovy/graphql/extensions/ExtensionsBuilderTest.groovy

This will be an `graphql.extensions.ExtensionsBuilder` into the graphql context if its not already present  and then used it later to build extensions on the way out of the engine

Adding ExtensionsBuilder in the graphql context by default

---

src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/exceptions/ParseCancelledTooDeepException.java
src/main/resources/i18n/Parsing.properties
src/test/groovy/graphql/parser/ParserStressTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy

This puts in a limit on how deep grammar rules can get.  
As ANLTR is a **recursive-descent parser** it will build up a call stack as it moves along.  This stack is limited and can blow up with just the wrong input.  Even if the max tokens checking is in place, it can still blow the JVM stack before the max tokens are reached.
Right now it's 500 deep as presented here.  Is this the right value?  More?? Less ??  I changed it from 1000

Preventing stack overflow exceptions via limiting the depth of the parser rules

---

build.gradle

and make sure MANIFEST.MF is the first entry in the JAR file.
Due to a class loading issue in 20.0 I am going to upgrade to 19.x in Sling Graphql Core and so I back ported the issues fixed in master.

Backported the fix to remove sun.misc

---

build.gradle
src/test/groovy/graphql/AlwaysFailsTest.groovy

Its VERY annoying to scroll through the build logs to try and find failed tests
This adds a listener so that we can print a summary at the end of the build
```
============================
These are the test failures
============================
graphql.AlwaysFailsTest.this test fails
graphql.AlwaysFailsTest.and this test always fails
============================
```
That way its easier to work out what tests have failed

Show test failures in builds

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Need to fix a bug with duplicated diff detail.

Correct diff when argument is "moved" and the type is changed

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Check for default value changes

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Follows on #3156 to fix an edge case.

Fix edge case with bad argument renamed

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
build.gradle
src/main/resources/i18n/Parsing_de.properties
src/main/resources/i18n/Scalars_de.properties
src/main/resources/i18n/Validation_de.properties

Our next release will include breaking changes, including upgrading to Java 11!
Upgrading to Java 11 makes it easier to upgrade ANTLR and enables UTF-8 strings.
Note: The 20.1 release was a feature and bugfix release, without any breaking changes. Before the 20.1 release, I had to downgrade back to Java 8 to ensure no breaking changes. See https://github.com/graphql-java/graphql-java/pull/3110

Upgrade to Java 11 (round 2)

---

src/main/java/graphql/scalar/GraphqlBooleanCoercing.java
src/main/java/graphql/scalar/GraphqlFloatCoercing.java
src/main/java/graphql/scalar/GraphqlIntCoercing.java
src/main/java/graphql/scalar/GraphqlStringCoercing.java
src/main/resources/i18n/Scalars.properties
src/main/resources/i18n/Scalars_de.properties
src/test/groovy/graphql/ScalarsBooleanTest.groovy
src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsIntTest.groovy
src/test/groovy/graphql/ScalarsStringTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Reverts stricter `parseValue` coercion for built-in scalars String #3030 and Boolean, Float, and Int #3042. 
We've received feedback that this `parseValue` breaking change is causing an issue with clients expecting the old  behaviour. Whilst this change was to align `parseValue` coercion with the JS reference implementation, we want to temporarily revert this change while we work on a better migration solution.
The stricter parseValue coercion was previously released with [GraphQL Java 20.0](https://github.com/graphql-java/graphql-java/releases/tag/v20.0).
JS implementation: https://github.com/graphql/graphql-js/blob/main/src/type/scalars.ts

Revert stricter scalar parseValue coercion

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/ValuesResolverConversion.java
src/main/java/graphql/execution/values/InputInterceptor.java
src/test/groovy/graphql/execution/values/InputInterceptorTest.groovy

This allows input values to be observed and in theory changed before being co-erced

This introduces an input interceptor

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Ok so I tried to do some 2nd or 3rd loops but there's no easy way to get like Object -> Fields -> Arguments.
So I just decided to go with the sorting option.

Sort diff edits before analysis

---

src/main/java/graphql/execution/DataFetcherResult.java
src/test/groovy/graphql/execution/DataFetcherResultTest.groovy

This PR adds a map function to DataFetcherResult (i.e. makes it a functor) to support a functional style of programming.

Add map function to DataFetcherResult 

---

src/main/java/graphql/schema/fetching/LambdaFetchingSupport.java
src/test/groovy/graphql/schema/fetching/LambdaFetchingSupportTest.groovy

This fix could not be done in the old version because it was not Java9+
Now that we are Java 11 - we can!

Adding in Java 9+ support for lookup across class loaders

---

src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironmentImpl.java
src/test/groovy/graphql/analysis/values/ValueTraverserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorDirectiveHelperTest.groovy

The current coed registry allows you to map data fetchers on GraphqlFieldsContainers - hence interfaces and object types
But this is wrong.  Interfaces never have data fetchers - only object types.
So this deprecates the old method and introduces a more specific new one

Deprecate FieldsContainer on code registry

---

src/main/java/graphql/scalar/GraphqlBooleanCoercing.java
src/main/java/graphql/scalar/GraphqlFloatCoercing.java
src/main/java/graphql/scalar/GraphqlIntCoercing.java
src/main/java/graphql/scalar/GraphqlStringCoercing.java
src/main/resources/i18n/Scalars.properties
src/main/resources/i18n/Scalars_de.properties
src/test/groovy/graphql/ScalarsBooleanTest.groovy
src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsIntTest.groovy
src/test/groovy/graphql/ScalarsStringTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Backporting revert of stricter scalar `parseValue` coercion ahead of a special release
Backport of https://github.com/graphql-java/graphql-java/pull/3186

Add backport of scalar coercion reversion PR #3186

---

src/main/java/graphql/execution/values/legacycoercing/LegacyCoercingInputInterceptor.java
src/test/groovy/graphql/execution/values/legacycoercing/LegacyCoercingInputInterceptorTest.groovy

This is super early to show my working

LegacyCoercing support

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/test/groovy/graphql/execution/AsyncTest.groovy
src/test/java/benchmark/BenchMark.java

Hello @bbakerman @andimarek 
just trying to improve the allocation rate (see the discussion in https://github.com/graphql-java/graphql-java/discussions/3175).
There are 3 commits:
- first one is to drop TracingInstrumentation from BenchMark (to better understand the numbers from the profiler);
- second one is about to allocate less CompletableFuture in the Async class;
- third one is about removing the unused `index` parameter from Async CF factory functions: this will drop the allocations of `java.lang.Integer`.
On my machine, I get the following numbers. 
Baseline:
```
Result "benchmark.BenchMark.benchMarkSimpleQueriesThroughput":
62.101 ±(99.9%) 2.006 ops/s [Average]
(min, avg, max) = (59.572, 62.101, 65.441), stdev = 1.877
CI (99.9%): [60.095, 64.108] (assumes normal distribution)
``` …

Droppinf some CompletableFuture allocations

---

src/main/java/graphql/execution/DataFetcherExceptionHandler.java
src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java
src/test/groovy/graphql/execution/SimpleDataFetcherExceptionHandlerTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy
src/test/groovy/readme/ExecutionExamples.java

This has been deprecated since 2021-06-23
This was previously a sync value and its now required to be async.  It used to default but now it will not

Removing the deprecated DataFetcherExceptionHandler sync method

---

src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStepInfoFactory.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java

hello @bbakerman @andimarek :)
another batch of small fixes... please have a look when you have time :)
D.

Minor performance fixes

---

src/main/java/graphql/execution/DataFetcherResult.java
src/main/java/graphql/normalized/ExecutableNormalizedField.java
src/main/java/graphql/schema/diffing/EditorialCostForMapping.java
src/main/java/graphql/schema/diffing/HungarianAlgorithm.java
src/main/java/graphql/schema/diffing/PossibleMappingsCalculator.java
src/main/java/graphql/schema/diffing/SchemaGraph.java
src/main/java/graphql/util/MutableRef.java
src/main/java/graphql/util/Ref.java

This is OCD fix ups.  If you compile on the terminal you gets lots of javadoc warnings.  This annoys me!

Java doc fixups and some renaming

---

build.gradle

**This PR will update the version of Guava to a patched version (32.0.0) so that security scanners do not mistakenly flag graphql-java as vulnerable. graphql-java never used the affected classes, this PR is only to make your security scanner happy.**
In graphql-java we shade selected classes from Guava. We don't actually use the affected classes in CVE-2023-2976, so this library was never vulnerable to CVE-2023-2976. However, in #3239 we received reports that security scanners have mistakenly flagged graphql-java as vulnerable because we do still include the Guava POM inside the META-INF directory of our jar. We still want to include the Guava POM in the jar, as a record of the version we shaded classes from.
Further explanation of exploit: …

Upgrade v18 to patched version of Guava

---

build.gradle

**This PR will update the version of Guava to a patched version (32.0.0) so that security scanners do not mistakenly flag graphql-java as vulnerable. graphql-java never used the affected classes, this PR is only to make your security scanner happy.**
In graphql-java we shade selected classes from Guava. We don't actually use the affected classes in CVE-2023-2976, so this library was never vulnerable to CVE-2023-2976. However, in https://github.com/graphql-java/graphql-java/issues/3239 we received reports that security scanners have mistakenly flagged graphql-java as vulnerable because we do still include the Guava POM inside the META-INF directory of our jar. We still want to include the Guava POM in the jar, as a record of the version we shaded classes from.
Further explanation of …

Update Guava version for v20

---

build.gradle

**This PR will update the version of Guava to a patched version (32.0.0) so that security scanners do not mistakenly flag graphql-java as vulnerable. graphql-java never used the affected classes, this PR is only to make your security scanner happy.**
In graphql-java we shade selected classes from Guava. We don't actually use the affected classes in CVE-2023-2976, so this library was never vulnerable to CVE-2023-2976. However, in https://github.com/graphql-java/graphql-java/issues/3239 we received reports that security scanners have mistakenly flagged graphql-java as vulnerable because we do still include the Guava POM inside the META-INF directory of our jar. We still want to include the Guava POM in the jar, as a record of the version we shaded classes from.
Further explanation of …

Update Guava version for v19

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/QueryComplexityCalculator.java
src/test/groovy/graphql/analysis/QueryComplexityCalculatorTest.groovy

Related to #3217 - but made into its own PR
This breaks out the query complexity calculator into its own class so it could be used outside the Instrumentation

Breaking out query complexity into its own class

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/execution/AbortExecutionExceptionTest.groovy

#3255 instrumentExecutionResult is now called if the AbortExecutionException is thrown early in the parse/validate phase

fixes when instrumentExecutionResult on AbortExecutionException

---

src/main/java/graphql/execution/directives/QueryDirectives.java
src/main/java/graphql/execution/directives/QueryDirectivesBuilder.java
src/test/groovy/graphql/execution/directives/QueryDirectivesImplTest.groovy

The QueryDirecivesImpl is @internal API but there is not builder to make one if used outside the engine
So this adds one

Adding builder for QueryDirectives

---

src/main/java/graphql/schema/PropertyFetchingImpl.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

This has some challenges.  I will discuss them more on the issue #3247
This PR now changes how `recordLike()` methods are looked up.  The use of `static recordLike()` is no longer supported.
I had intended to NOT make a breaking change  but after canvassing this with some others like the team at Spring GraphQL it was suggested that allowing `static recordLike()` access will present more problems in the future than benefits.
Since this is only 6 months old the scope of the breaking change is smaller than banning static `getFoo` methods say. 
So the breaking change is this - if you have a `static recordLike()` method - it will no longer be called.

static record like methods are no longer supported

---

build.gradle

Update Guava ahead of patch release
Some security scanners incorrectly flagged the older version as vulnerable https://github.com/graphql-java/graphql-java/issues/3263
Note that the graphql-java was never vulnerable. We shade in selected classes which are not related to the vulnerability. This is an update to keep security scanners happy.

20.x Guava update

---

build.gradle

Update Guava ahead of patch release
Some security scanners incorrectly flagged the older version as vulnerable https://github.com/graphql-java/graphql-java/issues/3263
Note that the graphql-java was never vulnerable. We shade in selected classes which are not related to the vulnerability. This is an update to keep security scanners happy.

19.x Guava update again

---

src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/UnicodeUtil.java
src/test/java/graphql/schema/idl/SchemaParserTest.java

This fixes a possible unwrapped NumberFormatException in src/main/java/graphql/parser/UnicodeUtil.java and src/main/java/graphql/parser/GraphqlAntlrToLanguage.java while parsing possibly malformed schema.
There are some places in the parser that require parsing numeric values from string to different numeric class types. When some of the text values contain invalid number representation, NumberFormatException are thrown. For example in [Line 672](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/parser/GraphqlAntlrToLanguage.java#L672) of GraphqlAntlrToLanguage class, the constructor call to the BigDecimal object will throw a NumberFormatException if the float value text has a long exponent which overflows the variable. This internal NumberFormatException is …

Wrap NumberFormatException

---

build.gradle

Updating guava version to 32.1.1
Some security scanners incorrectly flagged the older version as vulnerable https://github.com/graphql-java/graphql-java/issues/3263
Note that the graphql-java was never vulnerable. It shades in selected classes which are not related to the vulnerability. This is an update to keep security scanners happy.

18.x Guava Updated to 32.1.1

---

src/main/java/graphql/execution/ValuesResolverConversion.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This fixes the deprecated `defaultValue` input of null values when an AST literal is required - eg in schema printing and introspection.
see #3285

deprecated default value method produces bad results

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This PR backports null value default value bugfix https://github.com/graphql-java/graphql-java/pull/3286 to v19.
Keep in mind, back in v19 we had not yet split up ValuesResolver, so methods are in different places.

19.x backport of #3286 null default value bugfix

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/main/java/graphql/schema/diffing/ana/SchemaDifference.java

very thin change, when looking at `SchemaDifference`s one should be able to access the name of the directive for differences like `AppliedDirectiveArgumentValueModification` which currently don't give you that.
```
public AppliedDirectiveArgumentValueModification(AppliedDirectiveLocationDetail locationDetail, String argumentName, String oldValue, String newValue) {
this.locationDetail = locationDetail;
this.argumentName = argumentName;
this.oldValue = oldValue;
this.newValue = newValue;
}
```
example the `AppliedDirectiveArgumentValueModification` only has the name of the argument, and the location detail only has the name of the object type and field name, but nothing about what the name of the directive is
This is useful for lets say if you want to analyse …

add directiveName as property to AppliedDirectiveLocationDetail

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/SchemaPrinterComparatorsTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This PR addresses two schema printer items:
1. Adds deprecation reason printing to better support programmatically provided deprecation reason which is required by schema linters such as GraphQL-ESLint schema recommended rule [require-deprecation-reason](https://the-guild.dev/graphql/eslint/rules/require-deprecation-reason).
2. Fixes `@deprecated` directive missing from printed arguments.

Schema Printer - add deprecation reason printing and fix missing deprecated directive on argument

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/SimplePerformantInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy

createState() today is a sync call.  but if you had to call some remote system to get state setup then you need a CF to represent this
This PR changes create state to be a async call

Added support for async create state in instrumentmentations

---

src/test/groovy/readme/InstrumentationExamples.java

Currently, a deprecated method is still being used in InstrumentationExamples.java. This causes an NPE during the execution of `beginExecution`. Instead, use the non deprecated method in the example.

Use the non deprecated method in InstrumentationExamples.java

---

src/main/java/graphql/validation/TraversalContext.java
src/main/java/graphql/validation/ValidationContext.java
src/main/java/graphql/validation/rules/VariableTypesMatch.java
src/main/java/graphql/validation/rules/VariablesTypesMatcher.java
src/main/resources/i18n/Validation.properties
src/test/groovy/graphql/execution/ValuesResolverE2ETest.groovy
src/test/groovy/graphql/validation/rules/VariableTypesMatchTest.groovy
src/test/groovy/graphql/validation/rules/VariablesTypesMatcherTest.groovy

Backports default value bugfix #3278 to v19.
Note: back in v19.x, we didn't propagate context/locale throughout the ValuesResolver, and we didn't have German strings back then.

19.x backport of #3278 default value bugfix

---

build.gradle

Related to #3318
the guava version declared as a dependency and the guava version declared to the shadow jar plugin were different and this cause the code not to be included.  This only happened in the latest bug versions released.
I have confirmed locally that when the shadowJar task runs it includes `graphql.com.google` classes when this is in place.   `gradle check` makes shadowJar run

guava version fix for 19.x

---

src/test/groovy/graphql/execution/ExecutionStrategyErrorsTest.groovy

This adds some tests that lock in the current ExecutionStrategy error behaviors.
I am looking to do work in look at improving the ES efficiency and I want more tests to lock in todays behavior so any new code has to pass these tests (OR decide that there are not desirable behavior)

ES errors test to lock in current behavior

---

build.gradle

Exclude the `android.os` package from the Import-Package header.
Fixes https://github.com/graphql-java/graphql-java/issues/3271

Fix OSGi bundle manifest

---

src/main/java/graphql/language/SourceLocation.java
src/test/groovy/graphql/language/SourceLocationTest.groovy

I have need of this a few times inside Atlassian and so I though graphql-java should natively have it

The ability to get the source location of a schema element

---

build.gradle

Previously, the graphql-java build would always produce a new version
number based on the current date and time in local development. Because
the version number would always be different between 2 Gradle
invocations, some tasks, such as `javadoc` or `jar` could never be
cached because they depend on the version number.
With this patch, the version number will no longer include the date and
time when the Git workspace is clean, because the commit hash is
sufficient to uniquely identify the state of the workspace. This allows
the tasks that depend on the version number to be properly cached.
Previously, the cache key of the antlr task would be computed using
(among other things) the absolute paths of its input files. Because the
absolute paths were part of the cache key, the build cache …

Build cache fixes

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Non-null inputs are not going through `@oneOf` validation.
For example, the query bellow will not blow up, even though both fields under the oneOf type are being passed.
```
type Query {
search(by: SearchInput!): String
}
input SearchInput @oneOf {
name: String
id: ID
}
query myQuery {
search(by: {name: "Figaro", id: "1001"})
}
```

@oneOf handles non-null inputs

---

src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

Backports PR https://github.com/graphql-java/graphql-java/pull/3334 to 19.x, which fixed https://github.com/graphql-java/graphql-java/issues/3332. Small change to correctly unwrap a type

Backport PR #3334 to 19.x

---

src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

Backports PR #3334 to 20.x, which fixed #3332. Small change to correctly unwrap a type

Backport PR #3334 to 20.x

---

src/test/groovy/graphql/ParseAndValidateTest.groovy

Reverts graphql-java/graphql-java#2741
This PR only had a test in it. Will look into this after next release

Revert "A test to show that validation rules do not catch a mutation query to schema mismatch"

---

src/main/java/graphql/GraphQLContext.java
src/test/groovy/graphql/GraphQLContextTest.groovy

This will solve https://github.com/graphql-java/graphql-java/issues/3363

Add 'compute' family of methods to GraphQLContext

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/ValuesResolverOneOfValidation.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Update: This PR adds handling of arguments with a list of `@oneOf` input objects
Fixes https://github.com/graphql-java/graphql-java/issues/3366
Confirmed that graphql-js validates elements of a list

Handle list of @oneOf input objects

---

.github/workflows/stale-pr-issue.yml

Add a GitHub action to automatically comment on open PRs and issues, to help the maintainers close out older items.
Both PRs and issues will be closed after 90 days of inactivity.
This GitHub action runs once per day.
Based off Gradle's config https://github.com/gradle/gradle/blob/master/.github/workflows/stale-issue.yml

Add GitHub action to manage stale PRs and issues

---

.github/workflows/stale-pr-issue.yml

Tag PRs and issues as `keep-open` if you want to prevent the Stale Bot from closing what you're already working on
Note, any issues or PRs with a milestone label are also exempted from the Stale Bot.

Add tag to exempt PRs and issues from the stale bot

---

src/test/groovy/readme/ScalarExamples.java

Fix up our documentation to use current scalar coercion methods. This PR checks in the updated example into this repo.
Documentation PR: https://github.com/graphql-java/graphql-java-page/pull/146
This closes #3347 and #3277.

Update deprecated methods in scalar coercion documentation example

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/ConditionalNodesTest.groovy

This PR fixes issue #3409. As @dfa1 wrote, when evaluating nodes at least 1 level lower than the top level field, the GraphQLContext is for some reason wiped out, which means a custom ConditionalNodesDecision is not applied.
The problem was the GraphQLContext was there when evaluating whether a top level field should be included, but any fields below top level is evaluated for inclusion when completing values. In this separate method, the GraphQLContext was not propagated in the parameters.
In case you're wondering, this bug did not affect `@include`/`@skip`, it only affected decisions stored in `GraphQLContext`.

Propagate GraphQLContext when completing fields - fix missing ConditionalNodesDecision issue

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

We spotted a problem where the local Maven publish task fails on Gradle 8.5 and later. Something has changed with the signing plugin.
When running the publish locally task excluding signing on Gradle 8.5:
```
./gradlew publishToMavenLocal  -x signGraphqlJavaPublication
```
We got an invalid publication error
```
Invalid publication 'graphqlJava': artifact file does not exist: 'src/graphql-java/build/libs/graphql-java-0.0.0-defer-execution-2024-SNAPSHOT-sources.jar.asc'
```
It's a strange error because by skipping signing, we intentionally don't want this file there.
This PR fixes the problem by updating the signing task to only run when we're publishing (in other words, not a local SNAPSHOT version).
While I'm here I upgraded to Gradle 8.6. There are no accompanying gradlew etc file …

Skip signing for local and upgrade to Gradle 8.6

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/GraphQLTest.groovy

👋  While migrating from v18 to v21.3, I noticed there was a regression where instrumentations would have `createState` called without an executionId.
I think this might have been introduced in ce83384b7ae682cc1eb099c10ef87e8a0daa938f. I added a fix and a test.

ensure that instrumentations get an executionid

---

src/main/java/graphql/GraphQLError.java
src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/parser/ParserTest.groovy

Add escape characters where appropriate to AST printer for single line descriptions.
When parsing single line descriptions, escape characters are converted to their Java string equivalent. See `parseSingleQuotedString` inside `StringValueParsing`. https://github.com/graphql-java/graphql-java/blob/97ba988eabd74657f5455e9d32867c5170b0dffe/src/main/java/graphql/parser/StringValueParsing.java#L107
However, when we printed single line descriptions, we did not do the reverse and put the escape characters back into the printed output. Without the correct escape characters, it is possible to print invalid GraphQL (see #3229).
I'll add more test cases. Currently only has a test for case described in the original issue

Fix invalid AST printer: add escape characters to single line descriptions

---

src/test/groovy/graphql/execution/incremental/DeferExecutionSupportIntegrationTest.groovy

The order of incremental data in the scenario being tested was non-deterministic, so the test needed a few adjustments

Fix flaky defer test

---

src/main/java/graphql/execution/instrumentation/fieldvalidation/SimpleFieldValidation.java

The validateFields method in SimpleFieldValidation would iterate over the keySet of the rules Map and then subsequently use the key to look up the value; switch to iterating over the entrySet.

Avoid repeated Map lookups in SimpleFieldValidation

---

src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/language/PrettyAstPrinter.java
src/main/java/graphql/schema/GraphQLTypeUtil.java
src/main/java/graphql/schema/idl/TypeUtil.java

Change some places to use simple String concatenation instead of a StringBuilder, since JDK9+ has additional optimizations added as part of JEP280. Additionally, switch to the StringJoiner class and String.isBlank method in a few places.

Use String concatenation instead of StringBuilder

---

src/test/java/benchmark/AsyncBenchmark.java

This is the starting values before any changes to Async
```
Benchmark                      (num)   Mode  Cnt          Score          Error  Units
AsyncBenchmark.benchmarkAsync      0  thrpt   10  191428179.886 ± 33928842.671  ops/s
AsyncBenchmark.benchmarkAsync      1  thrpt   10   73586748.484 ± 12938517.205  ops/s
AsyncBenchmark.benchmarkAsync     10  thrpt   10    7167776.511 ±  1977327.653  ops/s
```

Added Async benchmark for future changes

---

src/main/java/graphql/execution/DataLoaderDispatchStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/dataloader/PerLevelDataLoaderDispatchStrategy.java

The use of CF is problematic for me and the BatchLoading work does an instance of anyway so this will work

Using object instead of CF in DispatcherStrategy interface

---

src/test/java/benchmark/ComplexQueryBenchmark.java

Now allows the benchmark to go into profiling mode

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/FieldCollector.java
src/main/java/graphql/execution/FieldValueInfo.java
src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/execution/MergedSelectionSet.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/test/java/benchmark/TwitterBenchmark.java

Avoid additional calls to `getFieldDef` in `ExecutionStrategy` and avoid immutable builder/collections where they're unnecessary  on hot paths.
This improves the throughput of `TwitterBenchmark` by about 15%:
```
Benchmark                  Mode  Cnt    Score   Error  Units
TwitterBenchmark.execute  thrpt   10  105.571 ± 0.367  ops/s
```
```
Benchmark                  Mode  Cnt    Score   Error  Units
TwitterBenchmark.execute  thrpt   10  123.840 ± 1.492  ops/s
```

Avoid repeated calls to getFieldDef and unnecessary immutable builders/collections

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/execution/FieldValueInfo.java
src/test/groovy/graphql/execution/FieldValueInfoTest.groovy

FetchValue and FieldValueInfo are data classes that are needed to hold state about what has been fetched and what has been completed as objects.
Currently they use the code best practice of a builder however this induces memory pressure - we create a FetchValue.Builder object only to turn it immediately into a FetchValue object.
In the name of performance and reduced memory pressure, lets just have a direct constructor.
While builder pattern is nicer for future extension, lets trade off code maintenance for performance here.
Also these probably should not have been public API say - but here we are

Don't build a builder object and then turn it into the actual object

---

src/main/java/graphql/execution/ExecutionStrategyParameters.java

related to https://github.com/graphql-java/graphql-java/issues/3483
This is more memory efficient because the builder default is not thrown away

Does not allocate a default deferred context that is thrown away on transform

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/execution/FieldValueInfo.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/ExecuteObjectInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/ExecutionStrategyInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/InstrumentationContext.java
src/main/java/graphql/execution/instrumentation/SimpleInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/adapters/ExecuteObjectInstrumentationContextAdapter.java
src/main/java/graphql/execution/instrumentation/adapters/ExecutionResultInstrumentationContextAdapter.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/util/FieldNameInterner.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentContext.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/util/AnonymizerTest.groovy

Quick follow up from https://github.com/graphql-java/graphql-java/pull/3478 to intern field names which allows object identity equality checks for `String.equals` and when looking up field definitions by name. Benchmark result here:
https://github.com/graphql-java/graphql-java/pull/3478#issuecomment-1972649516

Intern field names

---

src/main/java/graphql/language/Field.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/util/FieldNameInterner.java

I buggered this up before - I hope this works

recreating the netflix Intern field names PR

---

src/test/java/benchmark/MapBenchmark.java

```
Benchmark                            (numberEntries)   Mode  Cnt      Score      Error  Units
MapBenchmark.benchmarkHashMap                     10  thrpt    9  37700.894 ± 2787.234  ops/s
MapBenchmark.benchmarkLinkedHashMap               10  thrpt    9  39472.657 ± 1956.803  ops/s
MapBenchmark.benchmarkImmutableMap                10  thrpt    9  32952.299 ±  635.821  ops/s
MapBenchmark.benchmarkHashMap                     50  thrpt    9  31896.433 ± 1771.747  ops/s
MapBenchmark.benchmarkLinkedHashMap               50  thrpt    9  31721.675 ± 1316.887  ops/s
MapBenchmark.benchmarkImmutableMap                50  thrpt    9  30112.771 ±  877.851  ops/s
MapBenchmark.benchmarkHashMap                    300  thrpt    9  23714.696 ± 1719.088  ops/s
MapBenchmark.benchmarkLinkedHashMap …
```

Map benchmarks

---

src/test/java/benchmark/CompletableFuturesBenchmark.java

This bench mark makes a tree of objects and then traverses that tree if objects.
10 objects per level of either 2 or 5 in depth
One approach is that all objects are completed CFs to objects and the other approach is just a list of materialized objects.
We would always expect materialised object creation and traversal to be faster - but how much faster.
Well that is what this benchmark tried to find out
```
Benchmark                                                  (depth)   Mode  Cnt      Score      Error  Units
CompletableFuturesBenchmark.benchmarkCFApproach                  2  thrpt    3  27343.594 ± 3539.780  ops/s
CompletableFuturesBenchmark.benchmarkCFApproach                  5  thrpt    3     41.339 ±    9.774  ops/s
CompletableFuturesBenchmark.benchmarkMaterializedApproach …
```

A CompleteableFuture benchmark

---

src/main/java/graphql/validation/rules/SubscriptionUniqueRootField.java
src/test/groovy/graphql/validation/rules/SubscriptionUniqueRootFieldTest.groovy

Changing SubscriptionUniqueRootField validation in order to also check inline fragments and multiple fragments
Fix for: https://github.com/graphql-java/graphql-java/issues/3425

SubscriptionUniqueRootField validation to check multiple fragments - Validation Bug fix 

---

src/main/java/graphql/DirectivesUtil.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLUnionType.java

This PR is aimed at memory performance - every schema element that has zero directives gets the same empty object as a value.
Current memory dumps of large schemas show repeated instances of these empty holders

Return empty singleton DirectivesHolder if directives are empty

---

src/main/java/graphql/ErrorType.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionDisabledError.java
src/main/java/graphql/schema/visibility/NoIntrospectionGraphqlFieldVisibility.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy

This adds the ability to disable Introspection - either JVM wide (eg always) or per request via  a well know context key
NoIntrospectionGraphqlFieldVisibility is another way to do this but it does not allow dynamic on or off and it makes the schema invalid according to spec. 
This stops the execution hard at the `__schema` and `__type` field level.

This provides and ability to disable Introspection

---

src/main/java/graphql/ErrorClassification.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionDisabledError.java
src/main/java/graphql/schema/visibility/NoIntrospectionGraphqlFieldVisibility.java
src/test/groovy/graphql/introspection/GoodFaithIntrospectionInstrumentationTest.groovy
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Backport of https://github.com/graphql-java/graphql-java/pull/3526 and PR https://github.com/graphql-java/graphql-java/pull/3527 - pulls in introspection disabling and Good Faith Introspection
Remember we're back in the stone age with Java 8, small adjustments for this

19.x Backport #3526 and PR #3527 

---

build.gradle
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionDisabledError.java
src/main/java/graphql/schema/visibility/NoIntrospectionGraphqlFieldVisibility.java
src/test/groovy/graphql/introspection/GoodFaithIntrospectionInstrumentationTest.groovy
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Backport of PR #3526 and PR #3527 which enables introspection to be disabled
Note: version 20 takes us back to the stone age with Java 8

20.x Backport of PR 3526 and PR 3527

---

src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionDisabledError.java
src/main/java/graphql/schema/visibility/NoIntrospectionGraphqlFieldVisibility.java
src/test/groovy/graphql/introspection/GoodFaithIntrospectionInstrumentationTest.groovy
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Backport of #3526 and PR #3527 - pulls in introspection disabling and Good Faith Introspection
Double check me please, execution has gone through a renovation with the forthcoming defer feature

21.x Backport PR 3526 and PR 3527

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/execution/FieldValueInfo.java
src/main/java/graphql/execution/ResultNodesInfo.java
src/test/groovy/graphql/GraphQLTest.groovy

This backports PR #3525 
Minor adjustment compared to latest master, we must use `ExecutionResult` wrapping of results

20.x Backport max result nodes PR 3525

---

src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/normalized/ExecutableNormalizedOperation.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/InterfacesImplementingInterfacesTest.groovy
src/test/groovy/graphql/UnionTest.groovy
src/test/groovy/graphql/introspection/GoodFaithIntrospectionInstrumentationTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/java/benchmark/ENFBenchmarkDeepIntrospection.java

This adds the ability to short cut ENF creation when a maximum number of nodes has been reached 
It also captures the node count in the result object as well as the maximum depth seen.
The good faith introspection now uses this to more quickly check if the introspection query is in good faith in terms of how many ENF nodes it will create

Restrict the number of ENFs created and take advantage in GoodFaith introspection

---

src/main/java/graphql/ExecutionInput.java
src/test/groovy/graphql/ExecutionInputTest.groovy

> - Richard III by William Shakespeare

Removed deprecated methods in ExecutionInput

---

src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/normalized/ExecutableNormalizedOperation.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/InterfacesImplementingInterfacesTest.groovy
src/test/groovy/graphql/UnionTest.groovy
src/test/groovy/graphql/introspection/GoodFaithIntrospectionInstrumentationTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/java/benchmark/BenchmarkUtils.java
src/test/java/benchmark/ENFBenchmarkDeepIntrospection.java

Backporting #3539 for 21.x. The difficulty is that there were major changes in `ExecutableNormalizedOperationFactory` in preparation for the new defer feature in v22.
The changes in PR #3539 are harder and riskier to pull into the old `ExecutableNormalizedOperationFactory` structure. I propose it is safer to update 21.x (and prior versions) to the new file structure
I want to have another close look at this PR with fresh eyes because this is a complicated cherry pick. Here's an early look and we'll get the build going

21.x backport of #3539 ENF restriction for introspection

---

src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/test/groovy/graphql/introspection/GoodFaithIntrospectionTest.groovy

Catch abort execution exceptions and turn them into proper errors.

Improve Good faith introspection error handling

---

src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy

The ENOF should have a default max nodes, which is high, but still prevents a to large memory creation

add a default max nodes count for the ExecutableNormalizedFactory 

---

src/main/java/graphql/schema/GraphQLDirective.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/GraphQLArgumentTest.groovy
src/test/groovy/graphql/schema/GraphQLDirectiveTest.groovy
src/test/groovy/graphql/schema/GraphQLEnumValueDefinitionTest.groovy
src/test/groovy/graphql/schema/GraphQLFieldDefinitionTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectFieldTest.groovy
src/test/groovy/graphql/schema/GraphQLScalarTypeTest.groovy
src/test/groovy/graphql/schema/SchemaTraverserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/validation/rules/KnownArgumentNamesTest.groovy
src/test/groovy/graphql/validation/rules/ProvidedNonNullArgumentsTest.groovy

It's possible to programmatically create a `GraphQLDirective` without setting it's valid locations. These missing locations are not validated at schema creation time either, allowing the schema without directive locations to be rendered with`SchemaPrinter`, producing SDL like:
```
directive @foo on
directive @bar on
```
Trying to reparse this rendered sdl fails with an InvalidSyntaxError.
This PR addresses this by requiring that at the time that a `GraphQLDirective` is created, it must have a non-empty set of locations configured. This is similar to existing validations for name and arguments. As a result of this new requirement, I had to update a number of tests that create directives without locations.
There are 2 spec-related aspects to this:
1. Does the spec actually require a …

require non-empty directive locations

---

src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/SimplePerformantInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy

I have had revisionist thoughts on removing createState - while its not strictly needed - it breaks people without enough reward
So I have restored it and said its not deprecated

Putting createState back into Instrumentation

---

src/main/java/graphql/incremental/DelayedIncrementalPartialResultImpl.java
src/test/groovy/graphql/incremental/IncrementalExecutionResultTest.groovy

it looks like there was a copy-paste error for this one function (copied from the hasNext part of the builder).
This change is to fix the function to allow us to properly add "extensions" to the builder. Similar to this one [here](https://github.com/graphql-java/graphql-java/blob/e01013f65f4554643e8b7c3df5143438fc5d414a/src/main/java/graphql/incremental/IncrementalPayload.java#L135C1-L138C10)
have also added a test for this builder

fix incremental partial result builder

---

src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/TypeRuntimeWiring.java
src/main/java/graphql/schema/idl/errors/StrictModeWiringException.java
src/test/groovy/graphql/schema/idl/RuntimeWiringTest.groovy
src/test/groovy/graphql/schema/idl/TypeRuntimeWiringTest.groovy

Alexandre the Great asked for a strict mode when wiring the runtime

strictMode for RuntimeWiring and TypeRuntimeWiring

---

src/main/java/graphql/schema/validation/DeprecatedInputObjectAndArgumentsAreValid.java
src/main/java/graphql/schema/validation/SchemaValidationErrorType.java
src/main/java/graphql/schema/validation/SchemaValidator.java
src/test/groovy/graphql/schema/validation/DeprecatedInputObjectAndArgumentsAreValidTest.groovy
src/test/groovy/graphql/schema/validation/SchemaValidatorTest.groovy

Fixes #3590
From the [GraphQL specification](https://spec.graphql.org/draft/#sec--deprecated):
> The @deprecated directive must not appear on required (non-null without a default) arguments or input object field definitions.
This PR adds the schema validation rule to enforce this line of the spec.

Ready: Add @deprecated validation for input object fields, field arguments, directive arguments

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/FieldFetchingInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/NoContextChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/SimplePerformantInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/ModernTestingInstrumentation.groovy
src/test/groovy/graphql/execution/instrumentation/TestingFieldFetchingInstrumentationContext.groovy

When we changed InstrumentationContext to no longer take a CF as an argument, the callback to `beginFieldFetch` can no long know about the value that was fetched.
Expedia for example used to this know if the value was a SYNC or ASYNC value for this dispatch code.
This adds a new method with a new context class that can be called back with the object that was fetched (it might not be complete if its a CF say)
The default implementation calls back to the old method so that we dont break any one.  But should it?  v22 is only a few days old - if v22.1 was also breaking for this - the impact would be low - no zero but very low

Added field fetching method for Expedia

---

src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java
src/test/groovy/graphql/schema/DelegatingDataFetchingEnvironmentTest.groovy

While using Netflix' DGS with Kotlin, we ran into an issue where it was not immediately clear that `DataFetchingEnvironment.getLocalContext` can return `null`. After reading the documentation and the rest of the `DataFetchingEnvironment` interface, I noticed the lack of nullability annotations for Kotlin interoperability. However, I also saw that other classes in this project already use the Jetbrains annotations. 
In this PR I added nullability annotations to all methods of the `DataFetchingEnvironment` interface that had mentions about nullability in their documentation. For patching the whole class I currently lack the overview of the bigger picture of this interface.
I followed through on sub-classes that override these methods.

Add nullability annotations in DataFetchingEnvironment & sub-classes

---

src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/idl/TypeRuntimeWiring.java
src/test/groovy/graphql/schema/idl/RuntimeWiringTest.groovy

See #3431 for more detail on the problem fixed

Now does not overwrite a types default data fetcher unless its nonnull

---

src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java
src/main/java/graphql/schema/idl/errors/DirectiveIllegalArgumentTypeError.java
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

When validating directive arguments that use nested list types, it looks like the validator does not allow nulls to be used in valid positions.
For example, given a type like `[[String!]]`, it rejects the value `[null]`.
After looking into this, it looks like #2001 added support for coercing singleton items into lists, but didn't handle null values. The relevant part of the spec is this:
> If the value passed as an input to a list type is not a list *and not the null value*, then the result of input coercion is a list of size one.
This PR changes scalar-to-list coercion to allow null values in nested lists. A side effect of this is that the validation error `Argument value is X', expected a list value.` will never be raised.

nested nullable list validation bugfix

---

src/main/java/graphql/incremental/IncrementalExecutionResultImpl.java
src/test/groovy/graphql/incremental/IncrementalExecutionResultTest.groovy

Adding two missed properties on IncrementalExecutionResultImpl.Builder.from

Adding missed properties on IncrementalExecutionResultImpl.Builder.from

---

src/main/java/graphql/validation/ArgumentValidationUtil.java
src/main/java/graphql/validation/ValidationUtil.java
src/main/resources/i18n/Validation.properties
src/test/groovy/graphql/schema/GraphQLInputObjectTypeTest.groovy
src/test/groovy/graphql/validation/ValidationUtilTest.groovy
src/test/groovy/graphql/validation/rules/ArgumentsOfCorrectTypeTest.groovy

Note this is only when the AST literals are present - pure variables are handled later still just like in JS
https://github.com/graphql-java/graphql-java/issues/3572
so `f(arg : { a : "x", b: $y})` will be handled but not `f(arg:$variable)` which uses the existing code and still is lazy at this stage
re: https://github.com/graphql-java/graphql-java/issues/3572

This provides validation on @oneof input types during validation phase

---

src/main/java/graphql/execution/ValuesResolverConversion.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectTypeTest.groovy

This will call the oneOf validation during the coercion of the variables during execution.
This MAY make the later validation during argument retrieval slightly redundant however there are other paths that can enter this value code so I have left it in place
This PR plus https://github.com/graphql-java/graphql-java/pull/3577 will mean variables and literals are covered

This will validate @oneOf variable values when the variables are coerced

---

.github/workflows/stale-pr-issue.yml

Our stale bot stopped working because of a cache problem. See reports of the same issue by others: https://github.com/actions/stale/issues/1133
This permission set will fix the cache issue.

Fix stale bot cache problem

---

src/main/java/graphql/parser/ExtendedBailStrategy.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/exceptions/MoreTokensSyntaxException.java
src/main/resources/i18n/Parsing.properties
src/main/resources/i18n/Parsing_de.properties
src/main/resources/i18n/Parsing_nl.properties
src/test/groovy/graphql/parser/ParserOptionsTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy

Addresses #3617 
Adds an option to redact the token from parser error messages. Note that the default behaviour will be the same as before, by default error messages provide token information if available, to assist with debugging.
There are three parsing messages to be redacted:
* `InvalidSyntax.full`
* `InvalidSyntaxBail.full`
* `InvalidSyntaxMoreTokens.full`

Add option to redact token details from parser error messages

---

src/main/java/graphql/execution/FetchedValue.java

This got missed in the v22 reshuffle

Make FetchedValue a public constructor

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy

In the latest version of the [spec](https://spec.graphql.org/draft/#ObjectTypeDefinition), empty types (input objects, object types) must be represented without curly braces, i.e the following is valid:
```graphql
type Query 
extend type Query {
foo: String
}
```
while the following technically isn't (note the `{}`):
```graphql
type Query {}
extend type Query {
foo: String
}
```
Because of historical reasons, `graphql-java` supports parsing of both syntaxes. However its `AstPrinter` prints the spec invalid form. While this is ok in systems where `graphql-java`'s GraphQL parser is the only one in use, it fails in poly-parser systems where stricter (albeit spec-compliant) parsers might fail to parse `graphql-java` printed SDL output.
This PR updates the `AstPrinter` to be spec-compliant, …

AstPrinter: Empty types should not include braces `{}`

---

src/main/java/graphql/execution/incremental/IncrementalCallState.java
src/main/java/graphql/incremental/IncrementalExecutionResult.java
src/test/groovy/graphql/execution/incremental/DeferExecutionSupportIntegrationTest.groovy
src/test/groovy/graphql/execution/incremental/IncrementalCallStateDeferTest.groovy

POC - this should be what we are doding on defer to only start the publisher work on subscribe happening

Start draining deferred results on subscription

---

src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/execution/incremental/DeferredExecution.java
src/main/java/graphql/incremental/DeferPayload.java
src/main/java/graphql/incremental/DelayedIncrementalPartialResult.java
src/main/java/graphql/incremental/IncrementalExecutionResult.java
src/main/java/graphql/incremental/IncrementalExecutionResultImpl.java
src/main/java/graphql/incremental/IncrementalPayload.java
src/main/java/graphql/incremental/StreamPayload.java
src/main/java/graphql/normalized/incremental/NormalizedDeferredExecution.java
src/test/java/reproductions/SubscriptionReproduction.java

Let's only use the JetBrains nullability annotations, rather than a mix of JetBrains and javax annotations.

Only use JetBrains nullability annotations

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/main/java/graphql/analysis/QueryTransformer.java
src/main/java/graphql/analysis/QueryTraversalOptions.java
src/main/java/graphql/analysis/QueryTraverser.java
src/test/groovy/graphql/analysis/QueryTransformerTest.groovy
src/test/groovy/graphql/analysis/QueryTraversalOptionsTest.groovy
src/test/groovy/graphql/analysis/QueryTraverserTest.groovy

The default is the old behaviour of coercing by default
But this can turned off via options
I used an options class so we can extend with further options in the future.

This introduces a Traversal Options to allow skipping the coercing of field arguments

---

src/main/java/graphql/language/OperationDefinition.java

Thanks to @gnawf for finding this! `OperationDefinition` has a `getName` method but it was missing the `NamedNode` interface.
I double checked everything else inside `graphql.language`, this is the only class that was missing `NamedNode`.

Add missing NamedNode interface to OperationDefinition

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/execution/NonNullableFieldValidator.java
src/main/java/graphql/execution/incremental/DeferredCallContext.java
src/test/groovy/graphql/execution/NonNullableFieldValidatorTest.groovy
src/test/groovy/graphql/execution/incremental/DeferExecutionSupportIntegrationTest.groovy

Improvements in the error handling for deferred code.
- fixes bug where errors added by data fetchers that returned `DataFetcherResult` where not being added to deferred payloads
- Errors generated during the execution of deferred fields are kept in the correspondent `DeferredCallContext` only, no longer being duplicated in `ExecutionContext`

Fix bug with error handling in the defer execution code

---

src/main/java/graphql/parser/MultiSourceReader.java

This is a fix for https://github.com/graphql-java/graphql-java/issues/2709
`LineNumberReader` was updated in Java 16 to consider EOS a line terminator, so if a source doesn't end in newline, `getLineNumber()` will return 1 + the value in older Java versions. We ran into this issue at Airbnb where we use `MultiSourceReader` to read graphqls files. If a schema file didn't end in newline, the `SourceLocation` for some types would be incorrect. This PR attempts to address this issue.
Testing:
I ran the unit tests with Java 11 and Java 20 (this required bumping the language version in build.gradle) with and without this fix. Without this fix, `LineNumberingTest`, `MultiSourceReaderTest`, `ParserExceptionTest`, `TypeDefinitionRegistryTest` fail with Java 20 as described in the open issue. With …

Fix MultiSourceReader compatibility with Java 16+

---

src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherTest.groovy

Fixes #3662 
The ExecutionContextBuilder was not copying the DataLoaderDispatchStrategy and this gets "transformed" during subscription execution.  This caused it to fallback to the default NOOP implementation which is wrong.
The integration test was written first - it hung the dataloader as described in the bug and then with this fix applied it works.  TDD!

3662 - fixes dataloader dispatching during subscriptions

---

src/main/java/graphql/Directives.java

Adds DirectiveDefinitions that were missing on built-in directives `@skip`, `@include`, and`@defer`
We didn't previously have any tests for DirectiveDefinitions and I can see why, it's a definition rather than logic. But if you want tests I can add them.

Add missing directive definitions

---

src/main/java/graphql/incremental/IncrementalExecutionResultImpl.java
src/test/groovy/graphql/incremental/IncrementalExecutionResultTest.groovy

Calling `IncrementalExecutionResult.transform` will return an `ExecutionResultImpl` (rather than another `IncrementalExecutionResult`), which can cause incremental parts of the execution result to get lost.
This makes it difficult to add `@defer` support to a system with existing instrumentations, which might modify an ExecutionResult without knowing that it needs to be handled differently if it is incremental.
This PR overrides the implementation of `IncrementalExecutionResult.transform` to ensure that the transformed result retains its incremental nature.

transformable IncrementalExecutionResult

---

src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/util/EscapeUtil.java

Avoid the overhead of allocating unnecessary intermediate String instances in AstPrinter by only appending to the supplied StringBuilder. When running the AstPrinterBenchmark with the gc profiler, this significantly reduces the allocation rate:
before:
gc.alloc.rate:      4846.634 MB/sec
gc.alloc.rate.norm: 86960.001 B/op
after:
gc.alloc.rate:      2524.634 MB/sec
gc.alloc.rate.norm: 10432.000 B/op
The benchmarks also show a doubling in throughput.

Avoid unnecessary String allocations in AstPrinter

---

src/main/java/graphql/GraphqlErrorBuilder.java
src/test/groovy/graphql/GraphqlErrorBuilderTest.groovy

We have a great many tests that verify that the errors emitted from a `DataFetcher` fit a certain shape.
However, verifying equality of these errors is fiddly and error-prone, as we must directly check each individual attribute on every error - this is painful especially when we are trying to perform assertions on a `List` of `GraphQLError`s.
To this end, we add `#equals` / `#hashCode` methods on `GraphqlErrorImpl`. However, it is important to note that `equals` will return `true` if all the attributes match, even if the implementing class is _not_ a `GraphqlErrorImpl`. This is done so that different implementations may be swapped in and out with causing test failures.

Implement equals/hashCode for GraphqlErrorImpl

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
src/test/groovy/graphql/schema/DataFetcherFactoriesTest.groovy

Trying out this GitHub Action to help highlight which tests are failing in a PR or master build, because it's getting hard to read which test failed in plain text output with thousands of tests
GitHub Action source repo: https://github.com/EnricoMi/publish-unit-test-result-action

Add test result comment bot

---

src/main/java/graphql/schema/DataFetcherFactories.java
src/main/java/graphql/schema/DataFetcherFactory.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/PropertyDataFetcher.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/schema/DataFetcherFactoriesTest.groovy

If the code registry DFF value is the default then there is no need for a map entry since the lookup will default to the default

SchemaGeneratorHelper that does NOT put in an entry for defaulted values

---

src/main/java/graphql/schema/DataFetcherFactories.java
src/main/java/graphql/schema/DataFetcherFactory.java
src/main/java/graphql/schema/DataFetcherFactoryEnvironment.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/PropertyDataFetcher.java
src/main/java/graphql/schema/idl/MockedWiringFactory.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/DataFetcherTest.groovy
src/test/groovy/graphql/LargeSchemaDataFetcherTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/schema/DataFetcherFactoriesTest.groovy
src/test/groovy/graphql/schema/GraphQLCodeRegistryTest.groovy
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/TestLiveMockedWiringFactory.groovy
src/test/groovy/graphql/schema/idl/TestMockedWiringFactory.groovy

This adds support for a singleton property data fetcher
Before we create a `new PropertyDataFetcher()` for every defaulted field in the schema.  
This means for large schemas with 1000s of fields, we have a new object per field that ALWAYS fetches values with the name of the field. 
This can be static and hence we can save memory by default since MOST fields can use this static fetcher

Singleton property data fetcher

---

src/main/java/graphql/GraphqlErrorHelper.java
src/test/groovy/graphql/GraphQLErrorTest.groovy

Fixes https://github.com/graphql-java/graphql-java/issues/3661
Internally graphql-java represents an "empty" `SourceLocation` as line -1 and column -1. 
https://github.com/graphql-java/graphql-java/blob/ee32161909b10a80659aa5d8e7495f07519026d1/src/main/java/graphql/parser/ExtendedBailStrategy.java#L72
However in the issue raised it turns out the specification requires these numbers to be positive integers, starting at 1. https://spec.graphql.org/draft/#sel-GAPHRPFCCaCGX5zM
This PR updates the toSpecification method to filter out error locations that do not have both a positive line and column number. This only changes `toSpecification` and not any internal representation of SourceLocation.
This could be considered a breaking change, however it's necessary to bring behaviour in line with …

Filter out negative line and column error locations in toSpecification

---

src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/DataLoaderDispatchStrategy.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/instrumentation/dataloader/FallbackDataLoaderDispatchStrategy.java
src/main/java/graphql/execution/instrumentation/dataloader/PerLevelDataLoaderDispatchStrategy.java
src/main/java/graphql/execution/instrumentation/dataloader/PerLevelDataLoaderDispatchStrategyWithDeferAlwaysDispatch.java
src/test/groovy/graphql/MutationTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherTest.groovy

ThisPR for the https://github.com/graphql-java/graphql-java/issues/3711 issue where mutations dont allow DataLoader delayed dispatching (rather it dispatches ALWAYS)
Mutations run in serial and hence dispatch one field at a time.  However the data loader dispatching code previoiusly assumed that all of the mutation top level fields would be dispatched at once and hence it waited for all to be dispatched before it dispatched the dataloaders.
This changes that so that it expects one field at a time and it resets the tracing callstack per mutation field

DataLoader on Mutations and Queries

---

src/main/java/graphql/DuckTyped.java
src/main/java/graphql/Internal.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/reactive/ReactiveSupport.java
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/pubsub/CountingFlux.groovy
src/test/groovy/graphql/execution/reactive/ReactiveSupportTest.groovy

This adds support for Reactive Publishers, both reactive streams Publishers and JDK Flow Publishers, to be returned from a `DataFetcher` as a value.
They will be turned into `CompletableFuture` by using a subscriber to ask for one value from them.
This is a lot like how reactor `Mono` has a `.toFuture()` method except now they can just return the Mono itself, since a Mono is a reactive streams Publisher.
The cost of this is 2 more `instanceof` checks like we already for for `CompleteableFuture`s

Added support for reactive Publishers to be returned from data fetchers

---

src/main/java/graphql/execution/ResultPath.java
src/test/groovy/graphql/execution/ResultPathTest.groovy

This pull request adds a more robust validation to the `ResultPath.fromList` method. As you can pass any object to `GraphqlErrorException.Builder.path`, it can lead to a ClassCastException when casting directly to `int`.  this happened to me lol.
```java
public T path(List<Object> path) {
this.path = path;
return (T)this.asDerivedType();
}
```
> GraphqlErrorException.Builder.path

ResultPath: Check object type before casting to int

---

src/main/java/graphql/incremental/DeferPayload.java
src/main/java/graphql/incremental/IncrementalPayload.java
src/main/java/graphql/incremental/StreamPayload.java
src/test/groovy/graphql/incremental/DeferPayloadTest.groovy
src/test/groovy/graphql/incremental/StreamPayloadTest.groovy

Closes #3704 
Adding these handy methods to help cut down lines of code in tests

Adding hashcode and equals for defer & stream payloads

---

src/test/groovy/readme/ExecutionExamples.java

We've had a few questions about how to use the input interceptor, so I've added it to the documentation. https://github.com/graphql-java/graphql-java-page/pull/186
In this PR, I'm checking in the examples used

Add InputInterceptor example

---

src/test/groovy/readme/DirectivesExamples.java

Checking in example from graphql-java-page documentation update https://github.com/graphql-java/graphql-java-page/pull/185
Our documentation only explained schema (SDL) directives, but we didn't yet have a section on query/operation directives. This gave the wrong impression that GraphQL Java didn't support query/operation directives.
See previous GitHub discussion threads: https://github.com/graphql-java/graphql-java/discussions/3311

Add query directive documentation example

---

README.md
README.zh_cn.md
src/test/groovy/readme/DataFetchingExamples.java
src/test/groovy/readme/DirectivesExamples.java

Closes #3678 
We should be only referencing `GraphQLContext` rather than `Context` in the documentation
See the documentation changes in https://github.com/graphql-java/graphql-java-page/pull/184/files
This PR checks in the examples into this repo

Update documentation examples to remove deprecated context method

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

Fixes #3786 
With the schema transformer, it's possible to update the deprecated reason stored on a field definition.
@t2gran reported that the schema printer wasn't printing out the correct deprecated reason when it had been changed by a schema transformer. See #3786 and test in this gist: https://gist.github.com/t2gran/69b149357477870ba25e00375a2626a2. The bug was happening on fields in object types, interface types, and input types. I've recycled the gist object type test and added interface and input type cases.
The root cause was that the schema printer didn't re-check deprecated reason arguments if the deprecated directive already existed. Previously it (incorrectly) assumed that if the deprecated directive already existed, then the reason was fine. This PR fixes that.
I got nerd …

Update deprecated reason if changed by schema transformer

---

build.gradle

The original maintainer of shadow has handed over the project to GradleUp, an umbrella organisation that manages Gradle open source projects.
Good news is, the project is continuing. The only difference is the plugin ID changes to reflect the new ownership by GradleUp.
This PR pulls in the next closest version to what we had before, to minimise breaking changes.
As a paranoid end-to-end check, I created the jar with shading with this new plugin version, and pulled it into a separate project, running our Hello World example which requires Antlr to work. It still works.
GitHub thread explaining ownership change: https://github.com/GradleUp/shadow/issues/908
Changelog with 8.3.0 release notes: https://github.com/GradleUp/shadow/blob/main/src/docs/changes/README.md#v830-2024-08-08

Update shadow plugin after ownership change

---

build.gradle

Reverts graphql-java/graphql-java#3791
I'll debug later, I suspect this caused failing PR builds. This is mysterious, because the original PR's build did pass

Revert "Update shadow plugin after ownership change"

---

src/main/java/graphql/schema/GraphQLUnionType.java

Remove the allocation overhead of the stream / lambda in isPossibleType; don't have the flame graph on hand any longer unfortunately but this was showing up as an allocation hotspot for one of our apps.

Optimize GraphQLUnionType.isPossibleType

---

src/main/java/graphql/schema/GraphQLInputObjectType.java

Avoid copying / allocating a new List in GraphQLInputObjectType's getFieldDefinitions method. the field definitions are already stored as values in an ImmutableMap, and the default Guava implementation of the values method returns an ImmutableList; the issue arises due to the returned collection being a "partial view", which ImmutableList.copyOf uses as a signal that it should create a defensive copy of the passed in collection. In this particular case we just don't care if it's a partial view, since the owning ImmutableMap will be retained regardless.

Avoid allocating in GraphQLInputObjectType.getFieldDefinitions

---

src/main/java/graphql/execution/ValuesResolverConversion.java

Avoid the overhead of streams and extra copying incurred in externalValueToLiteralForList.

Avoid allocation / stream overhead in ValuesResolverConversion

---

src/main/java/graphql/validation/RulesVisitor.java

Avoid overhead of creating a Stream in filterRulesVisitingFragmentSpreads, and instead just do the filtering inline in a for loop.

Avoid overhead of Stream / Iterator in RulesVisitor

---

src/test/groovy/graphql/execution/instrumentation/threadpools/ExecutorInstrumentationTest.groovy

This test has confused many PR authors over the past 2 months, it's a strangely flaky test that always passes on the 2nd try.
I estimate it fails less than 15% of the time but it's still very confusing, especially for first time contributors. This test is getting put in quarantine while we do more investigation.

Quiet flaky test (for now)

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/GraphqlErrorHelper.java
src/test/groovy/graphql/ExecutionResultImplTest.groovy
src/test/groovy/graphql/GraphqlErrorHelperTest.groovy

We can today make a Map<String,Object> from an ExecutionResult but we can do the opposite
I needed to to this in some client reading HTTP graphql response code and making a ER was difficult and should be in graphql-java so here it is

Added the ability to parse our ExecutionResult from a map that came from toSpecification

---

src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/idl/DirectiveInfo.java
src/test/groovy/graphql/Issue2141.groovy
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/introspection/IntrospectionWithDirectivesSupportTest.groovy
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
src/test/groovy/graphql/schema/diffing/SchemaDiffingTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorAppliedDirectiveHelperTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

To be consistent with `@experimental_disableErrorPropagation` we now add `@defer` to the schema if its not present

@defer is now auto included in the schema if missing

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/NormalizedVariables.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/directives/DirectivesResolver.java
src/main/java/graphql/execution/directives/QueryDirectives.java
src/main/java/graphql/execution/directives/QueryDirectivesBuilder.java
src/main/java/graphql/execution/directives/QueryDirectivesImpl.java
src/main/java/graphql/normalized/ArgumentMaker.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/main/java/graphql/normalized/VariableAccumulator.java
src/main/java/graphql/normalized/VariablePredicate.java
src/test/groovy/graphql/execution/directives/QueryDirectivesImplTest.groovy
src/test/groovy/graphql/execution/directives/QueryDirectivesIntegrationTest.groovy
src/test/groovy/graphql/execution/values/InputInterceptorTest.groovy
src/test/groovy/graphql/normalized/ENOToAstCompilerDirectivesTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerDirectivesTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy
src/test/groovy/graphql/schema/CoercingTest.groovy

Previously the ENO compiler would not respect "immediate" directives on a field. 
While it has the `QueryDirectives` object - this doe not have "Normalised" values for directive arguments.
This PR adds that.  This PR is more extensive that I had hoped - but adding Normalised values in multiple places will set us up for betterness later

Allowing document compiler to handles directives and values down in the field tree

---

src/main/java/graphql/validation/rules/ArgumentsOfCorrectType.java
src/main/java/graphql/validation/rules/VariableDefaultValuesOfCorrectType.java
src/test/groovy/graphql/validation/rules/ArgumentsOfCorrectTypeTest.groovy
src/test/groovy/graphql/validation/rules/VariableDefaultValuesOfCorrectTypeTest.groovy

Fixes #3779 , thanks @replikonio for reporting!
This updates 2 validation rules to use the locale in the validation context. This locale is set as the client's locale (via ExecutionInput) or defaults to the JVM default locale.
One validation rule for incoming requests `VariableTypesMatch` was already using the client's locale. This updates 2 more rules to use the client's locale as well.

Use client locale if possible in validation of incoming requests

---

src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/test/groovy/graphql/schema/DataFetchingFieldSelectionSetImplTest.groovy

Addresses #3854.
Computes immediate fields only for `getImmediateFields()` to avoid cost of traversing the entire sub-tree to build glob-patterns for descendant fields.
Before:
```
Benchmark                                                          Mode  Cnt   Score   Error   Units
DFSelectionSetPerformance.benchMarkThroughput                     thrpt    9  10.424 ± 0.598  ops/ms
DFSelectionSetPerformance.benchMarkThroughput_getImmediateFields  thrpt    9  21.992 ± 0.224  ops/ms
DFSelectionSetPerformance.benchMarkAvgTime                         avgt    9   0.096 ± 0.005   ms/op
DFSelectionSetPerformance.benchMarkAvgTime_getImmediateFields      avgt    9   0.044 ± 0.001   ms/op
```
After:
```
Benchmark                                                          Mode  Cnt     Score    Error …
```

Optimize DataFetchingSelectionSet.getImmediateFields() to avoid traversing descendants

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy

Add printAstTo to AstPrinter, which allows the caller to supply their own target Appendable. This can be useful for reusing StringBuilders for instance.

Add method to AstPrinter to allow supplying Appendable

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/SubscriptionRootField.java
src/main/resources/i18n/Validation.properties
src/main/resources/i18n/Validation_de.properties
src/main/resources/i18n/Validation_nl.properties
src/test/groovy/graphql/validation/rules/SubscriptionRootFieldNoSkipNoIncludeTest.groovy
src/test/groovy/graphql/validation/rules/SubscriptionRootFieldTest.groovy

Fixes #3868 and implements https://github.com/graphql/graphql-spec/pull/860
We had an existing validation for subscription root fields. This adds on a new requirement that subscription root fields can't contain the `@include` nor `@skip` directives. See the spec link for more.
This could be considered a "breaking change" but it is more correctly a new validation requirement.

New spec validation: Subscriptions root field must not contain @skip nor @include on root selection set

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/EngineRunningObserver.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/test/groovy/graphql/EngineRunningTest.groovy
src/test/groovy/graphql/ExecutionInputTest.groovy
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/AsyncSerialExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/pubsub/RxJavaMessagePublisher.java

Addressing #3879
This allows the graphql operation to be co-operatively cancelled.  It use the "engine run state" tracking to know when its a good time to cancel and abort

Added ExecutionInput cancellation

---

build.gradle
src/test/groovy/graphql/GuavaLimitCheck.groovy

Fixes #3859 
We want to keep dependencies to an absolute minimum as this is a low level library. However we make an exception for a few selected Guava classes which are shaded in.
There's a potential risk where someone uses a new Guava class in a pull request, and either: 
1. They are unaware that they should, where possible, use a non-Guava version of the method (which is different to their usual developer workflow)
2. Or they really must use a Guava class, we forget to shade in the new class in the Gradle build file, causing functionality to break
This PR adds an Archunit test to detect new Guava class usage and produce a helpful error message to guide contributors to 1. use non-Guava versions where possible or 2. adjust the Gradle build file to shade in the new class
Example of …

Detect and prohibit new Guava classes

---

.github/workflows/commit_performance_result.yml
.github/workflows/publish_commit.yml

Fixes 2 problems seen lately on our performance pipeline, after enabling multiple concurrent runs
1. **Too many jobs.** We sent 36 jobs off in the space of a few minutes which was unnecessary. This is because the performance pipeline is triggered on every master commit, and some branches had many commits. This wasn't a problem before enabling concurrent pipeline runs. **Solution: change the performance pipeline to trigger on pull request merge instead**
2. **We had a race condition**, because two performance pipeline runs completed at almost the same time. The second pipeline couldn't commit the results because the HEAD of master changed during the copy step of the 2nd pipeline. **Solution: add another `git pull` before committing results.** Example of race condition: …

Performance pipeline improvements

---

src/main/java/graphql/GraphqlErrorHelper.java
src/test/groovy/graphql/GraphQLErrorTest.groovy

A fix for https://github.com/graphql-java/graphql-java/issues/3885
I felt that changing `GraphQLErrorHelper.location()`, rather than `BaseError.getLocations()`, was the least intrusive approach. However, there may be other places, in the present or in the future, where NPEs could show up due to null error locations, so maybe the change to `BaseError.getLocations()` outlined in https://github.com/graphql-java/graphql-java/issues/3885 would be a better option. Maybe both changes? It's at the discretion of the reviewer.

filter out null error location in toSpecification

---

src/main/java/graphql/execution/DataFetcherResult.java

I made a classic NPE mistake because I forgot to check if `data` was null while writing a DataFetcher
With JSpecify, we can detect NPEs like this at compile time rather than run time.
Have a look at the documentation for `@NullMarked` https://jspecify.dev/docs/user-guide/#nullmarked
This is the first PR to add JSpecify to an existing class so let's have a discussion.

Add JSpecify nullability annotations to DataFetcherResult

---

src/main/java/graphql/EngineRunningState.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/EngineRunningObserver.java
src/test/groovy/graphql/EngineRunningTest.groovy

Because the engine state updates are side effects, it can happen that the last "NOT_RUNNING" happens after the overall `CompletableFuture<ExecutionResult>` is completed.
As this is very counterintuitive this PR fixes that edge case with observing the `CompletableFuture<ExecutionResult>` explicitly.
It also make explicit states for Start and finish the engine.

Fix and improve EngineRunning state

---

src/main/java/graphql/execution/ExecutionStrategy.java

While updating graphql-kotlin to graphql-java 23 found that `completeField` is still wrapping `FieldValueInfo.fieldValueObject` in a `CompletableFuture` for objects already materialized / in memory
this might be considered a follow up of the `Completable Future wrapping` change set that came in graphql-java 22
https://github.com/graphql-java/graphql-java/releases/tag/v22.0
I don't think this is a breaking change.

avoid wrapping materialized fieldValueObject in a CompletableFuture

---

build.gradle

Since org.specify import is not necessarily needed at runtime, can we make it optional?

OSGI - Make org.jspecify.* imports optional

---

src/main/java/graphql/Assert.java
src/main/java/graphql/schema/idl/FieldWiringEnvironment.java
src/main/java/graphql/schema/idl/InterfaceWiringEnvironment.java
src/main/java/graphql/schema/idl/ScalarInfo.java
src/main/java/graphql/schema/idl/ScalarWiringEnvironment.java
src/main/java/graphql/schema/idl/SchemaParser.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/UnionWiringEnvironment.java
src/main/java/graphql/schema/idl/WiringEnvironment.java

Related https://github.com/graphql-java/graphql-java/issues/3878
I applied `@NullMarked` on the classes:
* `graphql.Assert`
* `graphql.schema.idl.FieldWiringEnvironment`
* `graphql.schema.idl.InterfaceWiringEnvironment`
* `graphql.schema.idl.ScalarInfo`
* `graphql.schema.idl.ScalarWiringEnvironment`
* `graphql.schema.idl.SchemaParser`
* `graphql.schema.idl.TypeDefinitionRegistry`
* `graphql.schema.idl.UnionWiringEnvironment`
* `graphql.schema.idl.WiringEnvironment`

Specify nullness for some `graphql.schema.idl` classes

---

build.gradle

Small change to bring this library in line with a recent change in DataLoader https://github.com/graphql-java/java-dataloader/pull/194/files

Make JSpecify optional import more specific

---

src/main/java/graphql/schema/SingletonPropertyDataFetcher.java

This was always the intention here when we created https://github.com/graphql-java/graphql-java/pull/3754 to have a singleton property fetcher instance
However we didnt do the factory right and hence `DataFetcherFactoryEnvironment` are created when they dont need to be
This fixes on of the items found in https://github.com/graphql-java/graphql-java/issues/3939
Namely why was "graphql.schema.DataFetcherFactoryEnvironment"  being 2% of objects allocated
This fixes that
re : https://github.com/graphql-java/graphql-java/issues/3941

Retriveing singleton property fetchers will not create DataFetcherFactoryEnvironment objects

---

src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/incremental/DeferredExecutionSupport.java

This is really 1% stuff. Its debatably faster BUT it uses (slightly) less memory and thats a good thing at scale

ExecutionStrategyParameters now has a direct transform without a Builder

---

src/jmh/java/graphql/execution/ExecutionStepInfoBenchmark.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/ExecutionStepInfoFactory.java
src/main/java/graphql/execution/ExecutionStrategy.java

This is really 1% stuff.  Its debatably faster BUT it uses (slightly) less memory and thats a good thing at scale
```
Benchmark                                                        (howManyItems)   Mode  Cnt    Score    Error  Units
ExecutionStepInfoBenchmark.benchMarkBuilderThroughput                   1000000  thrpt    4  376.814 ±  7.136  ops/s
ExecutionStepInfoBenchmark.benchMarkBuilderThroughput                   2000000  thrpt    4  188.889 ±  2.585  ops/s
ExecutionStepInfoBenchmark.benchMarkDirectConstructorThroughput         1000000  thrpt    4  379.725 ± 13.369  ops/s
ExecutionStepInfoBenchmark.benchMarkDirectConstructorThroughput         2000000  thrpt    4  191.496 ±  1.785  ops/s
```

ExecutionStepInfo now has a direct transform without a Builder

---

src/main/java/graphql/util/FpKit.java
src/main/java/graphql/util/NodeMultiZipper.java
src/test/groovy/graphql/util/FpKitTest.groovy

We no longer uses `.stream()` since its slower than an imperative style.
The methods were lacking tests so I went all TDD on it and write tests fist with the old streams implementation and then changed it and  watched the tests pass

FpKit now longer uses streams for performance reasons

---

src/test/groovy/graphql/execution/reactive/tck/CompletionStageMappingPublisherTckVerificationTest.java

use always a new thread for the tck verification as the TCK uses thread locals to track things, which can cause tests failure in rare cases

Avoid rare TCK test failure

---

src/main/java/graphql/GraphqlErrorHelper.java
src/test/groovy/graphql/GraphqlErrorHelperTest.groovy

In upgrading from 22.3 to 24.0, some of our tests that make assertions on serialized responses started failing.
I think this was probably caused by [#3753](https://github.com/graphql-java/graphql-java/pull/3753/files#r1855350447), which changed the serialized representation from a LinkedHashMap to a `Map.of`, which has [randomized iteration order](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/ImmutableCollections.java#L62-L68). This PR brings back the LinkedHashMap serialization format.
I'd appreciate some feedback on this! While the spec doesn't describe how the fields of an error should be ordered, non-deterministic ordering can make it difficult to build reliable tests that interact with GraphQL errors.

deterministic SourceLocation serialization

---

src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/pubsub/CommonMessagePublisher.java
src/test/groovy/graphql/execution/pubsub/FlowMessagePublisher.java
src/test/groovy/graphql/execution/pubsub/ReactiveStreamsMessagePublisher.java

This allows an implementation to return a `Flow.Publisher` in their data fetcher
It will be converted to a reactive streams publisher when it comes back out of the ExecutionResult.

Added support for Flow publishers coming back from the subscription field data fetcher

---

src/main/java/graphql/util/querygenerator/QueryGenerator.java
src/main/java/graphql/util/querygenerator/QueryGeneratorFieldSelection.java
src/main/java/graphql/util/querygenerator/QueryGeneratorResult.java
src/test/groovy/graphql/util/querygenerator/QueryGeneratorTest.groovy

- add constructor with default options
- rename `typeClassifier` to `typeName`
- return data structure containing the generated query + useful information about the execution

A few adjustments in the QueryGenerator util

---

src/main/java/graphql/schema/idl/ImmutableTypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/test/groovy/graphql/schema/idl/ImmutableTypeDefinitionRegistryTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

The `graphql.schema.idl.TypeDefinitionRegistry` is very mutable and we cant break its mutability at this stage of its life.
So we have added a `.readOnly()` mechanism that returns a `graphql.schema.idl.ImmutableTypeDefinitionRegistry` that is a `TypeDefinitionRegistry`
So code that is read only like the SchemaGenerator and TypeCheckers can be faster because they dont allocate copies all the time

Added a read only copy of a type registry for performance reasons

---

src/main/java/graphql/schema/idl/MockedWiringFactory.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/test/groovy/graphql/schema/idl/MockedWiringFactoryTest.groovy

If a schema has a default value on a custom scalar then the current MockWiringFactory will not fake it out well enough to create the schema
You get
```
java.lang.UnsupportedOperationException: Not implemented...this is only a mocked wiring
at graphql.schema.idl.MockedWiringFactory$1.parseLiteral(MockedWiringFactory.java:72)
at graphql.schema.Coercing.parseLiteral(Coercing.java:176)
at graphql.schema.Coercing.parseLiteral(Coercing.java:205)
at graphql.validation.ValidationUtil.parseLiteral(ValidationUtil.java:128)
at graphql.validation.ValidationUtil.isValidLiteralValue(ValidationUtil.java:100)
at graphql.schema.validation.DefaultValuesAreValid.visitGraphQLArgument(DefaultValuesAreValid.java:70)
at graphql.schema.GraphQLArgument.accept(GraphQLArgument.java:301)
at …
```

Allows creating mock schemas where there are default values on custom schemas

---

src/main/java/graphql/collect/ImmutableKit.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionQueryBuilder.java
src/main/java/graphql/introspection/IntrospectionWithDirectivesSupport.java
src/main/java/graphql/schema/idl/SchemaParseOrder.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeDirectivesChecker.java
src/test/groovy/graphql/collect/ImmutableKitTest.groovy

Die `.stream()` die
We still have some left but they tend to be .findFirst() or flatMap and hence harder to replace in a straight forward manner

Removed more .streams() with our filterAndMap code

---

src/main/java/graphql/ExecutionInput.java
src/test/groovy/graphql/ExecutionInputTest.groovy

Support null query when running APQ request. This is upstream merge of our commit made by @joshjcarrier
#4008
This pull request modifies the ExecutionInput logic to return a persisted query marker when a null or empty query is provided along with a persistedQuery extension, ensuring graceful handling of APQ requests.
- `src/main/java/graphql/ExecutionInput.java`: Introduces a new static method (`assertQuery`) to check for null/empty queries and returns a persisted query marker if appropriate; also removes the strict non-null assertion in the builder.
- `src/test/groovy/graphql/ExecutionInputTest.groovy`: Adds a test case validating that a null query with the persistedQuery extension returns the expected persisted query marker.

Support null query when running APQ request

---

build.gradle

It is very handy to start a benchmark directly from within IntelliJ:
Without this configuration, I get the following error "Unable to find the resource: /META-INF/BenchmarkList"
@bbakerman  @andimarek  @dondonz

Possibility to run JMH benchmarks without JAR build

---

build.gradle

Update DataLoader with nullability annotation fixes. Backport to prepare for 24.2 release
We released 5.0.2, which is 5.0.1 plus one more nullability fix
Note that the 5.0.1 upgrade on master looks different https://github.com/graphql-java/graphql-java/pull/4043 that's because Chained DataLoaders are in master, but not 24.x

Update to DataLoader 5.0.2 - backport for 24.2

---

build.gradle

Hey @dfa1 @bbakerman ,
unfortunately this really breaks idea rebuild/build functionality. We need to keep this commented out by default and put it back in if we want to run JMH tests from idea.
If you find another solution that would be great ... I spend some time finding one, but could not . 😢

comment out the processor by default

---

build.gradle
src/jmh/java/benchmark/AssertBenchmark.java
src/jmh/java/benchmark/AstPrinterBenchmark.java
src/jmh/java/benchmark/ChainedInstrumentationBenchmark.java
src/jmh/java/benchmark/CompletableFuturesBenchmark.java
src/jmh/java/benchmark/CreateExtendedSchemaBenchmark.java
src/jmh/java/benchmark/CreateSchemaBenchmark.java
src/jmh/java/benchmark/GetterAccessBenchmark.java
src/jmh/java/benchmark/IntMapBenchmark.java
src/jmh/java/benchmark/IntrospectionBenchmark.java
src/jmh/java/benchmark/MapBenchmark.java
src/jmh/java/benchmark/OverlappingFieldValidationBenchmark.java
src/jmh/java/benchmark/PropertyFetcherBenchMark.java
src/jmh/java/benchmark/SchemaTransformerBenchmark.java
src/jmh/java/benchmark/SimpleQueryBenchmark.java
src/jmh/java/benchmark/TwitterBenchmark.java
src/jmh/java/benchmark/TypeDefinitionParserVersusSerializeBenchmark.java
src/jmh/java/benchmark/ValidatorBenchmark.java
src/test/groovy/graphql/archunit/JMHForkArchRuleTest.groovy
src/test/groovy/graphql/archunit/NullabilityAnnotationUsageTest.groovy

Fixes #4010. Adds an ArchUnit test to prohibit JMH tests that use more than 2 forks. This is to save time in our automated testing pipeline, because extra forks don't add much value.
I had to update our test config because our JMH benchmarks are not in the usual package as everything else. ArchUnit reads .class files. Without this configuration change, ArchUnit can't read any JMH tests.
While I'm here I also: 
* Tidied up the test config, to reduce repetition
* Changed all offending JMH tests to 2 forks, even if they don't run in the automated pipeline (in `performance`), because I'd rather we apply this rule equally to all benchmarks
* Created a new home for ArchUnit tests, make it easier to find
Sample error output
```
Architecture Violation [Priority: MEDIUM] - Rule 'classes that are …
```

Prohibit JMH tests from having more than 2 forks

---

src/main/java/graphql/incremental/IncrementalExecutionResultImpl.java
src/test/groovy/graphql/incremental/IncrementalExecutionResultTest.groovy

Fixes the `transform()` method in `IncrementalExecutionResultImpl` to return an `IncrementalExecutionResult` that preserves all incremental-specific field values instead of losing them.
- Updated `IncrementalExecutionResultImpl.transform()` to preserve `incremental`, `hasNext`, and `incrementalPublisher` fields
- Improved `IncrementalExecutionResultTest` with comprehensive test coverage for the transform behavior
Fixes #4072

Fix IncrementalExecutionResult.transform() to preserve incremental fields

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/incremental/DeferredExecutionSupport.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/NoContextChainedInstrumentation.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/ModernTestingInstrumentation.groovy

The current deferred field Instrumentation is broken - it has no arguments and its context is never called back.
This implements it more properly.  It calls beingDeferredField each time a field actually gets started - eg after the main operation has finished and we begin to drain the deferred queue

Fixed deferred support to have proper Instrumentation

---

src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/main/java/graphql/util/LinkedHashMapFactory.java
src/test/groovy/graphql/archunit/MapOfUsageTest.groovy

Fixes #3989
Turns out Map.of doesn't guarantee consistent order when serialized, which is easy to forget. This PR adds an ArchUnit rule to ban it.
Additionally I created LinkedHashMap equivalents of Map.of to make things easier. It is verbose but intended to be a copy of the original Map methods.
Sample error message for ArchUnit test
```
Map.of() usage detected. Please use LinkedHashMap instead for consistent serialization order:
- Method <graphql.normalized.ExecutableNormalizedOperationToAstCompiler.compileToDocument(graphql.schema.GraphQLSchema, graphql.language.OperationDefinition$Operation, java.lang.String, java.util.List, graphql.normalized.VariablePredicate)> calls method <java.util.Map.of()> in (ExecutableNormalizedOperationToAstCompiler.java:103)
- Method …
```

Prohibit Map.of and provide alternative methods

---

build.gradle

We're getting an unusual error message on our JMH pipeline, and I'm trying to eliminate options. It mysteriously stops after this dependabot update https://github.com/graphql-java/graphql-java/commit/0b5c7629f345194923c3278f1c8994f1085e4f5d

Try revert this shadow change with JMH debugging
