src/main/java/graphql/ExceptionWhileDataFetching.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/InvalidSyntaxError.java
src/main/java/graphql/validation/ValidationError.java
src/test/groovy/graphql/GraphQLTest.groovy

Fixes my largest problem with the library at this point.

Fix typo in method name

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SimpleExecutionStrategy.java
src/main/java/graphql/schema/GraphQLInterfaceType.java

Initial execution strategy work

---

src/main/java/graphql/schema/GraphQLEnumType.java

This appears to be in line w/ graphql-js implementation:
https://github.com/graphql/graphql-js/blob/1c5cdbd314200a5bc78ef52b6be9194587a55437/src/type/definition.js#L823

Pass name in as the default value if nothing is provided

---

src/main/java/graphql/schema/FieldDataFetcher.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/test/groovy/graphql/DataFetcherTest.groovy

The FieldDataFetcher will fetch data directly from raw fields.
It can be enabled by calling the "fetchField()" method on the field definition builder.

Added fetching from raw fields.

---

README.md

Fixes the GraphQLInterfaceType example in README.md

fix example for GraphQLInterfaceType

---

src/main/java/graphql/execution/ExecutionStrategy.java

it's difficult to debug the exception when you can't set a breakpoint to the point where the exception is actually thrown

add curly braces to exception throwing ifs

---

src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/test/groovy/graphql/execution/ExecutorServiceExecutionStrategyTest.groovy

Added documentation to ExecutorServiceExecutionStrategy

---

src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLInputObjectTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLInterfaceTypeTest.groovy
src/test/groovy/graphql/schema/GraphQLObjectTypeTest.groovy

assert that fields are not re-defined

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/DataFetcherTest.groovy

add fetching fields to PropertyDataFetcher

---

README.md

Hi, I thought this might also deserve a spot in "Related Projects": This project exports a servlet that automatically exposes a schema dynamically built from GraphQL queries and mutations.

Mention graphql-java-servlet project

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/validation/SpecValidation51Test.groovy
src/test/groovy/graphql/validation/SpecValidation521Test.groovy
src/test/groovy/graphql/validation/SpecValidationBase.groovy
src/test/groovy/graphql/validation/SpecValidationSchema.java
src/test/groovy/graphql/validation/SpecValidationSchemaPojos.java

Some tests are disable, edit SpecValidationBase.enableStrictValidation = true to enable them.

Adding SpecValidation tests, sections 5.1 and 5.2.1

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/ScalarsQuerySchema.java
src/test/groovy/graphql/ScalarsQueryTest.groovy

When resolving a Double value, checking for NaN and returning null

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/test/groovy/graphql/execution/batched/FunWithStringsSchemaFactory.java
src/test/groovy/graphql/execution/batched/GraphqlExecutionSpec.groovy
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy

Fix for https://github.com/andimarek/graphql-java/issues/114 NPE when coercing null enum value in BatchedExecutionStrategy

Fix for #114 - NPE when coercing null enum value in BatchedExecutionStrategy

---

src/test/groovy/graphql/ScalarsQuerySchema.java
src/test/groovy/graphql/ScalarsQueryTest.groovy

The test expects a NumberFormatException to escape out of the execution engine, which should be changed later to an error in the list of errors.

Validation tests of result coercing a non-number string to a number

---

README.md

Includes an example from the todomvc-relay-java codebase with explanation
resolves #154

Expand README section on use with Relay

---

src/main/java/graphql/schema/GraphQLEnumType.java

Add overload of GraphQLEnumType.Builder.value() with deprecationReason

---

src/main/java/graphql/introspection/IntrospectionQuery.java
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy

Was a bit lazy in the unit test, not writing the full thing, but the other tests already cover individual introspection aspects, so I thought it to be all-right.

Added introspection query to codebase (issue #138)

---

src/main/java/graphql/relay/Base64.java
src/main/java/graphql/relay/Relay.java

- always use UTF-8 for decoding and encoding global id
- use getter instead of field in global id

some code cleanup

---

src/main/java/graphql/schema/SchemaUtil.java

Addresses #118 
If we already have a type resolved on the typemap, the resolved type should point to the same instance.

Recursive types not being resolved

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/parser/Parser.java

Fixes #230. 4 locations where Loggers existed:
* 1 changed from info to debug
* 2 changed from info to warn
* 1 unused, removed

Change log-levels to more appropriate setting (#230)

---

src/main/java/graphql/relay/SimpleListConnection.java

I ran into this problem and needed a simple fix.
Also cheers to my first PR :grin:

SimpleConnection with "last" argument > data size might throw ArrayIndexOutOfBoundsException

---

src/test/groovy/graphql/GraphQLTest.groovy

Add tests for #127

---

src/main/java/graphql/ExceptionWhileDataFetching.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/InvalidSyntaxError.java
src/main/java/graphql/validation/ValidationError.java
src/test/groovy/graphql/ErrorsTest.groovy

#253 - now with equals and hash code on GraphQlError

#253 - hash code and equals on error helper

---

README.md
src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/Scalars.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/schema/Coercing.java
src/main/java/graphql/schema/DataFetcher.java
src/main/java/graphql/schema/DataFetchingEnvironment.java

#273 
This picks up from where https://github.com/graphql-java/graphql-java/pull/91/ left off.
The original PR seems abandoned and did tricky things with the gradle build.  This is that code with more generics.
I know there are other PRs in the pipe that contain some of these changes but so be it.  if I need to merge conflicts I will.

#273 - use generics where possible

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/DataFetcherTest.groovy

#260 - Made DataFetchingEnvironment an interface.  I appreciate that some one else did a PR on this but it had merge conflicts and I could not easily get the branch in play so it was easier to replicate the approach.

 DataFetchingEnvironment as an interface.

---

src/main/java/graphql/Scalars.java
src/main/java/graphql/schema/Coercing.java

Fix #317: Coercing<T> should be Coercing<I, O> ?

---

src/main/java/graphql/Scalars.java
src/test/groovy/graphql/ScalarsTest.groovy

This is where the code is much more lenient in what numerical scalar types accept and how they coerce.

105 - lenient numerical scalars

---

src/test/groovy/graphql/validation/rules/ArgumentsOfCorrectTypeTest.groovy

Getting prepared to contribute with some unit tests.

Increasing test coverage for ArgumentsOfCorrectType.java

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/LoneAnonymousOperation.java
src/test/groovy/graphql/validation/SpecValidation51Test.groovy

Validation Rule was added to honor [Anonymous Operation Definitions](http://facebook.github.io/graphql/#sec-Anonymous-Operation-Definitions)

validation for lone anonymouse operation

---

README.md

- Clarify that in addition to Relay Apollo is also supported.
- Add hyperlinks to Relay and Apollo

Clarify supported clients in README.md

---

build.gradle

#300 updated slf4j

---

README.md

-  [graphql-java-reactive](https://github.com/bsideup/graphql-java-reactive) is added under related projects.

Add graphql-java-reactive

---

src/main/java/graphql/schema/FieldDataFetcher.java
src/main/java/graphql/schema/PropertyDataFetcher.java

#330 - made property and field data fetcher generic

---

src/main/java/graphql/schema/SchemaUtil.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy

My original PR #204 (already merged as a part of 2.3.0 release) should have had this commit already but somehow didn't... Something went terribly wrong.
I've now re-added the original missed commit and fixed the related test
closes #367

closes #367 TypeReferences resolved for interfaces and unions

---

src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLUnionType.java

#357 - link a runtime object back to its possible definition
+ some Java 8 fix ups as I changed code (broken window theory and IDEA rules)

#357 - link a runtime object back to its possible definition

---

README.md

Added missing import to README.md

---

src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/ParserTest.groovy

#352 - fixed the bug where too many tokens are allowed as valid

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/relay/DefaultConnection.java
src/main/java/graphql/relay/DefaultEdge.java
src/main/java/graphql/relay/DefaultPageInfo.java
src/main/java/graphql/relay/SimpleListConnection.java

Recent PRS introduced javadoc errors.  Fixed them up

Removes javadoc warnings during build time

---

README.md
src/test/groovy/readme/ReadmeExamples.java

#383 was caused by some one not knowing how to drive the library.  Improved the  readme to help

#383 added extra readme documentation for specific references

---

README.md
src/test/groovy/readme/ReadmeExamples.java

Reverts graphql-java/graphql-java#393 
I am not sure this extra method is really the best way to support TypeReferences .. up until now I revert the documentation.

Revert "#383 added extra readme documentation for specific references"

---

src/main/java/graphql/schema/SchemaUtil.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

This helps prevent that condition by enforcing the rules

Fixed a problem where non unique type names cause class exceptions

---

src/test/groovy/readme/README.next.md
src/test/groovy/readme/ReadmeExamples.java

#402 - put a next version README in place

#402 - put a next version README in place

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/errors/NotAnInputTypeError.java
src/main/java/graphql/schema/idl/errors/NotAnOutputTypeError.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

fixing https://github.com/graphql-java/graphql-java/issues/425

425 improve wrong type exceptions

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/errors/NotAnInputTypeError.java
src/main/java/graphql/schema/idl/errors/NotAnOutputTypeError.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

add line column to type case error

425 add lincol

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/GraphQLTest.groovy

#448 parse null pointer

---

src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/test/groovy/graphql/parser/GraphqlAntlrToLanguageTest.groovy

a reimplementation of https://github.com/graphql-java/graphql-java/pull/200

Added antlr parsing tests

---

src/main/java/graphql/schema/SchemaUtil.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

#457 =- certain names are special according to proposed spec

#457 - support for implicit schema when types are named `Query`

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

#467 generate additional types into schema

#467 generate additional types into schema

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java

As discussed here: https://github.com/graphql-java/graphql-java/pull/480#discussion_r119765358

remove unused `extensions` field from ExecutionResult(Impl)

---

src/main/java/graphql/execution/TypeInfo.java

#490 type info build is public

#490 type info build is public

---

src/main/java/graphql/schema/idl/errors/SchemaProblem.java
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

#489 schema problem has message now

#489 schema problem has message now

---

src/main/java/graphql/Scalars.java
src/test/groovy/graphql/ScalarsIDTest.groovy

It will be great to make Long ids valid as well. 😅 
Please let me know if I need to add more tests.

Respect Long as ID

---

src/main/java/graphql/execution/instrumentation/NoOpInstrumentation.java

Here is one granular portion of my earlier PR #504 Refactorings.

Reduce code duplication in NoOpInstrumentation

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionParameters.java
src/test/groovy/example/http/HttpMain.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

Renamed ExecutionInput in terms of spec

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/errors/InvalidDeprecationDirectiveError.java
src/main/java/graphql/schema/idl/errors/NonUniqueArgumentError.java
src/main/java/graphql/schema/idl/errors/NonUniqueDirectiveError.java
src/main/java/graphql/schema/idl/errors/NonUniqueNameError.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

#468 - deprecation is now supported in IDL and hence Introspection (and reverse Introspection to IDL)

#468 - deprecation is now supported in IDL and hence Introspection 

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentBuilder.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/DataFetcherTest.groovy
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

#492 - builder for DataFetchingEnvironmentImpl

#492 - builder for DataFetchingEnvironmentImpl

---

src/main/java/graphql/validation/ValidationError.java
src/main/java/graphql/validation/ValidationErrorCollector.java
src/main/java/graphql/validation/rules/ScalarLeafs.java
src/test/groovy/graphql/validation/rules/ScalarLeafsTest.groovy

I think it will be great to include field name for better user experience. In my case I got `Sub selection required for type null` error and was pretty confused for a moment 😅

Include field name in error description

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentBuilder.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

#421 Added FieldDefinition to the DataFetchingEnvironment

Added FieldDefinition to the DataFetchingEnvironment

---

src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/language/Argument.java
src/main/java/graphql/language/Directive.java
src/main/java/graphql/language/EnumTypeDefinition.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/FragmentDefinition.java
src/main/java/graphql/language/FragmentSpread.java
src/main/java/graphql/language/InlineFragment.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/InputValueDefinition.java
src/main/java/graphql/language/InterfaceTypeDefinition.java
src/main/java/graphql/language/NodeUtil.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/ScalarTypeDefinition.java
src/main/java/graphql/language/SchemaDefinition.java
src/main/java/graphql/language/TypeDefinition.java
src/main/java/graphql/language/UnionTypeDefinition.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/language/DirectiveTest.groovy

#518 Improved directive handling for places that use them

Improved directive handling for places that use them

---

src/main/java/graphql/schema/GraphQLEnumType.java
src/test/groovy/graphql/Issue526.groovy
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy

#526 better support for Java enums by using a serialisation strategy that knows about how Java Enum<?> have unique String names

better support for Java enums

---

build.gradle

Allows to deploy jar in OSGi container without wrapping it

Use bnd plugin to add OSGi manifest info

---

src/main/java/graphql/ExceptionWhileDataFetching.java
src/main/java/graphql/execution/DataFetcherExceptionHandler.java
src/main/java/graphql/execution/DataFetcherExceptionHandlerParameters.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java
src/main/java/graphql/execution/SimpleExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/ErrorsTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

#523 - this addresses the ability to compose execution strategies better
#525 - this also addresses the need to have a richer error reporting capability

Better error handling via composition and more info to the handlers

---

src/main/java/graphql/schema/idl/NoopWiringFactory.java
src/main/java/graphql/schema/idl/RuntimeWiring.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/TypeRuntimeWiring.java
src/main/java/graphql/schema/idl/WiringFactory.java
src/test/groovy/graphql/schema/idl/RuntimeWiringTest.groovy
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

#536 - the data fetcher used when no other data fetcher has been provided

Allows the data fetcher of last resort to be specified

---

src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java

Removes the only javadoc warning in the build

Fixed javadoc issue

---

src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/test/groovy/graphql/schema/GraphQLFieldDefinitionTest.groovy

assert dataFetcher is non null

---

src/main/java/graphql/schema/GraphQLEnumType.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/validation/TraversalContextTest.groovy

This fixes #546: Validation failed with a ClassCastException instead a clean Error.

this fixes #546: GraphQLEnumType was not marked as Nullable

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java
src/test/groovy/example/http/HttpMain.java
src/test/groovy/example/http/JsonKit.java
src/test/groovy/graphql/ExecutionResultTest.groovy

#473  execution result to spec

 execution result to spec

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

543 - removes the legacy method

Removed legacy handleDataException method

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/test/groovy/graphql/NonNullHandlingTest.groovy
src/test/groovy/graphql/execution/AsyncTest.groovy

- add helper class `Async` to simplify executing CFs sequentially
- make completeValueForList non blocking

improve async handling

---

src/main/java/graphql/relay/Connection.java
src/main/java/graphql/relay/ConnectionCursor.java
src/main/java/graphql/relay/DefaultConnection.java
src/main/java/graphql/relay/DefaultConnectionCursor.java
src/main/java/graphql/relay/DefaultEdge.java
src/main/java/graphql/relay/DefaultPageInfo.java
src/main/java/graphql/relay/Edge.java
src/main/java/graphql/relay/InvalidCursorException.java
src/main/java/graphql/relay/PageInfo.java
src/main/java/graphql/relay/Relay.java
src/main/java/graphql/relay/SimpleListConnection.java
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy

Better exceptions in relay cursors plus some code tweaks

---

src/main/java/graphql/execution/ExecutionStrategy.java

Documentaiton build on windows failed as '-' character was not from cp1252 code page (first 127 codes).

Replace '-' character with one from cp1252

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/AsyncTest.groovy

there is no need to make list completion sequential ... this changes it

make list completion not sequential, but fully async

---

src/main/java/graphql/validation/ArgumentValidationUtil.java
src/main/java/graphql/validation/ValidationUtil.java
src/main/java/graphql/validation/rules/ArgumentsOfCorrectType.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/validation/rules/ArgumentsOfCorrectTypeTest.groovy

Improve error messages for arguments that fail validation

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/batched/BatchedExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy

Fixed instrumentation calls in BatchedExecutionStrategy

---

src/main/java/graphql/ExecutionResultImpl.java

Fixed ctor bug

---

src/main/java/graphql/relay/DefaultEdge.java
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy

Fixed nullablity in DefaultEdge

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy
src/test/groovy/graphql/analysis/MaxQueryDepthInstrumentationTest.groovy

MaxQueryDepth/MaxComplexity instrumentations must check
for errors before doing anything

fix instrumentation error handling

---

README.md

added readme link

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/AsyncSerialExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

See #686 
I want this code to set us up to allow us to solve https://github.com/graphql-java/graphql-java/issues/162

686 variable coercion to spec

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

See #163 
wow this bug has been there for a long  time (2016).  Perhaps its not that useful but hey its fixed now

Primitive array support

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/batched/BatchedExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/batched/FunWithStringsSchemaFactory.java

Adds Optional support to BatchedES

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/ExecutionNode.java
src/test/groovy/graphql/execution/instrumentation/TracingInstrumentationTest.groovy

Fixes #674 and also fixes the extra ticket I raised as #675

This fixes BatchedExecutionStrategy so that it maintains the correct type info

---

src/main/java/graphql/analysis/QueryTraversal.java
src/test/groovy/graphql/analysis/QueryTraversalTest.groovy

This fixes two bugs:
- Introspection fields were not recognized at all
- NonNull/List types were not handled properly

fixing query traversal bugs (Introspection and NonNull/List)

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/batched/BatchedExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/batched/FunWithStringsSchemaFactory.java

Adds Iterable support to returned values

---

src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/test/groovy/graphql/GraphQLTest.groovy

fix handling of non batched data fetchers returning CompletableFuture

fix batched execution

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/test/groovy/graphql/execution/AsyncTest.groovy
src/test/groovy/graphql/execution/batched/BatchedExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/batched/FunWithStringsSchemaFactory.java

Now handles CompletableFuture coming back from an un batched DF

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/batched/BatchedExecutionStrategyTest.groovy

Make sure BatchedExecutionStrategy instruments dataFetcher

---

src/main/java/graphql/execution/NonNullableFieldValidator.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/batched/FetchedValues.java
src/test/groovy/graphql/execution/batched/BatchedExecutionStrategyTest.groovy

This technically fixes #684 but it is still not spec compliant re: 
http://facebook.github.io/graphql/#sec-Errors-and-Non-Nullability
But this is setting us up I think

684 batched es does not handle exceptions

---

src/main/java/graphql/schema/idl/ScalarInfo.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This is an extension of #709 - I could not back update the original PR so I included it as is and tweaked it a little further

Henryqdineen built in scalars

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/GraphQLTest.groovy

Added the ability to copy a GraphQL object more easily

---

src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

see #108 
now follows the more lenient implementation like graphql-js
https://github.com/graphql/graphql-js/pull/230/files
https://github.com/facebook/graphql/pull/120/files

Now follows graphql-js and its more lenient field merging

---

src/main/java/graphql/introspection/Introspection.java

Missing schema directives in Introspection types

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy

Now sorts schema printer output

---

src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/execution/ValuesResolver.java

Fixed the naming of the coerced exceptions

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/test/resources/simplelogger.properties

Added more logging to key places

---

src/main/antlr/Graphql.g4
src/test/groovy/graphql/parser/ParserTest.groovy

See #100 
https://facebook.github.io/graphql/#sec-Source-Text

Follows spec on whitespace

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/main/java/graphql/schema/idl/ScalarInfo.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/UnExecutableSchemaGenerator.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Added the ability to print an Introspection result as a schema

---

src/main/java/graphql/schema/DataFetcherFactories.java
src/main/java/graphql/schema/DataFetcherFactory.java
src/main/java/graphql/schema/DataFetcherFactoryEnvironment.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/idl/CombinedWiringFactory.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/WiringFactory.java
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy
src/test/groovy/graphql/validation/SpecValidationSchema.java

Adds a level of indirection into the data fetchers which are specified at
schema def time but needed "wired" at query execution time
see #734

Added DataFetcherFactory support

---

src/main/java/graphql/schema/validation/ObjectsImplementInterfaces.java

Improves parameter namng in ObjectsImplementsInterfaces#isCompatible

---

src/test/groovy/graphql/Issue743.groovy

See #743 for more details.
No fix justa test to prove its the case

Test for #743 to prove it works

---

src/test/groovy/example/http/HttpMain.java
src/test/resources/httpmain/index.html

So we have graphiql support on our local example
eg: localhots:3000/ just works

Adds graphiql support to out HttpMain example

---

docs/batching.rst
src/main/java/graphql/GraphQL.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
src/test/groovy/readme/BatchingExamples.java

Better examples of using per request data loaders

---

src/main/java/graphql/analysis/QueryTraversal.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/language/TypeDefinition.java
src/main/java/graphql/language/TypeExtensionDefinition.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/validation/rules/KnownDirectives.java
src/test/groovy/graphql/NestedInputSchema.java

Code health - IDEA suggestions and general tweaks

---

src/main/java/graphql/schema/GraphQLInterfaceType.java

Could you please also merge this one for v4 ?
Thanks

Fixed stack overflow on toString()

---

src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy

Fix ArrayIndexOutOfBoundsException in empty ChainedInstrumentation

---

src/main/java/graphql/analysis/QueryTraversal.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/introspection/Introspection.java
src/test/groovy/graphql/analysis/QueryTraversalTest.groovy

Fixes #763 QueryTraversal problem

---

src/main/java/graphql/TypeResolutionEnvironment.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy

Made TypeResolution return <T> for easier consumption

---

src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java
src/main/java/graphql/execution/instrumentation/tracing/TracingSupport.java
src/test/groovy/graphql/execution/instrumentation/TracingInstrumentationTest.groovy

Add parsing and validation to TracingInstrumentation

---

src/main/java/graphql/schema/idl/EchoingWiringFactory.java
src/main/java/graphql/schema/idl/UnExecutableSchemaGenerator.java
src/test/groovy/graphql/schema/idl/EchoingWiringFactoryTest.groovy

An echoing runtime wiring

---

docs/execution.rst
src/test/groovy/readme/ReadmeExamples.java

Fixed documentation regarding input objects and map

---

docs/batching.rst

Slightly improve the `dataloader` docs

Improve batching.rst

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/main/java/graphql/execution/instrumentation/NoOpInstrumentation.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldCompleteParameters.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy

Now allows the schema and execution context to be tweaked before execution

Better instrumentation at more points in the execution lifecycle.

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/InputMapDefinesTooManyFieldsException.java
src/main/java/graphql/execution/NonNullableValueCoercedAsNullException.java
src/main/java/graphql/schema/CoercingParseValueException.java
src/test/groovy/graphql/Issue739.groovy
src/test/groovy/graphql/Issue743.groovy
src/test/groovy/graphql/NullValueSupportTest.groovy

See #786 and the discussion on errors versus exceptions

Now catches validation exceptions and reports them as errors

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy

Instrument execution input so people can change that gets input (say …variables)

Instrument execution input 

---

src/main/java/graphql/GraphQL.java
src/test/resources/simplelogger.properties

Reduced logger down to warn and fixed up logging in tests

---

src/main/java/graphql/language/NodeUtil.java

#842   I was wrong to check String value.
So, I change operationName condition.
```
String == ""  // NO 
"".equals(String) O // YES ! 
```
Sorry to bother you. :(

Change operationName condition

---

src/main/java/graphql/schema/PropertyDataFetcher.java

Allows some one to see what property will be fetched the fetcher

Makes the property name a public getter

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Fix introspection processing missing implements

---

src/main/antlr/Graphql.g4
src/test/groovy/graphql/parser/ParserTest.groovy

Corrected the float specification as per spec and Lee Byrons direction

---

src/main/java/graphql/schema/diff/DiffEvent.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/main/java/graphql/schema/diff/reporting/CapturingReporter.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy
src/test/resources/diff/schema_with_additional_field.graphqls

Report field additions in SchemaDiff.

---

src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderNodeTest.groovy

This does not fix the efficiency - but give examples of desired efficiency

More examples of data loader efficiency

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/GraphQLTypeReference.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/StarWarsSchema.java

Simple static method for static imports

Added a static method for static imports

---

src/main/java/graphql/execution/ExecutionStrategy.java

This is exactly the same code but with things moved around a little

Re-org of the  execution strategy code for maintenance reasons

---

README.md
src/main/java/graphql/execution/FieldCollector.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/SchemaUtil.java
src/main/java/graphql/validation/rules/PossibleFragmentSpreads.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy
src/test/groovy/graphql/schema/SchemaUtilTest.groovy

I made the changes I request on a separate branch based on the original changes

896 performance improvements to implementation type look (originally from intuit master)

---

src/main/antlr/Graphql.g4
src/test/groovy/graphql/parser/IDLParserTest.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Fixes #903 as well as adds & support for implements declarations

---

src/main/java/graphql/validation/rules/VariableTypesMatchRule.java
src/main/java/graphql/validation/rules/VariablesTypesMatcher.java
src/test/groovy/graphql/validation/rules/VariableTypesMatchRuleTest.groovy

Added better error messages for mismatched types

---

src/main/java/graphql/schema/idl/NoopWiringFactory.java
src/main/java/graphql/schema/idl/ScalarWiringEnvironment.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/WiringFactory.java
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

This provides a fix for #930 
Note: This is my very first pull request to this project. I'm not 100% familiar with the code yet, so please feel free to provide feedback if something seems off.

Adds the posibility to specify scalars in a WiringFactory

---

src/main/antlr/Graphql.g4
src/main/antlr/GraphqlSDL.g4
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/language/ObjectTypeExtensionDefinition.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/errors/TypeExtensionMissingBaseTypeError.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/parser/IDLParserTest.groovy

see #906
This adds the Antlr support for parsing an AST of type extensions

Added the grammar support for type extensions

---

src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java

this simplifies getting the current Field getting queried.

getField method on DataFetchingEnvironment 

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy

adds method to print ast in a more compact format

Ast print compact

---

docs/index.rst
docs/scalars.rst
src/main/java/graphql/Scalars.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/schema/Coercing.java
src/main/java/graphql/schema/CoercingParseLiteralException.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/validation/ValidationUtil.java
src/test/groovy/graphql/ScalarsBigDecimalTest.groovy
src/test/groovy/graphql/ScalarsBigIntegerTest.groovy
src/test/groovy/graphql/ScalarsBooleanTest.groovy
src/test/groovy/graphql/ScalarsByteTest.groovy
src/test/groovy/graphql/ScalarsCharTest.groovy
src/test/groovy/graphql/ScalarsFloatTest.groovy
src/test/groovy/graphql/ScalarsIDTest.groovy
src/test/groovy/graphql/ScalarsIntTest.groovy
src/test/groovy/graphql/ScalarsLongTest.groovy
src/test/groovy/graphql/ScalarsShortTest.groovy
src/test/groovy/graphql/ScalarsStringTest.groovy
src/test/groovy/graphql/schema/GraphQLEnumTypeTest.groovy
src/test/groovy/readme/ScalarExamples.java

see #927 
Updated the JavaDoc and documentation on writing custom scalars

Updated javadoc and doc files on Scalars

---

src/main/java/graphql/Assert.java
src/test/groovy/graphql/AssertTest.groovy

Recently I was debugging code and I could not find out what name was the offending one.  This will help a lot

Added offending name to exception to allow better debugging

---

src/main/java/graphql/GraphQL.java
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy

Fixed a bug where the PreParser is not able to change the ExecutionInput

---

src/main/java/graphql/validation/rules/VariableTypesMatchRule.java
src/test/groovy/graphql/Issue938.groovy

While looking into #938 I uncovered a NullPointerException in the new "error message production"
I fixed it by avoiding the error message production because the check is invalid for unknown variables
eg If we have a unknownVariableX then by definition we can know its type and hence its a no op for the check on "same type".  It gets caught by other rules however

Error message production causes null pointer exception

---

src/main/java/graphql/execution/AbsoluteGraphQLError.java
src/test/groovy/graphql/execution/AbsoluteGraphQLErrorTest.groovy

Fixed a bug where extensions are lost in absolute errors

---

src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java

Deprecated batched execution strategy

---

README.md

Adds a note about #934 in README.md.

add a note that the tutorial is out-of-date

---

src/main/java/graphql/Scalars.java
src/test/groovy/graphql/ScalarsIDTest.groovy

Alternative to #971 if that's too broad.

support uuid as id type

---

src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/resources/starWarsSchemaExtended.graphqls

http://facebook.github.io/graphql/draft/#sec-Interfaces

multiple interfaces should use ampersand

---

src/main/java/graphql/execution/AbsoluteGraphQLError.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/ExecutorServiceExecutionStrategy.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/util/TraverserVisitor.java
src/test/groovy/graphql/execution/BreadthFirstExecutionTestStrategy.java
src/test/groovy/graphql/execution/BreadthFirstTestStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategyParametersTest.groovy

using idiomatic Java getters on ES parameters

---

src/main/java/graphql/language/Argument.java
src/main/java/graphql/language/Directive.java
src/main/java/graphql/language/DirectiveDefinition.java
src/main/java/graphql/language/DirectiveLocation.java
src/main/java/graphql/language/DirectivesContainer.java
src/main/java/graphql/language/EnumTypeDefinition.java
src/main/java/graphql/language/EnumValue.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/FragmentDefinition.java
src/main/java/graphql/language/FragmentSpread.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/InputValueDefinition.java
src/main/java/graphql/language/InterfaceTypeDefinition.java
src/main/java/graphql/language/NamedNode.java
src/main/java/graphql/language/NodeParentTree.java
src/main/java/graphql/language/ObjectField.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/OperationTypeDefinition.java
src/main/java/graphql/language/ScalarTypeDefinition.java
src/main/java/graphql/language/TypeDefinition.java
src/main/java/graphql/language/UnionTypeDefinition.java
src/main/java/graphql/language/VariableDefinition.java
src/main/java/graphql/language/VariableReference.java
src/test/groovy/graphql/language/NodeParentTreeTest.groovy

see #1002 
Now when you have a node you can ask its name if it implements NamedNode

Added NamedNode to the hierarchy

---

src/main/java/graphql/schema/PropertyDataFetcher.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

see #1012  and a related PR #1011

Makes the performance of the data fetcher better by caching the method lookups

---

src/main/java/graphql/schema/idl/NoopWiringFactory.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/WiringFactory.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

1014 fix fetch support in wiring factory

---

src/test/groovy/graphql/execution/ExceptionWhileDataFetchingTest.groovy

This is to prove that #1018 is not a problem
I realised we didn't have a test for this even though it worked

Added a test for 1018 to prove its not a problem

---

src/main/java/graphql/schema/Coercing.java

javadoc fix up

---

src/test/groovy/graphql/execution/defer/DeferredErrorSupportTest.groovy

I thought the code had a bug.  It doesnt but now we have a test that ensures it wont in the future
See #1040

Added extra tests to ensure a certain error behaviour

---

src/main/java/graphql/DirectivesUtil.java
src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/idl/SchemaGenerator.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeDirectivesChecker.java
src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/main/java/graphql/schema/idl/errors/DirectiveIllegalArgumentTypeError.java
src/main/java/graphql/schema/idl/errors/DirectiveIllegalLocationError.java
src/main/java/graphql/schema/idl/errors/DirectiveMissingNonNullArgumentError.java
src/main/java/graphql/schema/idl/errors/DirectiveRedefinitionError.java
src/main/java/graphql/schema/idl/errors/DirectiveUndeclaredError.java
src/main/java/graphql/schema/idl/errors/DirectiveUnknownArgumentError.java
src/main/java/graphql/schema/idl/errors/NonUniqueNameError.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeDirectivesCheckerTest.groovy
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

Added support for generating directives from SDL

---

src/main/antlr/GraphqlSDL.g4
src/test/groovy/graphql/parser/IDLParserTest.groovy

Allow empty body object type definitions

---

src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/test/groovy/graphql/execution/defer/CapturingSubscriber.groovy
src/test/groovy/graphql/execution/defer/DeferSupportIntegrationTest.groovy

This fixes the bug and adds a specific test for it

Bug with deferred fields being mixed up when resolved

---

src/main/java/graphql/schema/GraphQLTypeUtil.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/schema/GraphQLTypeUtilTest.groovy
src/test/groovy/graphql/validation/SpecValidation532Test.groovy
src/test/groovy/graphql/validation/SpecValidationSchema.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

Fixes the field merging to better follow the spec

---

src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

handle modified parent types (list and nonull) of fields correctly

bugfix issue 1115

---

src/main/java/graphql/language/Argument.java
src/main/java/graphql/language/ArrayValue.java
src/main/java/graphql/language/Document.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/SchemaDefinition.java
src/main/java/graphql/language/SelectionSet.java

this is supposed to be reverted in the future when we have good API for changing the Ast (not only one Node, but a whole query)

makes ast nodes mutable again for now

---

graphql-java-code-style.xml

No Milestone because it will not be released, just for development

update code style to always force curly braces in if for while

---

src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/FieldValueInfo.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/FieldValueInfoTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy

stable branch cherry pick of 1113

---

src/main/java/graphql/util/Traverser.java
src/test/groovy/graphql/util/TraverserTest.groovy

stable fix of PR 1141

---

src/main/java/graphql/schema/idl/SchemaGenerator.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Stable fix of pr 1150

---

src/main/java/graphql/execution/batched/UnbatchedDataFetcher.java
src/main/java/graphql/schema/AsyncDataFetcher.java
src/main/java/graphql/schema/DataFetcher.java
src/test/groovy/readme/DirectivesExamples.java

No longer forces the client code to wrap checked exceptions

DataFetcher declared to throw Exception

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy

fix handling of __typename in max query complexity calculation

---

src/main/java/graphql/schema/DataFetcher.java

mention DataFetcherResult in DataFetcher docs

---

src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLTypeVisitor.java
src/main/java/graphql/schema/GraphQLTypeVisitorStub.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/main/java/graphql/schema/SchemaUtil.java
src/test/groovy/graphql/TypeReferenceSchema.java
src/test/groovy/graphql/schema/SchemaUtilTest.groovy
src/test/groovy/graphql/schema/TypeTraverserTest.groovy

This both fixes #1208 and adds traversal support for directives as a general feature.
Still needs tests, which I'll add tomorrow.

Add support for traversing directives

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

stable fix of pr 1244

---

src/main/java/graphql/relay/SimpleListConnection.java
src/test/groovy/graphql/relay/SimpleListConnectionTest.groovy

Stable fix of pr 1205

---

src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy

Stable fix or pr 1255

---

src/main/java/graphql/UnresolvedTypeError.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/NonNullableFieldWasNullException.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/tracing/TracingSupport.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/main/java/graphql/schema/GraphQLTypeUtil.java
src/test/groovy/graphql/NonNullHandlingTest.groovy
src/test/groovy/graphql/TypeResolverExecutionTest.groovy
src/test/groovy/graphql/execution/ExecutionStepInfoTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy

The main breaking change here is that type is actually not automatically unwrapped anymore.

no special non null handling in ExecutionStepInfo

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java

no need for list of integers for storing complexity - integer as a sum is good enough

Improving complexity calculation

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationFieldFetchParameters.java
src/main/java/graphql/execution/instrumentation/tracing/TracingInstrumentation.java
src/main/java/graphql/execution/instrumentation/tracing/TracingSupport.java
src/main/java/graphql/relay/SimpleListConnection.java
src/main/java/graphql/schema/DataFetcher.java
src/main/java/graphql/schema/PropertyDataFetcher.java
src/main/java/graphql/schema/StaticDataFetcher.java
src/test/groovy/graphql/execution/instrumentation/TracingInstrumentationTest.groovy

Adds support for identifying trivial data fetchers and ignoring trivial fields in tracing

---

src/test/groovy/graphql/schema/GraphQLTypeReferenceTest.groovy

Added a regression test on re-use of type references

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/FieldCollector.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/validation/TraversalContext.java

Quick clean ups of SchemaUtil and the other singleton helpers

Cleaning up SchemaUtil usage

---

src/test/groovy/readme/DataFetchingExamples.java
src/test/groovy/readme/ExecutionExamples.java

This is the start of the "figure"markers.  I want to try then to reference these in the graphql-java-page doco text and hence try to keep them more up to date.

Started to add figure markers to code examples.

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ResolveType.java
src/main/java/graphql/execution/UnboxPossibleOptional.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/main/java/graphql/execution2/FetchedValueAnalyzer.java
src/main/java/graphql/execution2/ValueFetcher.java

move UnboxPossibleOptional into execution

use ResolveType everywhere and move it into execution package

---

src/main/java/graphql/execution2/FetchedValueAnalyzer.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java

Fixed up JavaDoc warnings

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy

You can now instrument a document and hence get a chance to rewrite it before it gets executed

Added the ability to instrument a document

---

src/main/java/graphql/language/AstPrinter.java

This is an enabler PR that will allow is to introduce a "mode" options field that allows for proper "compact" printing.
The maintains API backwards compat

Made AstPrinter non static in implementation but still static in call sequence

---

src/main/java/graphql/execution2/BatchedExecutionStrategy.java
src/main/java/graphql/execution2/DefaultExecutionStrategy.java
src/main/java/graphql/execution2/FetchedValue.java
src/main/java/graphql/execution2/FetchedValueAnalysis.java
src/main/java/graphql/execution2/FetchedValueAnalyzer.java

Just a quick internal cleanup:  FetchValueAnalysis was not fully immutable and modified from the outside of the analyzer.

cleanup FetchValueAnalysis

---

src/main/java/graphql/language/SelectionSet.java

make SelectionSet accept Collection<? extends Selection> instead List<Selection>

make SelectionSet accept Collection<? extends Selection>

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/main/java/graphql/execution/instrumentation/DocumentAndVariables.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy

This tweaks the unreleased ability to instrument a Document  and turns it into Document and variables

Added the ability to instrument document and variables

---

src/main/java/graphql/execution/nextgen/FetchedValueAnalysis.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalyzer.java
src/test/groovy/graphql/execution/nextgen/DefaultExecutionStrategyTest.groovy

If a data fetcher returns errors in their results, then they must be put into the fetch value analysis

Transfers errors from data fetches into the fetchvalues

---

src/main/java/graphql/execution/DataFetcherExceptionHandler.java
src/main/java/graphql/execution/DataFetcherExceptionHandlerParameters.java
src/main/java/graphql/execution/DataFetcherExceptionHandlerResult.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java
src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
src/test/groovy/graphql/execution/DataFetcherExceptionHandlerResultTest.groovy
src/test/groovy/graphql/execution/DataFetcherExceptionHandlerTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/readme/ExecutionExamples.java

now returns a result rather than relies on side effects

error handler changes

---

build.gradle
src/test/java/benchmark/BenchMark.java

This just puts JMH into the test class path so one can easily write a micro benchmark to test and idea.
Its not run continuously during builds.  Its just for exploration.

Adds the skeleton code for micro benchmarking.

---

src/main/java/graphql/cachecontrol/CacheControl.java
src/test/groovy/graphql/cachecontrol/CacheControlTest.groovy

This is support classes for following this spec
https://github.com/apollographql/apollo-cache-control

Adds Appollo CacheControl capability to graphql-java.

---

src/test/groovy/graphql/schema/idl/TestTripleQuotedCommentSupport.groovy

A test for Triple Quoted Strings in Introspection

---

src/main/java/graphql/ExecutionResultImpl.java

refactor(Execution result): Change order of fields inside Response

---

build.gradle

Back-port on stable branch of PR #1435.

Update antlr4 from 4.7.1 to 4.7.2

---

src/main/antlr/GraphqlCommon.g4
src/test/groovy/graphql/parser/ParserTest.groovy

Exponents can have positive exponents

---

src/main/java/graphql/Directives.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/StarWarsIntrospectionTests.groovy
src/test/groovy/graphql/execution/defer/DeferSupportIntegrationTest.groovy
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy

See #1399 
This got missed in 12.0 which is a pity but its will be released in 13.0 aka next version

Removed @defer as a default directive

---

src/main/java/graphql/parser/StringValueParsing.java
src/test/groovy/graphql/parser/StringValueParsingTest.groovy
src/test/groovy/graphql/schema/idl/TestTripleQuotedCommentSupport.groovy

See #1438
This is now implemented correctly in terms of the spec and takes the test cases from graphql-js and rejigs them for our code.

1438 - fixes problems with triple comment indenting

---

src/main/java/graphql/parser/StringValueParsing.java
src/test/groovy/graphql/parser/StringValueParsingTest.groovy

Backport the #1438 buf to 9x

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

 directive definition printing

---

src/main/java/graphql/validation/rules/ProvidedNonNullArguments.java
src/test/groovy/graphql/validation/rules/ProvidedNonNullArgumentsTest.groovy

This fixes a bug where on non null but defaulted directive arguments
See #1470

non null directive args with defaults can be missing bug

---

src/main/java/graphql/validation/rules/ProvidedNonNullArguments.java
src/test/groovy/graphql/validation/rules/ProvidedNonNullArgumentsTest.groovy

non null directive args with defaults can be missing - backport

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/cachecontrol/CacheControl.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/defer/DeferredCall.java
src/test/groovy/graphql/ExecutionResultImplTest.groovy

Expose if data is present in ExecutionResult

---

src/main/java/graphql/cachecontrol/CacheControl.java

Refactor that is enabled by #1491.
It's just one extra commit on top of #1491, but I thought it would be easier to do the review in a separate PR

Refactor CacheControl

---

src/main/java/graphql/language/InlineFragment.java

Make InlineFragment implement DirectivesContainer (as it was missed)

---

src/main/java/graphql/schema/idl/TypeInfo.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/idl/TypeInfoTest.groovy

Needed so in Nadel we dont repeat all the wrapping decoration code

Adds the ability to rename via the TypeInfo object

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

Fixes #1558, propagate LocalContext on non-DataFetcherResult

---

src/main/java/graphql/schema/GraphQLCodeRegistry.java

Ability to merge GraphQLCodeRegistries

---

src/main/java/graphql/execution/ExecutionContext.java

backport of 1525 - performant error path tracking

---

src/main/antlr/GraphqlCommon.g4
src/main/antlr/GraphqlOperation.g4
src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/IDLParserTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy

fixes also enum value names and fragment names
this fixed #1523

allow special names to be uses as field name

---

src/main/java/graphql/execution/nextgen/result/ExecutionResultNode.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/util/NodeMultiZipper.java
src/main/java/graphql/util/NodeZipper.java
src/main/java/graphql/util/Traverser.java
src/main/java/graphql/util/TreeTransformer.java
src/main/java/graphql/util/TreeTransformerUtil.java

various performant improvements

handle transformations with large zippers better/more performant

---

src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/execution/nextgen/result/ResultNodesUtil.java

This are minor tweaks - they turn up in a profiler under hot load but they are not major contributors in any way

Some minor minor perf tweaks on result node creation

---

src/main/java/graphql/language/AstTransformer.java
src/main/java/graphql/util/DefaultTraverserContext.java
src/main/java/graphql/util/ParallelTraverser.java
src/main/java/graphql/util/TraverserContext.java
src/main/java/graphql/util/TraverserState.java
src/main/java/graphql/util/TreeTransformer.java
src/main/java/graphql/util/TreeTransformerUtil.java
src/test/groovy/graphql/language/AstTransformerTest.groovy
src/test/groovy/graphql/util/ParallelTraverserTest.groovy

Adds a general parallel traverser (depth first, parallel)

Parallel traverser

---

src/main/java/graphql/language/AstTransformer.java
src/main/java/graphql/util/DefaultTraverserContext.java
src/main/java/graphql/util/TreeParallelTransformer.java
src/main/java/graphql/util/TreeParallelTraverser.java
src/main/java/graphql/util/TreeTransformer.java
src/main/java/graphql/util/TreeTransformerUtil.java
src/test/groovy/graphql/util/TreeParallelTransformerTest.groovy
src/test/groovy/graphql/util/TreeParallelTraverserTest.groovy

Adds a tree parallel transformer specific to transforming a tree in parallel.

add tree parallel transformer

---

src/main/java/graphql/ExceptionWhileDataFetching.java
src/main/java/graphql/SerializationError.java
src/main/java/graphql/TypeMismatchError.java
src/main/java/graphql/UnresolvedTypeError.java

Increasing the readability of toString

Add commas to separate logical parts of toString representations

---

src/main/java/graphql/Scalars.java
src/test/groovy/graphql/ScalarsIDTest.groovy

a BigInteger should be usable as an ID value

Support coercing a BigInteger into an ID Scalar

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/schema/SchemaPrinterComparatorsTest.groovy

Addressing the issue https://github.com/graphql-java/graphql-java/issues/1623.

Print directive argument only when it has a value

---

CONTRIBUTING.md
build.gradle

There are several security vulnerabilities in jackson-databind. (see details [here](https://github.com/mlvandijk/graphql-java.git))
This PR updates to the latest available version of databind.
In addition, fixed a typo in the `CONTRIBUTING.md`. (Let me know if you prefer separate PRs)

Update jackson-databind due to security vulnerabilities

---

src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java
src/test/groovy/graphql/schema/DelegatingDataFetchingEnvironmentTest.groovy

Related to #1663 
Makes it easier to wrap DFEs

A DelegatingDataFetcherEnvironment which makes it easier to wrap a DFE

---

src/test/groovy/graphql/util/TreeParallelTraverserTest.groovy

added a second one which doesn't rely on threads

fix parallel traverser test: the parallel test fails on travis,

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/schema/DataFetchingEnvironment.java
src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java
src/test/groovy/graphql/ContextPassingDataFetcher.groovy

local context is now null by default on top level fields

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLNamedDescriptionType.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLScalarType.java
src/main/java/graphql/schema/GraphQLUnionType.java

improve introspection performance by using explicit DataFetcher for name and description.
Introduce GraphQLNamedDescriptionType for types with name and description.

improve introspection performance 

---

src/main/java/graphql/execution/DataFetcherResult.java
src/test/groovy/graphql/execution/DataFetcherResultTest.groovy

Added DataFetcherResult#transform

---

src/main/java/graphql/schema/Coercing.java

Encountered some small grammatical errors while going through the source code.

Fix small grammatical errors

---

src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

GraphQLDirective didn't have a reference to DirectiveDefinition so far.

capture directive definition when building a GraphQLSchema from SDL

---

src/main/java/graphql/util/Traverser.java

Not a breaking change, because it was never released AND internal only

remove not released and unused feature

---

src/main/java/graphql/schema/diff/DiffCategory.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy

This is follow work to #1610 incorporating the idea that we have 2 enums for deprecation added and deprecation removed

Follow up work on SchemaDiff to makes it DEPRECATION added or removed

---

src/main/java/graphql/execution/Execution.java
src/test/groovy/graphql/execution/ExecutionTest.groovy

Fix if strategy is updated during instrumenting execution context

backport of #1648: Strategy update didn't take effect 

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

description of directives arguments are captured correctly from SDL

backport of #1722: description of directives arguments are captured

---

src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

capture directive definition when building a GraphQLSchema from SDL

backport of #1723: capture directive definition when building Schema

---

src/main/java/graphql/language/AstValueHelper.java
src/main/java/graphql/schema/PropertyDataFetcher.java
src/main/java/graphql/schema/PropertyDataFetcherHelper.java
src/test/groovy/graphql/language/AstValueHelperTest.groovy

This now shares the POJO lookup code for turning Java POJO values into AST elements along with the PropertyDataFecther via a new extracted class

AST code uses PropertyFetching techniques 

---

src/main/java/graphql/GraphqlErrorException.java
src/main/java/graphql/schema/CoercingParseLiteralException.java
src/main/java/graphql/schema/CoercingParseValueException.java
src/main/java/graphql/schema/CoercingSerializeException.java

This is useful for error specialisations as well addressing as #1690 
I am still waiting on Kotlin experts on why this helps

Introduce a GraphqlErrorException for Kotlin users and generally.

---

src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/ParserTest.groovy

This is for Nadel to be able to use new ANTLR integration

Make Parser public and allow for custom antlr parser implementation for subclasses

---

build.gradle

Its only a test dep but #1800 said to.  OK - I am not sure who that is (seems bot generated) but hey

Update of jetty dep

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/UniqueVariableNamesRule.java
src/test/groovy/graphql/validation/rules/UniqueVariableNamesRulerTest.groovy

New Validation rule: unique_variable_names

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/validation/rules/KnownDirectives.java
src/test/groovy/graphql/TestUtil.groovy

remove flags which were removed from the spec: https://github.com/graphql/graphql-spec/pull/152

remove flags on GraphQLDirective 

---

src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy

Fixed a copy pasta bug from #1818

---

src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/DeferredMustBeOnAllFields.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/validation/rules/NoFragmentCyclesTest.groovy

Fixes a stack over flow problem in the validation rules

---

src/main/java/graphql/schema/FieldCoordinates.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/test/groovy/graphql/schema/FieldCoordinatesTest.groovy

Description:
Implemented versions of FieldCoordinates creation methods that
do not perform validation in order to optimize performance.  This is
to allow for cases that need to create field coordinates that are
already known to be valid and need to optimize for performance.
Changes:
* Added optmized FieldCoordinates.coordinates method
* Added optmized FieldCoordinates.systemCoordinates method
Unit Tests:
* Added FieldCoordinates.groovy file to test all cases for
FieldCoordinates creation

#1845: Implemented optimized FieldCoordinates creation methods

---

src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java
src/test/groovy/graphql/schema/idl/TypeDefinitionRegistryTest.groovy

Added the ability to remove an extension by key and added a check that if the list is empty to remove that row from the map. Updated the tests to test for single and multiple values

ISSUE-1885: Add impl to remove values by key

---

src/main/java/graphql/ExecutionInput.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/test/groovy/graphql/Issue1768.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy

Here's the push request it's a proposal for the issue #1768

Issue #1768 ExecutionInput: allow to set value a top level

---

src/main/java/graphql/schema/PropertyDataFetcherHelper.java

This PR provides a more efficient data fetcher so that public field strategy does not have to perform  reflective lookups when we have already cached the method / field
So given:
1. Use reflection to find a publicly accessible getter method - if successful store result in the method cache to save on future reflection operations
1. If (1) fails reflection is again used to find a non-public getter method - if successful the result of this is stored in the method cache to save on future reflection operations
1. If (2) fails reflection is used to find a publicly accessible field - if successful the result is stored in field cache.
1. Finally, if (1), (2), or (3) fail - the field is stored in a negative cache, and null is returned
We now will skip steps 1) and 2) for public fields and we will …

A more efficient PropertyDataFetcher

---

src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/UniqueArgumentNamesRule.java
src/test/groovy/graphql/validation/SpecValidationSchema.java
src/test/groovy/graphql/validation/rules/UniqueArgumentNamesTest.groovy

New validation rule: unique_argument_names

---

src/main/java/graphql/GraphQLException.java
src/main/java/graphql/analysis/FieldComplexityEnvironment.java
src/main/java/graphql/analysis/QueryVisitorFieldArgumentEnvironmentImpl.java
src/main/java/graphql/analysis/QueryVisitorFieldArgumentInputValueImpl.java
src/main/java/graphql/analysis/QueryVisitorFieldEnvironmentImpl.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/NonNullableFieldWasNullException.java

Stable fix of pr 1792

---

src/main/java/graphql/schema/idl/CombinedWiringFactory.java
src/test/groovy/graphql/schema/idl/WiringFactoryTest.groovy

stable fix port of 1797

---

src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy

Fixed a copy pasta bug from #1818 (#1821)

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

stable fix of pr 1907

---

src/main/java/graphql/schema/idl/SchemaTypeExtensionsChecker.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

1898: Fix field redefinition check in extensions

---

src/main/java/graphql/schema/validation/TypesImplementInterfaces.java
src/test/groovy/graphql/schema/validation/TypesImplementInterfacesTest.groovy

Implementing type **can** declare more field arguments than in the implemented interface given that the extra arguments are optional (aka not non-null).
fixes: #1897

1897: Fix field argument validation in SchemaValidator

---

src/test/groovy/graphql/LocalContextTest.groovy

add test for local context and aliases

---

src/main/java/graphql/ErrorType.java
src/main/java/graphql/execution/NonNullableFieldWasNullError.java
src/main/java/graphql/execution/NonNullableFieldWasNullException.java
src/test/groovy/graphql/GraphQLErrorTest.groovy
src/test/groovy/graphql/execution/NonNullableFieldWasNullExceptionTest.groovy
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy

This updates the error message to make a cryptic situation that is KNOWN to confuse people more clear.
I also made the error type is own since its really a special type of error

Updated the error message for the non null exception AND create its own error type

---

src/main/java/graphql/language/VariableDefinition.java
src/test/groovy/graphql/execution/directives/VariableDirectiveTest.groovy

make directives to be children of VariableDefinition.

fix variable directive

---

src/main/java/graphql/execution/nextgen/BatchedExecutionStrategy.java
src/main/java/graphql/execution/nextgen/DefaultExecutionStrategy.java
src/main/java/graphql/execution/nextgen/Execution.java
src/main/java/graphql/execution/nextgen/ExecutionHelper.java
src/main/java/graphql/execution/nextgen/ExecutionStrategy.java

NG Code is not public, therefore non breaking, non user impact.

refactor NG ExecutionStrategy to be more general

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This came from discussions in the Sprectrum chat where someone want to be able to not print certain elements
Honestly schema transform before print is one way and this is a another more simple way

Added the ability to provide a predicate on schema printing per schema element

---

src/test/groovy/graphql/language/AstSignatureTest.groovy

It works but this adds and extra test case after I  thought we had  a problem - but we dont

An extra test case for AST signature code

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/language/NullValue.java

reuse variableDefinition.getDefaultValue() and remove unused import

---

src/main/java/graphql/execution/FieldCollector.java

In `FieldCollector`, take `Set` as track of fragmentNames which is already visited.

take  Set as track of fragmentNames which is already visited.

---

src/main/java/graphql/schema/PropertyDataFetcherHelper.java

Include class loader in caching key

---

src/main/java/graphql/Assert.java

pre-compile valid name Pattern to speed up `assertValidName`

Pre-compile valid name pattern

---

src/main/java/graphql/analysis/NodeVisitorWithTypeTracking.java
src/test/groovy/graphql/analysis/MaxQueryComplexityInstrumentationTest.groovy

Backport fix #1865 on 14.x LTS

Backport of #1865: Do not visit a variable definition value node

---

build.gradle

(cherry picked from commit 9ede5fed88e7a3a1060f016b2b35f9514126b9bb)

Backport of fix #1802: Update fo jetty

---

src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/DeferredMustBeOnAllFields.java
src/test/groovy/graphql/TestUtil.groovy
src/test/groovy/graphql/validation/rules/NoFragmentCyclesTest.groovy

(cherry picked from commit d9d29d9c3464b4d2894dc8c71c5521a6f6fda2c5)

Backport of fix #1836: Fixes a stack over flow problem in the validation rules

---

src/main/java/graphql/introspection/IntrospectionResultToSchema.java
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

Determine whether isDataPresent in createSchemaDefinition(ExecutionResult) is false.
Details for this PR in #2034 .

determine whether isDataPresent in createSchemaDefinition(ExecutionResult) is false

---

src/main/java/graphql/language/EnumTypeDefinition.java
src/main/java/graphql/language/EnumTypeExtensionDefinition.java
src/main/java/graphql/language/EnumValueDefinition.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/language/FieldDefinition.java
src/main/java/graphql/language/FragmentDefinition.java
src/main/java/graphql/language/FragmentSpread.java
src/main/java/graphql/language/InlineFragment.java
src/main/java/graphql/language/InputObjectTypeDefinition.java
src/main/java/graphql/language/InputObjectTypeExtensionDefinition.java
src/main/java/graphql/language/InputValueDefinition.java
src/main/java/graphql/language/InterfaceTypeDefinition.java
src/main/java/graphql/language/InterfaceTypeExtensionDefinition.java
src/main/java/graphql/language/ObjectTypeDefinition.java
src/main/java/graphql/language/ObjectTypeExtensionDefinition.java
src/main/java/graphql/language/OperationDefinition.java
src/main/java/graphql/language/ScalarTypeDefinition.java
src/main/java/graphql/language/ScalarTypeExtensionDefinition.java
src/main/java/graphql/language/SchemaDefinition.java
src/main/java/graphql/language/SchemaExtensionDefinition.java
src/main/java/graphql/language/UnionTypeDefinition.java
src/main/java/graphql/language/UnionTypeExtensionDefinition.java

Make the builder classes which have directive implement NodeDirectivesBuilder.

Replace NodeBuilder with NodeDirectivesBuilder

---

src/main/java/graphql/DirectivesUtil.java
src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/language/Directive.java
src/main/java/graphql/language/DirectivesContainer.java
src/main/java/graphql/language/InlineFragment.java
src/main/java/graphql/language/NodeUtil.java
src/main/java/graphql/language/SchemaDefinition.java
src/main/java/graphql/schema/GraphQLDirectiveContainer.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java

I notice that some methods will create unnessary HashMap, it seems to be avoid.

remove unnecessary Map

---

build.gradle

#2006 - adding an automatic module name

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/introspection/IntrospectionDataFetcher.java
src/test/groovy/graphql/execution/instrumentation/TracingInstrumentationTest.groovy

Mark IntrospectionDataFetcher as TrivialDataFetcher, do not trace introspection operation

---

src/main/java/graphql/execution/ExecutionStrategy.java

allowing more customizations for ExecutionStrategy

---

src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Provide more details about the usage of `EnumValuesProvider` and its implementations. #2061

Add a test to explain how to use MapEnumValuesProvider

---

src/test/groovy/graphql/schema/GraphQLTypeVisitorStubTest.groovy

unignoring unit test

---

src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/language/AstPrinter.java
src/main/java/graphql/language/EnumTypeExtensionDefinition.java
src/main/java/graphql/language/InputObjectTypeExtensionDefinition.java
src/main/java/graphql/language/InterfaceTypeExtensionDefinition.java
src/main/java/graphql/language/ObjectTypeExtensionDefinition.java
src/main/java/graphql/language/ScalarTypeExtensionDefinition.java
src/main/java/graphql/language/UnionTypeExtensionDefinition.java
src/test/groovy/graphql/language/AstPrinterTest.groovy
src/test/groovy/graphql/language/AstTransformerTest.groovy

changing child node.
Backport onto 14.x.
(cherry picked from commit 3998b0dab816b232cd9de8216169d0bbaab52a83)

Backport 14.x: Fix AstTransformer extension being converted to base type when ... #2056

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Issue: https://github.com/graphql-java/graphql-java/issues/2053

Avoids ArrayIndexOutOfBoundsException for description of only newline (#2053)

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

Fix getArgumentValuesImpl according by spec.CoerceArgumentValues()

---

src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncExecutionStrategy.java
src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/test/groovy/graphql/Issue1768.groovy

- Remove unused import;
- Remove redundant method.

Remove unused import; Remove redundant method

---

src/main/java/graphql/execution/Async.java
src/main/java/graphql/execution/ExecutionStrategy.java

As we agreed, a separate PR for removal of some methods  @bbakerman @andimarek

removing unused methods

---

build.gradle

Tested in a standalone project

Fixes the missing guava maths classes

---

build.gradle

Fixes module name

---

src/main/java/graphql/DirectivesUtil.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/schema/idl/SchemaTypeExtensionsChecker.java
src/test/groovy/graphql/Issue2114.groovy

Allow usage of repeatable directives on extensions

---

build.gradle

Following instructions here:
https://github.com/artyushov/idea-jmh-plugin/issues/13#issuecomment-687805558

upgrading jmh to 1.25

---

src/main/java/graphql/Directives.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/idl/DirectiveInfo.java
src/main/java/graphql/util/Anonymizer.java
src/test/groovy/graphql/util/AnonymizerTest.groovy

Improve several aspects: arguments, variables, operation name ...

Improve Anonymizer

---

src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java

Moved supplier of locked Query Tree outside synchronised call

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/FieldCollector.java
src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/language/Field.java
src/main/java/graphql/normalized/FieldCollectorNormalizedQuery.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java

This method has several definitions in a lot of places. It is also a good API for advanced users.
@andimarek  @bbakerman 
I'm not sure about the name: any suggestion is welcome :-)

introducing Field.getResultKey()

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/main/java/graphql/schema/transform/FieldVisibilitySchemaTransformation.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/transform/FieldVisibilitySchemaTransformationTest.groovy

The `GraphQLSchema` holds the list of types. 
For the purpose of this PR, we will differentiate types into two categories. **connected** and **detached** types.
**Connected** types are types that are connected to the root operation types, meaning there is at least one path that leads from the root operation types entry points (Query, Mutation, Subscription) to each of the connected types. 
**Detached** types are types that are not connected to the root operations types.
All the detached types are held in the `GraphQLSchema.additionalTypes` field.
All the connected types AND the additional types are held in the `GraphQLSchema.typeMap` field.
I noticed that in certain cases, **detached** types are not detected properly and end up only in the `GraphQLSchema.typeMap` instead of also being in …

Fix nested detached types were not added to additionalTypes

---

src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java

Variable used for double-checked locking should be volatile

---

src/main/java/graphql/schema/idl/SchemaTypeExtensionsChecker.java
src/test/groovy/graphql/execution/directives/RepeatableDirectivesTest.groovy

Ensure repeatable directive on extend type run correctly

---

src/main/java/graphql/schema/idl/SchemaPrinter.java
src/test/groovy/graphql/Issue2141.groovy
src/test/groovy/graphql/schema/SchemaPrinterComparatorsTest.groovy

Remove redundant parenthesis for directive on FIELD_DEFINITION

---

src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/schema/PropertyFetchingImpl.java

Hello @bbakerman @andimarek,
I did some more profiling with YourKit and found these new "opportunities":
JMH benchmark:
master
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  47.091 ± 1.469  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime      avgt   15  21.572 ± 1.113  ms/op
```
with FetchedValue fix
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  47.069 ± 0.646  ops/s
BenchMark.benchMarkSimpleQueriesAvgTime      avgt   15  20.776 ± 0.804  ms/op
```
with CacheKey fix
```
BenchMark.benchMarkSimpleQueriesThroughput  thrpt   15  52.207 ± …
```

more micro optimizations

---

src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLTypeCollectingVisitor.java
src/main/java/graphql/schema/GraphQLTypeReference.java
src/main/java/graphql/schema/GraphQLTypeVisitor.java
src/main/java/graphql/schema/SchemaTransformer.java
src/main/java/graphql/schema/SchemaUtil.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

This changes the SchemaTransformer so that type references are fixed up for changed types.

Schema Transformer will fix up type references to changed types

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

Add gradle wrapper validation action

---

src/main/java/graphql/execution/ExecutionStrategy.java

Make `completeValueForNull` protected, so that it can be override in subclass.

Change access to method `completeValueForNull` to protected.

---

src/main/java/graphql/execution/ValuesResolver.java
src/test/groovy/graphql/NullVariableCoercionTest.groovy

Bug fix for complex input types with non null input fields that have default values

---

src/test/groovy/graphql/cachecontrol/CacheControlTest.groovy

minor fix for groovy test

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy

Fix AstPrinter throws on empty description

---

src/main/java/graphql/introspection/IntrospectionWithDirectivesSupport.java
src/test/java/graphql/introspection/IntrospectionWithDirectivesSupportTest.groovy

This is a better reflection of the type intentions
```
_DirectiveArgument {
name : String!
value : String!
}
```

Applied Directives now only show argument values IF there is a value set

---

src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/normalized/NormalizedInputValue.java
src/main/java/graphql/normalized/NormalizedQuery.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLSchema.java

The command line is now CLEAN from javadoc warnings with this change

Cleans up JavaDoc warnings

---

build.gradle

Addresses #2350 - add git working tree check to build file

Fix issue building zip and gzip downloads

---

src/main/java/graphql/execution/nextgen/Common.java

What about to handle throw an exception using the Optional Class form java jdk ?

Change the way throwing an exception using Optional

---

.github/workflows/master.yml
README.zh_cn.md
gradle.properties

Addresses #2307.
This PR cleans up references to bintray.

Remove references to bintray

---

src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Scalars can get descriptions from DSL

---

src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy

Shows that
https://github.com/graphql-java/graphql-java/issues/2238
and
https://github.com/graphql-java/graphql-java/issues/2290
are fixed on master if not in 16

show that recursive arguments on directives can compile to schema

---

src/main/java/graphql/schema/GraphQLDirectiveContainer.java
src/test/groovy/graphql/schema/GraphQLDirectiveTest.groovy
src/test/groovy/readme/SchemaTransformExamples.java

A couple of times of late I was wanting a boolean "element has a directive" method.  Here it is

has directive support

---

src/main/java/graphql/ExperimentalApi.java

Nothing uses it yet but now available to be used

@ExperimentalApi support

---

build.gradle

Updated the antlr runtime and the antlr generator to version 4.9.2

Updated antlr to version 4.9.2

---

build.gradle
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/instrumentation/nextgen/InstrumentationExecutionParameters.java
src/main/java/graphql/execution/instrumentation/parameters/InstrumentationExecutionParameters.java
src/test/groovy/readme/DataLoaderBatchingExamples.java

I also updated the doco : https://github.com/graphql-java/graphql-java-page/pull/53
I also fixed some javadoc warnings which trigger me

Upgrade to 3.0.0 of data loader

---

src/main/java/graphql/schema/idl/ArgValueOfAllowedTypeChecker.java
src/test/groovy/graphql/schema/idl/SchemaGeneratorTest.groovy
src/test/groovy/graphql/schema/idl/SchemaTypeCheckerTest.groovy

Fixes scalars being able to accept any literal in SDL

---

src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/parser/SDLParserTest.groovy

Right now there is only 1 option but another maybe to remove SourceLocation on AST elements and then we will wish we had a holder options object

Made a ParserOptions class so we can have more options later

---

src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/util/FpKit.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy
src/test/groovy/graphql/execution/ValuesResolverTestLegacy.groovy
src/test/groovy/graphql/util/FpKitTest.groovy

If a value is an array, we create an iterable and then other code handles it like existing lists
See #2432

Handle arrays in the value resolver

---

src/test/groovy/graphql/schema/DataFetchingFieldSelectionSetImplTest.groovy

See https://github.com/graphql-java/graphql-java/issues/2381

proves selection sets work in mutations

---

src/test/java/benchmark/SchemaBenchMark.java

A schema creation benchmark

---

src/main/java/graphql/language/AstSignature.java
src/test/groovy/graphql/language/AstSignatureTest.groovy

Privacy safe support logging versus signatures

---

src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java
src/main/java/graphql/execution/reactive/SubscriptionPublisher.java
src/test/groovy/graphql/execution/SubscriptionExecutionStrategyTest.groovy

The Publisher from Subscription fields now has supported API shape

Add an API class that is returned by the subscriptions

---

src/main/java/graphql/schema/SchemaTransformer.java

by precalculating zippers for a parent and therefore avoiding iterating all the zippers every time in zippersWithSameParent

improve schema transformer performance 

---

src/main/java/graphql/language/Document.java
src/test/groovy/graphql/language/DocumentTest.groovy

This has annoyed me forever, and I want to fix it

Better definition access on Document

---

src/main/java/graphql/schema/FieldCoordinates.java
src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy

I had cause to look up a  field definition in a  schema by FieldCorodinates
hence this PR

Allow getting a field in the schema by FieldCoordinates

---

src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Improves the AST compilation for normalised fields - to make it more human ready

groups together fields into the one object type during AST compilation

---

build.gradle
src/test/groovy/graphql/execution/instrumentation/DataLoaderCacheCanBeAsyncTest.groovy
src/test/groovy/readme/DataLoaderBatchingExamples.java

This updates graphql-java up to 3.10 of data loader

Upgrading back to dataloader 3.2

---

src/main/java/graphql/normalized/ExecutableNormalizedOperation.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

Add operation name to ExecutableNormalizedOperation

---

src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java
src/main/java/graphql/analysis/QueryComplexityInfo.java

Add InstrumentationValidationParameters to QueryComplexityInfo

---

src/main/java/graphql/execution/SimpleDataFetcherExceptionHandler.java

See https://github.com/graphql-java/graphql-java/issues/2564

A protected method for logging

---

src/main/java/graphql/schema/idl/SchemaPrinter.java

https://github.com/graphql-java/graphql-java/runs/4145957689?check_suite_focus=true

fix broken build

---

src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

My IDE keeps freezing when I open GraphQL Java, so I used the IDE without the smart features to write this code… felt like I was sent 10 years back in time. Let me know if something is wrong.

Avoid printing inline fragment if there is no conditional type

---

src/main/java/graphql/analysis/QueryTraverser.java
src/main/java/graphql/collect/ImmutableKit.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalysis.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java
src/main/java/graphql/introspection/IntrospectionWithDirectivesSupport.java
src/main/java/graphql/normalized/ENFMerger.java
src/main/java/graphql/relay/Connection.java
src/main/java/graphql/schema/GraphQLCodeRegistry.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/SchemaTransformer.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/main/java/graphql/schema/idl/ScalarInfo.java
src/main/java/graphql/schema/idl/SchemaPrinter.java
src/main/java/graphql/schema/idl/SchemaTypeChecker.java
src/main/java/graphql/util/TraverserContext.java
src/main/java/graphql/util/TreeTransformerUtil.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java

Hi @andimarek @bbakerman,
please accept this small contribution, after a long time ... :-)

fix typos in javadoc

---

src/main/java/graphql/language/FloatValue.java
src/main/java/graphql/language/IntValue.java
src/main/java/graphql/language/ObjectField.java
src/main/java/graphql/language/StringValue.java
src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java

Hi again @andimarek  @bbakerman, 
another small contribution: isEqualTo implementation was overly complex and hard to read...

Simplify some isEqualTo implementations

---

src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
src/main/java/graphql/execution/instrumentation/dataloader/LevelMap.java
src/test/groovy/graphql/execution/instrumentation/dataloader/LevelMapTest.groovy
src/test/java/benchmark/IntMapBenchmark.java

Naming fix up to IntMap

---

src/main/java/graphql/language/AstPrinter.java
src/test/groovy/graphql/language/AstPrinterTest.groovy

Let me know if we should add any other tests.

Fix AstPrinter trimming blank string values

---

src/main/java/graphql/Directives.java
src/main/java/graphql/introspection/Introspection.java

Use correct defaultValue methods.

use new defaultValue method

---

build.gradle
src/test/groovy/graphql/JvmSpecificTest.groovy

See https://github.com/graphql-java/graphql-java/issues/2559

This uses -parameters as javac options

---

src/main/java/graphql/GraphqlErrorBuilder.java
src/test/groovy/graphql/GraphqlErrorBuilderTest.groovy
src/test/groovy/readme/ReadmeExamples.java

While using this builder I had occasion to derive from it so I could make a special specific graphql error class.
This helps with that by making the builder be designed to derived from or it can be used as is

This allows you to derive new classes from the error builder class

---

src/main/java/graphql/TypeResolutionEnvironment.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ResolveType.java
src/main/java/graphql/execution/TypeResolutionParameters.java
src/main/java/graphql/execution/nextgen/ExecutionStrategyUtil.java
src/main/java/graphql/execution/nextgen/FetchedValueAnalyzer.java
src/test/groovy/graphql/TypeResolutionEnvironmentTest.groovy
src/test/groovy/graphql/TypeResolverExecutionTest.groovy

And also cleaned up TypeResolutionEnvironment.java / TypeResolutionParameters.java a bit since there was lots of repeated code and really they should be merged at some point
See https://github.com/graphql-java/graphql-java/issues/2693

Added in local context to TypeResolutionEnvironment

---

src/main/java/graphql/schema/validation/InputAndOutputTypesUsedAppropriately.java
src/main/java/graphql/schema/validation/SchemaValidationErrorType.java
src/main/java/graphql/schema/validation/SchemaValidator.java
src/test/groovy/graphql/schema/validation/InputAndOutputTypesUsedAppropriatelyTest.groovy
src/test/groovy/graphql/schema/validation/SchemaValidatorTest.groovy

https://github.com/graphql-java/graphql-java/issues/2656

Validation of input and output types only in the right context

---

src/main/java/graphql/GraphqlErrorBuilder.java
src/test/groovy/graphql/GraphqlErrorBuilderTest.groovy

See https://github.com/graphql-java/graphql-java/issues/2637

Allows nullable error attributes in GraphqlErrorBuilder

---

src/main/java/graphql/execution/DataFetcherResult.java
src/test/groovy/graphql/execution/DataFetcherResultTest.groovy

Add clearErrors method to Builder in DataFetcherResult

---

src/main/java/graphql/GraphqlErrorBuilder.java

ErrorBuilder<?> does not work with Kotlin

---

build.gradle

memory allocation / no ops performance fixes

Upgrade dataloader to 3.1.2

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/instrumentation/SimpleInstrumentationContext.java
src/test/groovy/graphql/execution/instrumentation/InstrumentationTest.groovy
src/test/groovy/graphql/execution/instrumentation/TestingExecutionStrategyInstrumentationContext.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentContext.groovy
src/test/groovy/graphql/execution/instrumentation/TestingInstrumentation.groovy

See #1620 and #2722
This was missing from the very first placee we start

Added a missing onDispatch to the beginExecution 

---

src/main/java/graphql/Internal.java
src/main/java/graphql/schema/idl/errors/SchemaProblem.java

Change SchemaProblem from @Internal to @PublicApi

---

src/main/java/graphql/execution/ConditionalNodes.java
src/main/java/graphql/execution/MergedField.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/main/java/graphql/util/FpKit.java
src/test/java/benchmark/NQBenchmark1.java
src/test/java/benchmark/OverlappingFieldValidationBenchmark.java

```
Baseline : 
NQBenchmark.benchMarkThroughput  thrpt    9  58179.108 ± 3248.527  ops/s
NQBenchmark.benchMarkAvgTime      avgt    9      0.022 ±    0.011  ms/op
Progress:
NQBenchmark1.benchMarkThroughput  thrpt    9  60097.926 ± 2723.146  ops/s
NQBenchmark1.benchMarkAvgTime      avgt    9      0.016 ±    0.001  ms/op
Final : 
NQBenchmark1.benchMarkThroughput  thrpt    9  61725.227 ± 2766.171  ops/s
NQBenchmark1.benchMarkAvgTime      avgt    9      0.016 ±    0.001  ms/op
```

This is some performance optimisations for NormalisedOperations

---

src/main/java/graphql/schema/DelegatingDataFetchingEnvironment.java

DelegatingDataFetchingEnvironment was missing Deprecated and Override annotations.

Add missing annotations in DelegatingDataFetchingEnvironment

---

src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/UnicodeUtil.java

Make some static fields final, and avoid unnecessary boxing in UnicodeUtils.

Make some static fields final

---

src/main/java/graphql/normalized/VariableAccumulator.java
src/test/groovy/graphql/normalized/VariableAccumulatorTest.groovy

Collector.toMap will not allow null values

Changed VariableAccumulator so it can represent itself with null values

---

src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java

@bbakerman @andimarek hi guys :-)
just proposing a minor simplification in FieldLevelTrackingApproach#getCountForList. What do you think?

simplify FieldLevelTrackingApproach

---

src/main/java/graphql/normalized/ExecutableNormalizedField.java
src/main/java/graphql/schema/GraphqlDirectivesContainerTypeBuilder.java
src/main/java/graphql/schema/idl/RuntimeWiring.java

This is an OCD thing- but I hate the command line warnings these missing things produced

JavaDoc fix ups - stop warnings on command line

---

README.md
README.zh_cn.md

* Add MIT license badge
* Add snapshot release badge
* filter release badge to latest version

docs: readme updates

---

.github/workflows/pull_request.yml

When a PR is raised against the bugfix (18.x) branch, run the usual pipeline

Run pipeline on bugfix PRs

---

src/test/groovy/graphql/parser/ParserTest.groovy

I failed to cleanup a static test set call

Test stability

---

src/test/java/benchmark/DFSelectionSetBenchmark.java

A benchmark of DF selection sets

DF SelectionSet Benchmark

---

src/main/java/graphql/ParseAndValidate.java
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/SafeTokenSource.java
src/main/java/graphql/schema/idl/SchemaParser.java
src/test/groovy/graphql/parser/BadParserSituations.java
src/test/groovy/graphql/parser/ParserOptionsTest.groovy
src/test/groovy/graphql/parser/ParserTest.groovy
src/test/groovy/graphql/parser/SafeTokenSourceTest.groovy
src/test/groovy/graphql/schema/idl/SchemaParserTest.groovy

[…. (#2892)](https://github.com/graphql-java/graphql-java/pull/2892) ported to 18.x

18.x port - Stop DOS attacks by making the lexer stop early on evil input

---

src/test/groovy/readme/ExecutionExamples.java

Already fixed on the documentation page https://github.com/graphql-java/graphql-java-page/pull/95
This PR is to check in the code example

Fix up field visibility doco example

---

src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

we had a report that scalar renaming was not working - so I wrote a quick test - since it might be useful to keep - here it is
I had a quick look around and could not see a specific test so here is one

We can rename scalar types

---

src/main/java/graphql/schema/transform/FieldVisibilitySchemaTransformation.java
src/test/groovy/graphql/schema/transform/FieldVisibilitySchemaTransformationTest.groovy

Fixes a bug that happened when the field visibility transformation was applied to a schema that has some types reachable only via directive definitions.

Fix field visibility bug with enum with enum args

---

src/main/java/graphql/schema/GraphQLAppliedDirectiveArgument.java
src/main/java/graphql/util/Breadcrumb.java
src/main/java/graphql/util/NodeLocation.java
src/test/groovy/graphql/schema/SchemaTransformerTest.groovy

See  https://github.com/graphql-java/graphql-java/issues/2933

Reproduction of renaming scalars and applied directives bug

---

src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy

See https://github.com/graphql-java/graphql-java/issues/2877

Diff counts are the same

---

src/main/java/graphql/schema/Coercing.java

Addresses https://github.com/graphql-java/graphql-java/issues/2904 and update Coercing javadoc for clarity

Make parseValue nullable and update Coercing javadoc

---

src/main/java/graphql/schema/transform/FieldVisibilitySchemaTransformation.java
src/test/groovy/graphql/schema/transform/FieldVisibilitySchemaTransformationTest.groovy

Fixes a bug that happened when the field visibility transformation was applied to a schema that has some type(s) reachable only via directive definitions.

Stable port of Fix field visibility bug with enum with enum args (#2926)

---

src/main/java/graphql/schema/diff/SchemaDiff.java
src/test/groovy/graphql/schema/diff/SchemaDiffTest.groovy

#2935
See https://github.com/graphql-java/graphql-java/issues/2877

Stable port of Diff counts are the same

---

src/main/java/graphql/ExecutionResult.java
src/main/java/graphql/ExecutionResultImpl.java
src/main/java/graphql/cachecontrol/CacheControl.java
src/test/groovy/graphql/ExecutionResultTest.groovy
src/test/groovy/graphql/cachecontrol/CacheControlTest.groovy
src/test/groovy/graphql/introspection/IntrospectionResultToSchemaTest.groovy

We should have had this years ago.
I am using the `Builder<B>` pattern here off the interface - Spring style

Added new builder to ExecutionResult

---

src/main/java/graphql/introspection/IntrospectionQuery.java
src/main/java/graphql/introspection/IntrospectionQueryBuilder.java

Document the new IntrospectionQueryBuilder and tweaked it a little

---

src/main/java/graphql/execution/preparsed/persisted/PersistedQueryCache.java
src/test/java/benchmark/TwitterBenchmark.java

hi @bbakerman @andimarek 
Twitter Benchmark was not running anymore since the introduction of the max token validation.
I also did some other minor fixes (javadoc and unused imports)

Fixes in TwitterBenchmark

---

src/main/java/graphql/ErrorClassification.java
src/main/java/graphql/GraphQLError.java
src/main/java/graphql/GraphqlErrorBuilder.java
src/main/java/graphql/execution/Execution.java
src/test/groovy/graphql/GraphqlErrorBuilderTest.groovy
src/test/groovy/readme/ReadmeExamples.java

This makes it a smidger error to make errors

Adds an error builder on GraphQLError

---

src/test/java/benchmark/AddError.java
src/test/java/benchmark/BenchMark.java
src/test/java/benchmark/BenchmarkUtils.java
src/test/java/benchmark/DFSelectionSetBenchmark.java
src/test/java/benchmark/IntrospectionBenchmark.java
src/test/java/benchmark/NQBenchmark1.java
src/test/java/benchmark/NQBenchmark2.java
src/test/java/benchmark/NQExtraLargeBenchmark.java
src/test/java/benchmark/OverlappingFieldValidationBenchmark.java
src/test/java/benchmark/SchemaBenchMark.java
src/test/java/benchmark/SchemaTransformerBenchmark.java
src/test/java/benchmark/ValidatorBenchmark.java

@bbakerman  please have a look in case you're find this useful! :)

centralizing resource loading in BenchmarkUtils

---

src/main/java/graphql/normalized/ExecutableNormalizedField.java
src/test/groovy/graphql/normalized/ExecutableNormalizedFieldTest.groovy

Helper for getting fields based on object type name

---

src/main/java/graphql/execution/Async.java

@bbakerman @andimarek hello :) 
I'm trying to reduce some duplications in Async class. What do you think?

Avoiding some duplicated work in Async

---

src/test/groovy/graphql/i18n/I18nTest.groovy

It seems to work as expected on master
We will keep looking into this, checking on 19.x line say

Testing I18n lookup

---

src/main/java/graphql/i18n/I18n.java

master fix - use class loader on i18n

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
build.gradle
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

This PR updates graphql-java to Java 11 🎉 
The tests are passing locally and the build succeeds.
WIP as I need to check that GitHub builds succeed
Blog post coming soon

Turn it up to (Java) 11

---

src/main/antlr/GraphqlSDL.g4
src/main/java/graphql/parser/GraphqlAntlrToLanguage.java

Thanks @act1on3 and Daniela for identifying that an ANTLR rule could be approved & writing the fix
I am raising this PR on their behalf. @act1on3 I've added you as co-author, I didn't have Daniela's GitHub account or email.

Fix extend schema directives ANTLR rule

---

src/main/java/graphql/execution/instrumentation/SimpleInstrumentation.java
src/test/groovy/readme/InstrumentationExamples.java

Add documentation update from https://github.com/graphql-java/graphql-java-page/pull/116

Update instrumentation example in documentation

---

src/main/java/graphql/execution/instrumentation/dataloader/DataLoaderDispatcherInstrumentation.java

@bbakerman let's reuse the NOOP defined in the interface

Reuse ExecutionStrategyInstrumentationContext.NOOP in DataLoaderDispatcherInstrumentation

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/main/java/graphql/schema/diffing/ana/SchemaDifference.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Can't determine argument location without field name.
Skimmed through the rest of the schema and it seems fine.

Add missing detail

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
coding-guidelines.md
src/main/java/graphql/Scalars.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/directives/QueryAppliedDirective.java
src/main/java/graphql/schema/GraphQLAppliedDirective.java
src/main/java/graphql/schema/GraphQLArgument.java
src/main/java/graphql/schema/GraphQLDirective.java
src/main/java/graphql/schema/GraphQLEnumType.java
src/main/java/graphql/schema/GraphQLEnumValueDefinition.java
src/main/java/graphql/schema/GraphQLFieldDefinition.java
src/main/java/graphql/schema/GraphQLInputObjectField.java
src/main/java/graphql/schema/GraphQLInputObjectType.java
src/main/java/graphql/schema/GraphQLInterfaceType.java
src/main/java/graphql/schema/GraphQLList.java
src/main/java/graphql/schema/GraphQLNonNull.java
src/main/java/graphql/schema/GraphQLObjectType.java
src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/schema/GraphQLUnionType.java
src/main/java/graphql/util/EscapeUtil.java
src/test/groovy/example/http/HttpMain.java
src/test/groovy/example/http/QueryParameters.java
src/test/groovy/example/http/package-info.java

From #3082 I updated a bunch of `http://` links in JavaDoc

Updating the JavaDoc http links

---

src/main/java/graphql/schema/impl/SchemaUtil.java
src/test/groovy/graphql/TypeReferenceSchema.java
src/test/groovy/graphql/schema/impl/SchemaUtilTest.groovy

Resolve TypeReferences in schema applied directives

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/main/java/graphql/schema/diffing/ana/SchemaDifference.java
src/test/groovy/graphql/schema/diffing/SchemaDiffingTest.groovy
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Depends on #3102 otherwise I'd have to fix merge conflicts afterwards.

Handle enum value rename

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
build.gradle
src/main/resources/i18n/Parsing_de.properties
src/main/resources/i18n/Scalars_de.properties
src/main/resources/i18n/Validation_de.properties
src/test/groovy/graphql/execution/instrumentation/fieldvalidation/FieldValidationTest.groovy

The next release will be a non-breaking one, so I am temporarily reverting all Java 11 related changes.
We'll put these changes back in for our next breaking change release.
Original PRs
* Java 11 https://github.com/graphql-java/graphql-java/pull/3050
* ANTLR version upgrade https://github.com/graphql-java/graphql-java/pull/3059
* UTF-8 for German strings https://github.com/graphql-java/graphql-java/pull/3060

Downgrade to Java 8 ahead of release

---

src/main/java/graphql/execution/ExecutionStrategy.java

The different code path that existed prior to this change would omit the calls to `onFieldValuesInfo` when an `UnresolvedTypeException` occurred, and that causes a thread leak similar to an older issue for unhandled exceptions https://github.com/graphql-java/graphql-java/issues/2068 - that is, once a type cannot be resolved, the deeper batches from other (successful) branches are never dispatched.
Since we are just adding an error in the cases of `UnresolvedTypeException` and try to set the value to null, this only needed a small refactoring to make it similar to when the value is actually null.

Gracefully returning null in cases of UnresolvedTypeException

---

src/main/java/graphql/schema/diffing/DiffImpl.java
src/main/java/graphql/schema/diffing/FillupIsolatedVertices.java
src/main/java/graphql/schema/diffing/SchemaDiffing.java
src/main/java/graphql/schema/diffing/SchemaDiffingCancelledException.java
src/main/java/graphql/schema/diffing/SchemaDiffingRunningCheck.java

Adds `.stop()` function to `SchemaDiffing.java` and also checks for `Thread.interrupted()`

Add manual stop on algorithm

---

src/main/java/graphql/validation/AbstractRule.java
src/main/java/graphql/validation/RulesVisitor.java
src/main/java/graphql/validation/ValidationErrorType.java
src/main/java/graphql/validation/Validator.java
src/main/java/graphql/validation/rules/UniqueObjectFieldName.java
src/main/resources/i18n/Validation.properties
src/test/groovy/graphql/validation/rules/UniqueObjectFieldNameTest.groovy

Added UniqueObjectFieldName validation rule with a test that covers issue #1806.
This validation might be too broad?

UniqueObjectFieldName validation rule (#1806)

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

Ok I actually took a look through the entire `EditOperationAnalyzer` file, this should be the last of this type of fix.

Fix applied argument deleted on field

---

src/main/java/graphql/parser/ParseCancelledTooManyCharsException.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/SafeTokenReader.java
src/test/groovy/graphql/parser/ParserOptionsTest.groovy
src/test/groovy/graphql/parser/ParserStressTest.groovy
src/test/groovy/graphql/parser/SafeTokenReaderTest.groovy

Backport of https://github.com/graphql-java/graphql-java/pull/3148

Backport max chars fix to v17

---

src/main/java/graphql/parser/ParseCancelledTooManyCharsException.java
src/main/java/graphql/parser/Parser.java
src/main/java/graphql/parser/ParserOptions.java
src/main/java/graphql/parser/SafeTokenReader.java
src/test/groovy/graphql/parser/ParserOptionsTest.groovy
src/test/groovy/graphql/parser/ParserStressTest.groovy
src/test/groovy/graphql/parser/SafeTokenReaderTest.groovy

Backport of https://github.com/graphql-java/graphql-java/pull/3148

Backport max characters to 18.x

---

src/main/java/graphql/normalized/ExecutableNormalizedOperation.java
src/main/java/graphql/normalized/ExecutableNormalizedOperationFactory.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationFactoryTest.groovy

This gives us the ability to get to query directives from ENFs

The ability to get query directives in ENF land

---

src/main/java/graphql/schema/diffing/DiffImpl.java
src/main/java/graphql/schema/diffing/EditorialCostForMapping.java
src/main/java/graphql/schema/diffing/Mapping.java
src/main/java/graphql/schema/diffing/PossibleMappingsCalculator.java
src/main/java/graphql/schema/diffing/SchemaDiffing.java
src/main/java/graphql/schema/diffing/SchemaGraph.java
src/main/java/graphql/schema/diffing/SortSourceGraph.java
src/test/groovy/graphql/schema/diffing/SchemaDiffingTest.groovy

This improves the schema diffing algo in multiple ways with the goal to reduce runtime.

improve schema diffing performance

---

src/main/java/graphql/normalized/ExecutableNormalizedOperationToAstCompiler.java
src/test/groovy/graphql/normalized/ExecutableNormalizedOperationToAstCompilerTest.groovy

This PR will address issue #3292

write query directives from ENF to AST

---

src/main/java/graphql/execution/ValuesResolverConversion.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

This PR backports null value default value bugfix #3286 to v20.

20.x backport of #3286 null default value bugfix

---

src/main/java/graphql/validation/TraversalContext.java
src/main/java/graphql/validation/ValidationContext.java
src/main/java/graphql/validation/rules/VariableTypesMatch.java
src/main/java/graphql/validation/rules/VariablesTypesMatcher.java
src/main/resources/i18n/Validation.properties
src/main/resources/i18n/Validation_de.properties
src/test/groovy/graphql/execution/ValuesResolverE2ETest.groovy
src/test/groovy/graphql/validation/rules/VariableTypesMatchTest.groovy
src/test/groovy/graphql/validation/rules/VariablesTypesMatcherTest.groovy

Backports #3278 to 20.x which fixes a default value problem

20.x backport of #3278 default value bugfix

---

src/main/java/graphql/execution/ValuesResolverConversion.java
src/test/groovy/graphql/introspection/IntrospectionTest.groovy
src/test/groovy/graphql/schema/idl/SchemaPrinterTest.groovy

Cherry picks https://github.com/graphql-java/graphql-java/pull/3286 to 21.x which fixes a null default value problem

21.x Cherry pick pull request #3286

---

src/main/java/graphql/validation/TraversalContext.java
src/main/java/graphql/validation/ValidationContext.java
src/main/java/graphql/validation/rules/VariableTypesMatch.java
src/main/java/graphql/validation/rules/VariablesTypesMatcher.java
src/main/resources/i18n/Validation.properties
src/main/resources/i18n/Validation_de.properties
src/test/groovy/graphql/execution/ValuesResolverE2ETest.groovy
src/test/groovy/graphql/validation/rules/VariableTypesMatchTest.groovy
src/test/groovy/graphql/validation/rules/VariablesTypesMatcherTest.groovy

Cherry picks https://github.com/graphql-java/graphql-java/pull/3278 to 21.x which fixes a default value problem

21.x cherry pick of #3278 default value bugfix

---

build.gradle

guava version fix for 20.x

---

build.gradle

guava version fix for 21.x

---

build.gradle

guava version fix for master

---

src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

This shows the problem as reported in #3332 as happening
However I have another test that works and logically I cant see the difference.
Anyway here is a reproduction we can work on

Issue 3332 - overlapping aliases should be prevented

---

src/main/java/graphql/schema/usage/SchemaUsageSupport.java
src/test/groovy/graphql/schema/usage/SchemaUsageSupportTest.groovy

https://github.com/graphql-java/graphql-java/issues/3267

#3267 clear directives schema usage bug fix

---

src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/directives/QueryDirectivesImpl.java
src/main/java/graphql/execution/instrumentation/dataloader/FieldLevelTrackingApproach.java
src/main/java/graphql/execution/reactive/CompletionStageMappingPublisher.java
src/main/java/graphql/parser/MultiSourceReader.java
src/main/java/graphql/schema/DataFetchingFieldSelectionSetImpl.java
src/main/java/graphql/util/InterThreadMemoizedSupplier.java
src/main/java/graphql/util/LockKit.java
src/test/groovy/graphql/util/LockKitTest.groovy

This is sort of a POC but perhaps it can just be our approach to locking key structures
`synchronised` is simple but Loom does not like it
https://softwaremill.com/what-is-blocking-in-loom/
related also to https://github.com/quarkusio/quarkus/issues/35605#issuecomment-1700446616

removed synchronised from code base as much as possible for VT

---

build.gradle

Pulling in today's new java-dataloader release

Update DataLoader to 3.2.1

---

src/main/resources/i18n/Execution_nl.properties
src/main/resources/i18n/Parsing_nl.properties
src/main/resources/i18n/Scalars_nl.properties
src/main/resources/i18n/Validation_nl.properties

Hey guys,
These are Dutch translations. I can commit to maintaining them in the future. I'll periodically check for changes and you can always @ me.

Dutch translations for GraphQL Java

---

src/main/resources/i18n/Execution_de.properties
src/main/resources/i18n/Parsing_de.properties
src/main/resources/i18n/Scalars_de.properties
src/main/resources/i18n/Validation_de.properties

Should be reviewed by someone who also speaks German as I'm not a native speaker.

Update German translations

---

src/main/java/graphql/validation/ValidationError.java
src/test/groovy/example/http/ExecutionResultJSONTesting.java
src/test/groovy/graphql/ErrorsTest.groovy
src/test/groovy/graphql/GraphQLErrorTest.groovy
src/test/groovy/graphql/GraphqlErrorHelperTest.groovy
src/test/groovy/graphql/execution/DataFetcherResultTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyExceptionHandlingEquivalenceTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentEntryTest.groovy
src/test/groovy/graphql/language/SerialisationTest.groovy

Who needs named parameters anyway? 😉
Tidying up ahead of our next breaking release. I'm sure these constructors will NOT be missed.

Cleaning up ValidationError constructors

---

src/main/java/graphql/schema/PropertyFetchingImpl.java
src/main/java/graphql/schema/diff/SchemaDiff.java
src/main/java/graphql/util/StringKit.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy
src/test/groovy/graphql/util/StringKitTest.groovy

🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿🧿
This uses Locale.ROOT as suggested in the issue #3385

3385 - fix for the turkish eye 🧿

---

src/main/java/graphql/schema/diffing/ana/EditOperationAnalyzer.java
src/main/java/graphql/schema/diffing/ana/SchemaDifference.java
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerAppliedDirectivesTest.groovy
src/test/groovy/graphql/schema/diffing/ana/EditOperationAnalyzerTest.groovy

The new schema diffing didn't handle all the different changes to applied directives correctly. This adds much more coverage.

handle more Schema diff applied directives cases

---

src/main/java/graphql/execution/ValuesResolverOneOfValidation.java
src/test/groovy/graphql/execution/ValuesResolverTest.groovy

We were seeing occurrences of `NoSuchElementException`.

Fix oneOf bug when variables is empty

---

src/main/java/graphql/execution/instrumentation/ChainedInstrumentation.java
src/test/groovy/graphql/execution/instrumentation/ChainedInstrumentationStateTest.groovy

Small code tweaks on recent PR

---

src/main/java/graphql/schema/GraphQLSchema.java
src/test/groovy/graphql/schema/GraphQLSchemaTest.groovy

Fixes #3427 
Adds a forgotten builder method

Fix schema builder to copy extensionDefinitions

---

src/main/java/graphql/execution/ExecutionId.java
src/main/java/graphql/util/IdGenerator.java
src/test/groovy/graphql/util/IdGeneratorTest.groovy

As suggested by Rossen - tweaked the name ro be a betetr default name

Tweaked id generator name

---

src/test/java/benchmark/ComplexQueryBenchmark.java
src/test/resources/storesanddepartments.graphqls

I wanted to have a benchmark thats more complex, uses async code and sync code and also can be run in a forever manner you can attach a profiler to it say.
This is my attempt
I am not sure on the runtime profile of the code here - eg the sleeping and number of threads etc... but its a start

Added a more complex query benchmark

---

src/test/java/benchmark/ComplexQueryBenchmark.java

Now allows the benchmark to go into profiling mode - 2

---

src/test/java/benchmark/BenchmarkUtils.java
src/test/java/benchmark/ComplexQueryBenchmark.java

A common helper to allow us to attach a profiler and set it up (capture memory etc..) before we start the real work

Updated helper code for profiler attachment

---

src/test/java/benchmark/ComplexQueryBenchmark.java
src/test/java/benchmark/IntrospectionBenchmark.java
src/test/java/benchmark/QueryExecutionOrientedBenchmarks.java
src/test/java/benchmark/TwitterBenchmark.java

This adds a class that can run N benchmarks in one go
I also tweaked the "query oriented" benchmarks to be more consistent in how they run

Combined benchmark runner

---

src/main/java/graphql/schema/DefaultGraphqlTypeComparatorRegistry.java
src/main/java/graphql/schema/GraphQLTypeUtil.java
src/test/groovy/graphql/Issue3434.groovy

Fix printing of union types

---

src/main/java/graphql/GraphQLContext.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/execution/FieldValueInfo.java
src/main/java/graphql/execution/ResultNodesInfo.java
src/test/groovy/graphql/GraphQLTest.groovy
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/AsyncSerialExecutionStrategyTest.groovy

Backports PR #3525, which enables setting a maximum number of result nodes

19.x Backport PR 3525 max result nodes

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/FetchedValue.java
src/main/java/graphql/execution/FieldValueInfo.java
src/main/java/graphql/execution/ResultNodesInfo.java
src/test/groovy/graphql/GraphQLTest.groovy

See the original PR #3525 for more details. This backports a max result nodes limit

21.x backport 3525 max result nodes

---

src/main/java/graphql/introspection/Introspection.java
src/main/java/graphql/schema/diffing/SchemaGraph.java
src/main/java/graphql/util/CyclicSchemaAnalyzer.java
src/test/groovy/graphql/util/CyclicSchemaAnalyzerTest.groovy

This is a util class which analyses a GraphQL schema and finds all cycles inside the schema.

adding a cycle schema analyzer

---

src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ValuesResolver.java
src/main/java/graphql/schema/PropertyDataFetcherHelper.java
src/main/java/graphql/schema/PropertyFetchingImpl.java

more bottom of the barrel improvements
These ones are easy ish.
other closures are not so easy

Small tweaks to not allocate objects for lambda closures

---

src/main/java/graphql/parser/Parser.java
src/test/groovy/graphql/parser/ParserExceptionTest.groovy
src/test/groovy/graphql/parser/SDLParserTest.groovy

>  - Richard III by William Shakespeare

Removed deprecated methods in parsing

---

src/main/java/graphql/execution/preparsed/NoOpPreparsedDocumentProvider.java
src/main/java/graphql/execution/preparsed/PreparsedDocumentProvider.java
src/main/java/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCache.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQueryCache.java
src/main/java/graphql/execution/preparsed/persisted/PersistedQuerySupport.java
src/test/groovy/graphql/execution/preparsed/NoOpPreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/PreparsedDocumentProviderTest.groovy
src/test/groovy/graphql/execution/preparsed/TestingPreparsedDocumentProvider.groovy
src/test/groovy/graphql/execution/preparsed/persisted/ApolloPersistedQuerySupportTest.groovy
src/test/groovy/graphql/execution/preparsed/persisted/InMemoryPersistedQueryCacheTest.groovy

>  - Richard III by William Shakespeare

Removed deprecated methods in doc providers

---

src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/schema/DataFetchingEnvironmentImpl.java
src/test/groovy/graphql/execution/ExecutionContextBuilderTest.groovy

>   - Richard III by William Shakespeare

Removed deprecated methods in ExecutionContext

---

src/main/java/graphql/schema/GraphQLSchema.java
src/main/java/graphql/validation/TraversalContext.java
src/test/groovy/graphql/schema/visibility/GraphqlFieldVisibilityTest.groovy

>   - Richard III by William Shakespeare

Removed deprecated methods in GraphQLSchema

---

src/main/java/graphql/validation/ValidationError.java

>   - Richard III by William Shakespeare

Removed deprecated methods in ValidationError

---

src/main/java/graphql/schema/PropertyFetchingImpl.java
src/test/groovy/graphql/schema/PropertyDataFetcherTest.groovy

Cherry picks #3251 
This is a special release nominally for Atlassian only to allow progressive upgrade to an older system

Cherry pick PR #3251: Remove static record-like method lookup - for special 20.9 Atlassian release

---

src/main/java/graphql/GraphQLContext.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/introspection/GoodFaithIntrospection.java
src/main/java/graphql/introspection/Introspection.java
src/test/groovy/graphql/GraphQLContextTest.groovy

This helps make boolean decisions via the graphql context.  If `Boolean.TRUE.equals(val)` then its true

Added a getBoolean onto GraphQLContext.java

---

.github/workflows/pull_request.yml

Update GitHub pull request actions ahead of release

Update GitHub actions ahead of release

---

src/main/java/graphql/execution/instrumentation/FieldFetchingInstrumentationContext.java
src/main/java/graphql/execution/instrumentation/Instrumentation.java

Feedback from https://github.com/graphql-java/graphql-java/issues/3609 led to this javadoc

Better javadoc on beginFieldFetching

---

src/main/java/graphql/execution/CoercedVariables.java
src/main/java/graphql/execution/RawVariables.java

Closes #3628.
I have not bothered doing any unit tests of this very minor change, not least because best practices mean nobody should be relying on the output of a `toString()` method, anyway.  However, if you really want UTs for this, let me know and I can add them.
I have deliberately not put a descriptive wrapper around the `toString()` call to the internal object; but again, if you would prefer otherwise, please advise.
Thanks in advance for your review.

Add toString() implementations for RawVariables and CoercedVariables classes

---

src/main/java/graphql/execution/reactive/NonBlockingMutexExecutor.java

I dont think this is going to be ground breaking but its been sitting there since Java 8 days

Small tweak allowed on Java 9 and later

---

src/main/java/graphql/incremental/IncrementalPayload.java
src/test/groovy/graphql/incremental/DeferPayloadTest.groovy
src/test/groovy/graphql/incremental/StreamPayloadTest.groovy

The return type was wrong so you can't build objects properly.

Fix builder return type and expose generic toSpecification

---

src/main/java/graphql/parser/MultiSourceReader.java

Addressing the suggestion here which I like: https://github.com/graphql-java/graphql-java/pull/3670/files#r1687267538

Use static function to initialize a flag in MultiSourceReader

---

src/main/java/graphql/schema/diffing/DiffImpl.java
src/main/java/graphql/schema/diffing/SchemaDiffing.java

- improve performance for calc lower bounds costs
- fix sorting of initial vertices

schema diffing improvements

---

src/test/groovy/graphql/DefaultValuesTest.groovy

We have tests for default values but I added some more specifically for #3708 as a bug case
I think its working as expected

Added some more tests around providing default values

---

src/test/java/performance/ComplexQueryPerformance.java
src/test/java/performance/OverlappingFieldValidationPerformance.java
src/test/java/performance/PerformanceTestingUtils.java

This starts a new set of JMH testing which aims to be the set of performance test we will run regularly to monitor for performance regression/improvements.

initial tests for regular performance testing

---

build.gradle

Reverts graphql-java/graphql-java#3762

Revert "Bump biz.aQute.bnd.builder from 6.4.0 to 7.1.0"

---

src/main/java/graphql/execution/DataFetcherResult.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/FieldValueInfo.java

Cleaning up some methods deprecated for at least 1 year

Deprecation time

---

SECURITY.md
security/SECURITY_README.md
security/cve-sample.json

Add info on becoming a CNA and sample CVE submission payload template

Security updates

---

src/main/java/graphql/GraphqlErrorHelper.java
src/main/java/graphql/parser/ParserOptions.java

This annoys me - so I fixed it

Now there are zero javadoc errors during compile

---

src/main/java/graphql/execution/CoercedVariables.java
src/main/java/graphql/execution/RawVariables.java

Make CoercedVariables.emptyVariables() and RawVariables.emptyVariables() return an immutable singleton instance.

Return a singleton from CoercedVariables.emptyVariables and RawVariables.emptyVariables

---

agent-test/build.gradle
agent/build.gradle
build.gradle

Bump Shadow to support Java 24 usages in byte-buddy

---

src/main/java/graphql/schema/PropertyDataFetcher.java

Correct PropertyDataFetcher javadoc

---

src/main/java/graphql/validation/rules/OverlappingFieldsCanBeMerged.java
src/test/groovy/graphql/validation/rules/OverlappingFieldsCanBeMergedTest.groovy

The goal here is simplification and performance improvements.

call Overlapping validation only once during validation

---

src/main/java/graphql/execution/conditional/ConditionalNodes.java
src/main/java/graphql/normalized/nf/NormalizedDirective.java
src/main/java/graphql/normalized/nf/NormalizedDocument.java
src/main/java/graphql/normalized/nf/NormalizedDocumentFactory.java
src/main/java/graphql/normalized/nf/NormalizedField.java
src/main/java/graphql/normalized/nf/NormalizedFieldsMerger.java
src/main/java/graphql/normalized/nf/NormalizedOperation.java
src/main/java/graphql/normalized/nf/NormalizedOperationToAstCompiler.java
src/test/groovy/graphql/normalized/nf/NormalizedDocumentFactoryTest.groovy
src/test/groovy/graphql/normalized/nf/NormalizedOperationToAstCompilerTest.groovy

This is a version of ENFs without variables: NormalizedDocument and NormalizedField

Introduce NormalizedDocument and NormalizedField

---

src/test/java/performance/DFSelectionSetPerformance.java

Move DFSelectionSetBenchmark to performance suite to allow tracking of performance across releases

Move DFSelectionSetBenchmark to performance suite

---

.github/workflows/pull_request.yml
README.md
README.zh_cn.md

Config changes for the upcoming v23 release

Prepare for version 23

---

src/main/java/graphql/GraphQL.java
src/main/java/graphql/execution/AbstractAsyncExecutionStrategy.java
src/main/java/graphql/execution/DefaultResponseMapFactory.java
src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionContext.java
src/main/java/graphql/execution/ExecutionContextBuilder.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ResponseMapFactory.java
src/test/groovy/graphql/CustomMapImplementationTest.groovy
src/test/groovy/graphql/execution/DefaultResponseMapFactoryTest.groovy
src/test/groovy/graphql/execution/ExecutionTest.groovy
src/test/groovy/graphql/execution/instrumentation/fieldvalidation/FieldValidationTest.groovy

Proposal for #3857. I would like to write a unit test too: the idea is to make sure that all nested maps are really built with the customization.

ResponseMapFactory #3857

---

src/main/java/graphql/execution/ExecutionStrategy.java

cherry pick https://github.com/graphql-java/graphql-java/pull/3943 since this release was focused on avoid wrapping materialized objects in CFs
https://github.com/graphql-java/graphql-java/releases/tag/v22.0

avoid wrapping materialized fieldValueObject in a completable future

---

build.gradle

OSGI optional for 23.x

---

.github/workflows/pull_request.yml
build.gradle

Cherry picks 2 OSGI PRs to make JSpecify optional
https://github.com/graphql-java/graphql-java/pull/3949
https://github.com/graphql-java/graphql-java/pull/3959

24.x Cherry pick JSpecify OSGI config

---

build.gradle

Upgrade DataLoader to 5.0.0 for 24.0 release

Upgrade to DataLoader 5.0.0

---

build.gradle
src/test/groovy/graphql/execution/instrumentation/DataLoaderCacheCanBeAsyncTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/BatchCompareDataFetchers.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderCompanyProductBackend.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderCompanyProductMutationTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderNodeTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/Issue1178DataLoaderDispatchTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/PeopleCompaniesAndProductsDataLoaderTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/StarWarsDataLoaderWiring.groovy
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy
src/test/groovy/readme/DataLoaderBatchingExamples.java

Released today https://github.com/graphql-java/java-dataloader/releases/tag/v5.0.0

Add DataLoader 5.0.0

---

src/main/java/graphql/execution/DataFetcherResult.java
src/test/groovy/graphql/execution/DataFetcherResultTest.groovy
src/test/groovy/graphql/execution/instrumentation/DataLoaderCacheCanBeAsyncTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/BatchCompareDataFetchers.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderCompanyProductBackend.java
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderCompanyProductMutationTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderHangingTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderNodeTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/DataLoaderTypeMismatchTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/Issue1178DataLoaderDispatchTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/PeopleCompaniesAndProductsDataLoaderTest.groovy
src/test/groovy/graphql/execution/instrumentation/dataloader/StarWarsDataLoaderWiring.groovy
src/test/groovy/graphql/schema/DataFetchingEnvironmentImplTest.groovy
src/test/groovy/readme/DataLoaderBatchingExamples.java

Cherry picks these helper methods on DataFetcherResult for 24.0 https://github.com/graphql-java/graphql-java/pull/3964
Also include extra DataLoader updates

Cherry pick DataFetcherResult helpers

---

src/main/java/graphql/schema/SingletonPropertyDataFetcher.java

Cherry pick of #3942 for 24.0 release

Cherry pick PR 3942 To add singleton to factory method

---

src/main/java/graphql/execution/AsyncSerialExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/main/java/graphql/execution/incremental/DeferredExecutionSupport.java

Cherry picks #3935 for 24.0 release

Cherry pick PR 3935

---

src/jmh/java/graphql/execution/ExecutionStepInfoBenchmark.java
src/main/java/graphql/execution/ExecutionStepInfo.java
src/main/java/graphql/execution/ExecutionStepInfoFactory.java
src/main/java/graphql/execution/ExecutionStrategy.java

Cherry pick #3934 for 24.0 release

Cherry pick 3934 for execution step info builder changes

---

src/main/java/graphql/analysis/values/ValueTraverser.java
src/main/java/graphql/collect/ImmutableKit.java
src/main/java/graphql/execution/instrumentation/fieldvalidation/FieldValidationSupport.java
src/main/java/graphql/language/AstSignature.java
src/main/java/graphql/language/Document.java
src/main/java/graphql/language/NodeParentTree.java
src/main/java/graphql/language/SelectionSet.java
src/main/java/graphql/schema/visibility/BlockedFields.java
src/test/groovy/graphql/collect/ImmutableKitTest.groovy
src/test/groovy/graphql/util/FpKitTest.groovy

Cherry pick #3931 for 24.0 release

Cherry pick 3931 imperative filters

---

src/main/java/graphql/execution/Execution.java
src/main/java/graphql/execution/ExecutionStrategy.java
src/main/java/graphql/execution/ExecutionStrategyParameters.java
src/main/java/graphql/execution/NonNullableFieldValidator.java
src/main/java/graphql/execution/SubscriptionExecutionStrategy.java
src/test/groovy/graphql/execution/AsyncExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/AsyncSerialExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyParametersTest.groovy
src/test/groovy/graphql/execution/ExecutionStrategyTest.groovy
src/test/groovy/graphql/execution/NonNullableFieldValidatorTest.groovy

Cherry pick #3929 for 24.0 release

Cherry pick PR 3929 reduce nonnullablefieldvalidator allocations

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
src/main/java/graphql/GraphqlErrorHelper.java
src/test/groovy/graphql/GraphqlErrorHelperTest.groovy

This is backport of #3987 for 24.1

Deterministic source location backport 24

---

README.md
README.zh_cn.md

Small fix to update the badges, and I noticed we forgot to add the book to the Chinese readme
It says "we wrote a book!"

Update badges and add book link

---

src/main/java/graphql/introspection/Introspection.java

Removed ' character from introspection messages

---

src/jmh/java/performance/DataLoaderPerformance.java
src/main/java/graphql/execution/instrumentation/dataloader/PerLevelDataLoaderDispatchStrategy.java

perf improvements for chained DataLoaders.

chained data loader performance improvements
